### ISSUE TITLE
Stackblitz Deployment issue - Angular Material Snackbar

### ISSUE THREAD

**Issue by trevordowdle** [stackblitz/core#1029]
#### Reproduction

Steps to reproduce:
1. Open the [Basic snack-bar example](https://stackblitz.com/angular/yjpqxkjprxej?file=app%2Fsnack-bar-overview-example.ts) in stackblitz.
2. Fork the project and perform a firebase deploy via stackblitz.
3.  Open the [deployed project](https://testproject-4fc07.firebaseapp.com/?46571) in **Safari** and summon forth a snackbar.
 
 
#### Expected Behavior

What behavior were you expecting to see?
A snackbar

#### Actual Behavior

What behavior did you actually see?
A supersized-bar

<img width="654" alt="Screen Shot 2019-07-24 at 6 48 30 PM" src="https://user-images.githubusercontent.com/4210581/61838180-56939600-ae45-11e9-9392-c4356c2ac72b.png">

#### Environment

Safari, on Mac OS and IOS

This only happens on the deployment version, I can't figure out what is causing it.  But i'm hoping someone could help know what changes can be made in the stackblitz project in order for the bug not to show up on deploy.  Or is this strictly a firebase deployment bug?

I found a reference to a similar issue [here](https://github.com/angular/components/issues/14376), the solution seemed simple enough and was due to not closing html tag(s) properly or not having an html doc type declaration.  However I tried checking both of those things and it still happens after deploy.

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is what I see from your app on Safari and Chrome. It's possible that this issue has been fixed from various code changes since the inception of this issue. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-15 at 4 13 51 PM](https://user-images.githubusercontent.com/49956513/118376895-b322f080-b598-11eb-8898-a9d87b2c2024.png)
![Screen Shot 2021-05-15 at 4 12 45 PM](https://user-images.githubusercontent.com/49956513/118376896-b322f080-b598-11eb-9570-94eacda95e2f.png)
