### ISSUE TITLE
Angular GitHub project fails to build

### ISSUE THREAD

**Issue by mcosta74** [stackblitz/core#1041]
Here the link to the [project](https://stackblitz.com/github/mcosta74/ClrDialog)

it works locally and on [GitHub pages](https://mcosta74.github.io/ClrDialog/)

**Comment by purplem1lk** [comment]
Thank you for your patience - This is what I see when I go to your StackBlitz project link. It's possible that code changes since the inception of this issue have fixed this issue. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-20 at 7 53 28 PM](https://user-images.githubusercontent.com/49956513/119062539-0e901c80-b9a5-11eb-834d-fa960e9afe0a.png)
