### ISSUE TITLE
When click GitHub Sign in got an error

### ISSUE THREAD

**Issue by TroyEdwardLee** [stackblitz/core#1047]
![image](https://user-images.githubusercontent.com/45854080/63490446-483da600-c4e7-11e9-8375-266663d0fa81.png)

**Comment by ItsMeRTXYZ** [comment]
Same

**Comment by ItsMeRTXYZ** [comment]
This needs to be fixed

**Comment by ItsMeRTXYZ** [comment]
@EricSimons @beeman @wmhilton

**Comment by ItsMeRTXYZ** [comment]
Just change your email

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm pasting a great reply from one of the StackBlitz developers to help with this type of issue:

So when this happens, it's likely that it's because of an email or username collision. The error message isn't helpful and we need to work on that.

**So what does this mean?**
It happens if for instance someone creates two GitHub accounts with the same email address. So account A and account B have the same email address. Someone signs in with account A at StackBlitz. Later that person signs in with account B, then we have a collision.

It can also happen with a username. If account A has username Foo, signs in at StackBlitz. Then account A gets renamed to FooBar and a second account B is being created with username Foo. If account B signs in, we know have a username collision because that username is taken by someone else.

**How to resolve?**
If it's an email collision, you have two options 
1. Update email at Account B to have a +github added or something so the email is different from Account A.
2. Update email at Account A to something else, sign in with Account A at StackBlitz so the information in our database gets updated. Afterwards, sign in with Account B and now it should work.

If it's a username collision, it probably depends. If some random person once was in possession of your current GitHub username and signed in at StackBlitz, we will have to fix it manually on our side. If you are in possession of both GitHub accounts, it's basically the same as solution 2 of the email collision flow. Sign in with Account A so the info gets updated on our side, then sign in with account B and it should work.

Hopefully, this resolves the issue - If this issue persists, feel free to tag me or ask me to reopen this issue. Thank you! :)
