### ISSUE TITLE
Broken - output blinks and then is blank

### ISSUE THREAD

**Issue by TPReal** [stackblitz/core#1059]
My project backed by a GitHub repo https://stackblitz.com/edit/tp-svg-cut is showing correctly when I open it in an incognito tab, but when I open it in a browser were I'm logged in then that's what happens:
1. There's "initializing git repository" overlay on the code, and "starting dev server" on the output pane.
2. After a second or so, the overlay on the code switches to "updating branches" or similar, and the output shows the correct output.
3. Finally, after another second, there is no more overlay on the code, and the output pane reloads by itself, and becomes blank. Any further reloads (by editing or by the reload button) leave it blank. DOM inspection shows empty <body>.

**Comment by TPReal** [comment]
Guys, this is serious, it's broken, I checked a couple of browsers and systems and it's the same everywhere. I'm basically looking for a different IDE now.

**Comment by purplem1lk** [comment]
Thank you for your patience - This is what I see when I open your StackBlitz project link. You mentioned that this seems to when you're logged in. Can you provide a screenshot/screencast of what you're seeing since we're unable to reproduce this? It's also possible that code changes made since the inception of this issue have fixed this issue. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-20 at 8 43 11 PM](https://user-images.githubusercontent.com/49956513/119065644-fff93380-b9ab-11eb-82e3-d51c8a932ea2.png)

**Comment by TPReal** [comment]
Ah, yes, it seems to have fixed itself some time during the last year and a half...
