### ISSUE TITLE
Import from github doesn't work with latest version create-react-app

### ISSUE THREAD

**Issue by alimansoori** [stackblitz/core#1075]
[https://stackblitz.com/github/alimansoori/create-react-app](https://stackblitz.com/github/alimansoori/create-react-app)

The **preview** is not displayed in latest version create-react-app

My github repo is :
[https://github.com/alimansoori/create-react-app](https://github.com/alimansoori/create-react-app)

**Comment by purplem1lk** [comment]
Thank you for your patience - I've attached a screenshot of what I see when I click your project link. I'm unsure if this is what you're expecting, but we are unable to move forward without further information about the expected behavior. If this issue persists, feel free to tag me or ask to reopen this issue with expected behavior criteria. Thank you! :)

![Screen Shot 2021-05-22 at 4 45 23 PM](https://user-images.githubusercontent.com/49956513/119240379-1e327100-bb1d-11eb-8296-39bbef50ae65.png)
