### ISSUE TITLE
Can not sign in 

### ISSUE THREAD

**Issue by halljames631** [stackblitz/core#1079]
when trying to sign into stackblitz. it say "Yikes! Something went wrong with your request."
<img width="839" alt="Screen Shot 2019-10-13 at 11 14 49 AM" src="https://user-images.githubusercontent.com/54309614/66717758-b21d5200-edaa-11e9-975e-13f34a280420.png">

**Comment by purplem1lk** [comment]
Thank you for your patience. I've pasted a reply from one of the StackBlitz devs from #1402 below.

So when this happens, it's likely that it's because of an email or username collision.

**So what does this mean?**
It happens if for instance, someone creates two GitHub accounts with the same email address. So account A and account B have the same email address. Someone signs in with account A at StackBlitz. Later that person signs in with account B, then we have a collision.

It can also happen with a username. If account A has the username Foo, signs in at StackBlitz. Then account A gets renamed to FooBar and a second account B is being created with username Foo. If account B signs in, we know have a username collision because that username is taken by someone else.

**How to resolve?**
If it's an email collision, you have two options

Update email at Account B to have a +github added or something so the email is different from Account A.
Update email at Account A to something else, sign in with Account A at StackBlitz so the information in our database gets updated. Afterward, sign in with Account B and now it should work.
If it's a username collision, it probably depends. If some random person once was in possession of your current GitHub username and signed in at StackBlitz, we will have to fix it manually on our side. If you are in possession of both GitHub accounts, it's basically the same as solution 2 of the email collision flow. Sign in with Account A so the info gets updated on our side, then sign in with account B and it should work.

If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and any screenshots/screencast to support. Thank you! :)
