### ISSUE TITLE
adding github dependency leads to uncaught exception

### ISSUE THREAD

**Issue by cristianbogdan** [stackblitz/core#1081]
adding this project dependency
https://github.com/cristianbogdan/react-basic-draw-presentation#0.1.7

shows this uncaught Error on the console:
```
webcontainer.7d044722a80339d7d45.js:8 Uncaught (in promise) Error
    at new o (https://c.staticblitz.com/d/webcontainer.7d044722a80339d7d45.js:8:70015)
    at e.mount (https://c.staticblitz.com/d/webcontainer.7d044722a80339d7d45.js:8:153432)
    at https://c.staticblitz.com/d/webcontainer.7d044722a80339d7d45.js:8:86308
    at Function.e.Create (https://c.staticblitz.com/d/webcontainer.7d044722a80339d7d45.js:8:96975)
    at https://c.staticblitz.com/d/webcontainer.7d044722a80339d7d45.js:8:86103
    at async Promise.all (index 0)
    at async Promise.all (index 0)

o | @ | webcontainer.7d044722a80339d7d45.js:8
-- | -- | --
  | e.mount | @ | webcontainer.7d044722a80339d7d45.js:8
  | (anonymous) | @ | webcontainer.7d044722a80339d7d45.js:8
  | e.Create | @ | webcontainer.7d044722a80339d7d45.js:8
  | (anonymous) | @ | webcontainer.7d044722a80339d7d45.js:8
  | Promise.then (async) |   |  
  | (anonymous) | @ | engineworker-294a7c2….js:1
  | (anonymous) | @ | engineworker-294a7c2….js:1
  | dispatch | @ | engineworker-294a7c2….js:1
  | (anonymous) | @ | engineworker-294a7c2….js:1
  | t.onmessage | @ | engineworker-294a7c2….js:1
```

Not sure if the two are related but
```
import x from 'react-basic-draw-presentation' 
console.log(x)
```
prints
```
{}
```

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click on your project link (https://stackblitz.com/edit/react-basic-draw-presentation) from the GitHub repository you linked. We are unable to provide assistance without being able to reproduce the issue you're seeing. It's possible that code changes that were made since the inception of this issue fixed it. If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of your error. Thank you! :)

![Screen Shot 2021-05-22 at 4 58 06 PM](https://user-images.githubusercontent.com/49956513/119240629-e4fb0080-bb1e-11eb-8829-90dc618dbc29.png)
