### ISSUE TITLE
typescript, webpack, react & mobx project

### ISSUE THREAD

**Issue by ShaunWMusic** [stackblitz/core#1086]
This project type is not yet supported. We currently only support projects scaffolded with @angular/cli. If you think this is a bug, please file an issue in our repo!

**Comment by purplem1lk** [comment]
Thank you for your patience - There have been several projects added since the inception of this issue so we recommend checking them out on the new StackBlitz site. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of your error/expected behavior. Thank you! :)
