### ISSUE TITLE
attributeChangedCallback throws error

### ISSUE THREAD

**Issue by thepassle** [stackblitz/core#1095]
Adding an `attributeChangedCallback` to a custom element results in an error:

```
Error in /~/01-basic/05-mutating-attributes.js (28:16)
Failed to execute 'define' on 'CustomElementRegistry': Iterator getter is not callable.
```

<img width="1680" alt="Screenshot 2019-11-09 at 16 30 57" src="https://user-images.githubusercontent.com/17054057/68531044-783e5d80-030e-11ea-97c4-3bb3d5a6bf1b.png">

Link to the stackblitz: https://stackblitz.com/edit/open-wc-vanilla-demos

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click your project link. It's possible that code changes made since the inception of this issue have fixed it. If your issue persists, feel free to tag me or ask to reopen this issue with further screenshots of the errors you see. Thank you! :)

![Screen Shot 2021-05-22 at 5 21 18 PM](https://user-images.githubusercontent.com/49956513/119241113-2214c200-bb22-11eb-9f39-a0dec6ad804f.png)
