### ISSUE TITLE
Error with a specific @progress package version

### ISSUE THREAD

**Issue by tsvetomir** [stackblitz/core#1119]
I get the following error when when running [this snippet](https://stackblitz.com/edit/angular-fdlh5g?file=src/app/app.module.ts) on StackBlitz.

```
Uncaught (in promise) Error: Error: EISDIR: File is a directory., '/package.json'
```

```
Uncaught (in promise) Error
    at new o (https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:70015)
    at Function.o.FileError (https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:70394)
    at Function.o.EISDIR (https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:70569)
    at e.preloadFile (https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:97502)
    at https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:85477
    at Function.e.Create (https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:96917)
    at https://c.staticblitz.com/d/webcontainer.3a5e72d1ca6ef3f98e9.js:8:85179
    at async Promise.all (index 15)
    at async Promise.all (index 0)
```

The error is triggered by `@progress/kendo-angular-dropdowns@4.2.2`. Switching to version 4.2.1 seems to resolve the issue, see [forked snippet](https://stackblitz.com/edit/angular-opvrmh?file=src%2Fapp%2Fapp.component.html).

I couldn't spot any significant differences between the two package versions. The same version also works fine in a regular project.

What could be causing this error?

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click the first snippet you linked. We are unable to provide assistance without being able to reproduce the issue. It's possible that code changes made since the inception of this issue have fixed it. We appreciate you bringing up this issue! If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of your error. Thank you! :)

![Screen Shot 2021-05-22 at 5 47 34 PM](https://user-images.githubusercontent.com/49956513/119241613-ccdaaf80-bb25-11eb-9af0-c321b865c955.png)

**Comment by tsvetomir** [comment]
Seems to work fine now, thanks for taking a look!
