### ISSUE TITLE
Import from GitHub fails for repo using React 16.12, but not repo using React 16.10.2

### ISSUE THREAD

**Issue by DTHutton** [stackblitz/core#1136]
#### Error Message
> The dependencies for this project couldn't be resolved.
> This usually means that a dependency in your package.json is incorrect.
> If you think this is a bug, please file an issue in our repo!

I get this error when trying to import [this pre-existing react app](https://github.com/DTHutton/word-guess-react) from GitHub. I do _not_ get the error when trying to import [this pre-existing react app](https://github.com/DTHutton/hw-19-clicky-game). 

Both projects were created with [create-react-app](https://github.com/facebook/create-react-app), but different versions. The only difference in dependencies that I can see is the addition of testing libraries for the failed import.

#### Successful Import
- [Repo](https://github.com/DTHutton/hw-19-clicky-game)
- [create-react-app v3.2.0](https://github.com/facebook/create-react-app/releases/tag/v3.2.0)
- Dependencies:
"dependencies": {
    "gh-pages": "^2.1.1",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-scripts": "3.2.0"
  }

#### Failed Import
- [Repo](https://github.com/DTHutton/word-guess-react)
- [create-react-app v3.3.0](https://github.com/facebook/create-react-app/releases/tag/v3.3.0)
- Dependencies:
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"
  }

Any help on this would greatly appreciated.

**Comment by kc0tlh** [comment]
@DTHutton this issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!

<img width="1437" alt="image" src="https://github.com/stackblitz/core/assets/1532264/566d33f9-af7b-413b-8b24-7816019efa2f">

Simply add [pr.new/](https://developer.stackblitz.com/codeflow/using-pr-new) in front of the repo name to import. For example: [pr.new/github.com/DTHutton/word-guess-react](https://pr.new/github.com/DTHutton/word-guess-react)

More info on opening Github repos in StackBlitz can be found [here in our docs](https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide).

Related issue: https://github.com/stackblitz/core/issues/2473
