### ISSUE TITLE
Bug: No error reported for multiple let or const declarations

### ISSUE THREAD

**Issue by jostschmithals** [stackblitz/core#1140]
This code ...

```
let x = 1;
let x = 2;

const y = 3;
const y = 4;

console.log('x =', x);
console.log('y =', y);
```

... doesn't produce an error, as it should do ( "Uncaught SyntaxErrors: Identifier ... has already been declared"), and the first `const` value is overwritten in the console output, without any error.

[https://stackblitz.com/edit/stackblitz-bug-duplicated-let-and-const-declarations](https://stackblitz.com/edit/stackblitz-bug-duplicated-let-and-const-declarations)

**Comment by karocksjoelee** [comment]
any update on this ?

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click your project link. It's possible that code changes made since the inception of this issue have fixed it. If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of your error. Thank you! :)

![Screen Shot 2021-05-23 at 12 49 43 PM](https://user-images.githubusercontent.com/49956513/119269368-5c836b00-bbc5-11eb-8795-f371ea86f018.png)
