### ISSUE TITLE
Angular index.html is missing doctype when deployed to Firebase

### ISSUE THREAD

**Issue by budgetlauncher-admin** [stackblitz/core#1156]
Create a new (blank) Angular project. The index.html that is generated for the local dev server starts with <!doctype html> as expected. However, when deploying to Firebase, the index.html that is generated and deployed does not have <!doctype html>. This causes issues with Angular Material.

**Comment by Aidan-Chey** [comment]
hey there @budgetlauncher-admin 
I came accross your issue here while googling the same issue you seem to be experiencing (new angular project with firestore integration).

I seems you may have posted this issue in the incorrect github repository, this is in [stackblitz/core](https://github.com/stackblitz/core) where it should probably be in [angular/angular](https://github.com/angular/angular) or [angular/angularfire](https://github.com/angular/angularfire).

I'd recommend you delete or close this issue.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing or being able to reproduce it and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
