### ISSUE TITLE
Can't SignIn after changing GitHub username

### ISSUE THREAD

**Issue by dzintars** [stackblitz/core#1182]
Recently i changed my GitHub username. Primary email is still the same but old username now is an GitHub organization.
Now when i try to SignIn i do receive `Yikes! Something went wrong with your request.`.
I believe the only way to solve this issue is to manually remove OAuth connection from my account so i can re-authorize and sign in again.
I tried to remove Authorized OAuth Stackblitz app from my GitHub account and to SignIn again, but with no luck, probably because of email.
But in general... this should be handled somehow more user friendly way. Mby handle new username/credentials of that email in your side automatically?

#1146 #1127 #1103 #1096 #1079 #1047 #934 #760

**Comment by ronCYA** [comment]
Yeah users shouldn't get a "Yikes!" message for username change. Accounts should be tied to their ID which is just as easy to grab but does not change like e-mail and username:

https://api.github.com/users/kgish

**Comment by curiouscod3** [comment]
I have a same issue.. Can't log in.. but I can log in with other github accounts. It is weird
https://github.com/stackblitz/core/issues/1146
Please tell me how to fix and log in

**Comment by iamsrk** [comment]
Yeah I too have the same issue. Please fix it quick.

**Comment by curiouscod3** [comment]
**Do StackBliz.com members read these complains? they don't care?** Please reset my account and let me sign in again..I am assuming this is because I changed my username of Github.

**Comment by kc0tlh** [comment]
This error will occur if you don't have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page:​ https://github.com/settings/emails

If the issue persists, it is likely you have **two GitHub accounts with the same email address and/or username**. If this is the case, simply change the email address and/or username on the new Github account that you would like to log into StackBlitz with.

Tip: If you don't want to change your Github email address you can instead update it to have a +github added to the end, so it is unique. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.

This issue was discussed last year in issue #1402 for additional context.

Hopefully this resolves the issue for you. If not, don't hesitate to reply and we'll have a closer look.

**Comment by dzintars** [comment]
For sure my emails in GH is 100% verified.
