### ISSUE TITLE
unable to install firebase-admin

### ISSUE THREAD

**Issue by schnapper79** [stackblitz/core#1191]
I tried to add "firebase-admin":"^8.9.2" as a dependency. But installation fails for adding "jwa":"^2.0.0".

Trying to install jwa only and let your package manager decide which version of jwa is latest, it installs version 1.4.1, which is more than 3 months old. Can you please fix your npm caches more often than just once in a while?

**Comment by Ahmad-Saleh89** [comment]
I'm having the same issue. i hope it gets fixed soon

**Comment by sulco** [comment]
Thanks for reaching out! 
We've undergone a series of updates to the platform since this issue was submitted and it does no longer seem to appear (I've tried it with installing firebase-admin `8.9.2` and the latest `9.5.0` which has been published 2 days ago)

Closing for now, please free to reopen if you're still experiencing it!
