### ISSUE TITLE
Formatting does not work in Safari Browser

### ISSUE THREAD

**Issue by uloco** [stackblitz/core#1204]
The title says it already.
I tried it with a new react.js project.
Format document does not work.
Chrome works fine.

**Comment by fvsch** [comment]
Thanks for the report @uloco.

Tested today in Safari 15.4 on macOS, and formatting with Prettier is working well.

For the record, we shipped a significant update of our formatting logic (and upgraded our Prettier version to 2.4) in September 2021, so that could have fixed the issue. Or maybe recent releases of Safari improved Web standards support that were triggering the previous issue.

I’m considering this fixed for now, but feel free to open a new issue with an example project and information on the specific Safari version you're testing if it's still broken for you.
