### ISSUE TITLE
Github Oauth login is not working after updated the email id of the Github account.

### ISSUE THREAD

**Issue by ganesa-vijayakumar** [stackblitz/core#1244]
Hi Team,

Let me explain my case. I had two Github accounts `GanesaVijayakumar` and `ganesa-vijayakumar`. I used the account `ganesa-vijayakumar` to get into Stackbliz and created a few repositories too. After a few years, I was in the process of merging the accounts into one by swapping the usernames and also updating the emails.
- Updated the username `ganesa-vijaykumar` to `ganesa-vijayakumar1`
- Updated the username `GanesaVijayakumar` to `ganesa-vijayakumar`
- Updated the first account username `ganesa-vijayakumar1` to `GanesaVijayakumar`
- Transferred the same email id to the newly modified account `ganesa-vijayakumar` and used a different email address for the second account `GanesaVijayaumar`

Now, If I trigger the OAuth login with the current account `ganesa-vijayaumar` (which has the same email address) it is not login into the account instead of getting a message `Yikes! Something went wrong with your request.`.

I'm not sure what are the details that you are considering for login (maybe username and email address). Is there any possibility to use my Stackblitz account with the current active GitHub account `ganesa-vijayakumar`.

Thanks,
Ganesa

**Comment by kc0tlh** [comment]
The issue here is that StackBlitz is seeing you attempt to login with the same email address, but a new username. This is causing a collision on our end. We will be revamping this flow in the future (@apai4 / @HeyGarrison tagging you both for awareness), but currently the workaround below should resolve your issue:

To resolve this you could add a +github added to the end of your email address in github, so it is unique in our database. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.

This issue was discussed last year in issue https://github.com/stackblitz/core/issues/1402 for additional context.

Hopefully this resolves the issue for you. If not, don't hesitate to reply and we'll have a closer look.

**Comment by ganesa-vijayakumar** [comment]
It helps. Thanks, @kc0tlh.
