### ISSUE TITLE
How to update the project info text

### ISSUE THREAD

**Issue by simonssspirit** [stackblitz/core#1277]
How to update the project info text.

When we use a GitHub repo to load in StackBlitz there is an info text loaded.

It seems to be connected to the About info on the page, but even after updating the text, it is the same in the StackBlitz projects. Can it be updated?

![image](https://user-images.githubusercontent.com/11087921/88171334-d2c2e400-cc27-11ea-9157-8026e0fad070.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - I was able to update the text in the 'Info' section and saw the new text reflected in the project, as well as the dashboard. It's possible that code changes made since the inception of this issue have fixed it. If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-23 at 2 45 14 PM](https://user-images.githubusercontent.com/49956513/119272744-7fb61680-bbd5-11eb-969a-57570838be8d.png)
![Screen Shot 2021-05-23 at 2 45 34 PM](https://user-images.githubusercontent.com/49956513/119272754-8b094200-bbd5-11eb-8668-f1292d03e31b.png)
