### ISSUE TITLE
stackblitz Can't find package …what exactly stackblitz trying to do when pkg name is capitalized by mistake

### ISSUE THREAD

**Issue by NaraGitHub** [stackblitz/core#1301]
![image](https://user-images.githubusercontent.com/16210020/92772529-6e87eb00-f361-11ea-9ce4-6b70b20213c8.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of a project where I added Redux, but did not see the same error as you. It's possible that code changes made since the inception of this issue have fixed this issue. If your issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

![Screen Shot 2021-05-23 at 2 59 59 PM](https://user-images.githubusercontent.com/49956513/119273160-8e9dc880-bbd7-11eb-9069-ce025da0f099.png)
