### ISSUE TITLE
Embedded stackblitz Fork / Save not working (Cookie?)

### ISSUE THREAD

**Issue by Giusti** [stackblitz/core#1317]
It seems that the Fork button inside the embedded stackblitz ist not working anymore, instead returning error 422.

I am using the stackblitz sdk like this:

`sdk.embedProjectId(
        'stackblitz',
        repo.name,
        {
          height: '100%',
          openFile: app.component.ts
        }
      );`

After analysing a bit, it seems that issue is related to chromes same site cookie changes? 
To verify I have changed the cookie default flags in the `chrome://flags` settings like this

![image](https://user-images.githubusercontent.com/6214919/95952645-c8fce700-0df8-11eb-9c1d-6032001ccc11.png)

And now the fork and sign in work correctly inside my embedded stackblitz

It seems the cookies have to be set from `SameSite=Lax` to `SameSite=None` if I understood correctly for 3rd party to work with cookies.

Another thing I noticed is, that when I sign in inside the embedded stackblitz, even tho I am the author of the stackblitz repo, the save button does not appear anymore therefore I am unable to save my work.

With the SameSite cookies disabled, I am automatically logged in and the save button is visible and works as expected.

**Comment by sagar7993** [comment]
I'm facing the same problem. The Stackblitz SDK is not usable at all due to this problem

**Comment by sagar7993** [comment]
@EricSimons Could you look into this

**Comment by fvsch** [comment]
Hi folks, thanks for the report!

It looks like the issue comes from embedding StackBlitz projects without the `embed=1` query parameter (or the corresponding `{ forceEmbedLayout: true }` option for the SDK). We recently changed the SDK to set this option by default (starting from v1.7.0).

Currently we don't officially support the full StackBlitz editing workflow in iframes, including:

- using the editor's full feature set;
- logging into stackblitz.com inside an iframe;
- forking projects inside iframes;
- saving changes to projects inside iframes.

What's more, browsers are moving to use double-keyed storage buckets for embedded sites, so that stackblitz.com opened as a top-level page and stackblitz.com opened in an iframe on a different origin would use separate storage buckets. So the problems reported here are most likely becoming long-term restrictions, and we're not looking into working around them at this time.

We recommend that people use embeds for showing StackBlitz projects to users and letting them play around and make changes, and use https://stackblitz.com directly for editing projects.
