### ISSUE TITLE
sign in with github account

### ISSUE THREAD

**Issue by tfey** [stackblitz/core#1323]
why I am not able to sign in with my github user account?

**Comment by CoderNinja123-alt** [comment]
Ya @tfey ! Same here! Unable to sign up with my account!

**Comment by d3r1n** [comment]
I can not sign in too its shows this website [URL](https://stackblitz.com/api/users/auth/github/callback?code=263f140ab9ba5b0bde64&state=cc0143a9592c0d155754a50389110537d856e0707fda0686)

**Comment by kallenkortuem** [comment]
I also cannot sign in anymore and I don't remember if I have a subscription membership setup so it is important to me that I can log in.

One likely cause for my case is that I changed my GitHub username.

Either way this really needs to be addressed since I am/was a paying customer.

**Comment by d3r1n** [comment]
I guess modes are **_sleeping_** ☹

**Comment by purplem1lk** [comment]
Thank you for your patience - I have pasted a reply from one of the StackBlitz devs from #1402 about how to navigate this issue:

So when this happens, it's likely that it's because of an email or username collision.

**So what does this mean?**
It happens if for instance, someone creates two GitHub accounts with the same email address. So account A and account B have the same email address. Someone signs in with account A at StackBlitz. Later that person signs in with account B, then we have a collision.

It can also happen with a username. If account A has the username Foo, signs in at StackBlitz. Then account A gets renamed to FooBar and a second account B is being created with username Foo. If account B signs in, we know have a username collision because that username is taken by someone else.

**How to resolve?**
If it's an email collision, you have two options

Update email at Account B to have a +github added or something so the email is different from Account A. Update email at Account A to something else, sign in with Account A at StackBlitz so the information in our database gets updated. Afterward, sign in with Account B and now it should work.

If it's a username collision, it probably depends. If some random person once was in possession of your current GitHub username and signed in at StackBlitz, we will have to fix it manually on our side. If you are in possession of both GitHub accounts, it's basically the same as solution 2 of the email collision flow. Sign in with Account A so the info gets updated on our side, then sign in with account B and it should work.

If your issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
