### ISSUE TITLE
Feature: private, unlisted and categories

### ISSUE THREAD

**Issue by fabiobiondi** [stackblitz/core#134]
Hi guys, 
it would be nice to have more features to organize our snippets:

- **Private** and/or **Unlisted** snippets
- Organize snippets in collections (or by using tags)
- Favorites
- Add an image preview to any snippet (automatically generated or by providing an image link)

Anyway, amazing work! I'm using it with React, Angular and Redux and it works like a charm

**Comment by EricSimons** [comment]
Thanks for the kind words @fabiobiondi, we really appreciate it! :)

When you say snippets, do you mean stackblitz projects? Or snippets [similar to VS Code's](https://code.visualstudio.com/docs/editor/userdefinedsnippets)?

**Comment by BamiGorengo** [comment]
Making Projects Private is really very important i think. I hope very much that this function is implemented soon.

**Comment by EricSimons** [comment]
@BamiGorengo @fabiobiondi totally agree about private projects — I'm curious to hear your use case for it (work, sideprojects, etc) and if it's a feature that you would pay money for?

**Comment by BamiGorengo** [comment]
I totaly understand that companies need to make money to survive, and that without existing the github team, we never get so great stuff like StackBlitz. But i think so extremely important stuff, "like making Projects private" must be free.

As Example: I switch last Month to gitlab because i cant make repository private. I was thinking some months about paying that 7$... Then i try and pay. After Payment i try to make a repository in one of my Organizations "Private"... And then came the lol-moment.... I payed for my Account and the Organization is not a part of my account. so i need to pay for every each organization :O 

I was before paying already close to switch to another git Provider, but after this i was sure thats its time to switch.

The Same is for me with StackBlitz. Its from Usability 10000 Times better than the alternatives.. But when i have Secret Projects, i am forced to use the Free Providers.

Its cool to take money for stuff they are can called as "nice to have" but the setting for making Projects private are more important then "nice to have stuff".

Sry my bad english, its horrible to read i know :D

**Comment by Misiu** [comment]
@BamiGorengo I must disagree.
Private projects is one of features I can pay for.
StackBlitz is awesome project, I can't imagine how many hours team spend on creating it.
They are adding new features, fixing bugs, paying for servers and best of all this is free for all of us (thank You guys for that).

If You are creating private projects then is quite possible it's prototype app You want to share with future customer, so eventually You'll make money out of using StackBlitz. I don't see any good reason why Yous should't share just a piece of money You got with creators.

If we want to have awesome tool like StackBlitz we must support creators, not just saying thanks. By supporting development all of us will benefit (bug fixes, new features, etc).

Personally I don't mind paying dolar or two for extra feature like private projects, but this is only my opinion, anyone can disagree, but keep in mind that team must live out of something. They probably have other (paid) projects, but if they could get profits out of StackBlitz they probably could focus more on project.

**Comment by BamiGorengo** [comment]
I for example, made yesterday a Stackblitz for StackOverflow, because i need help with a bug. Inside this StackBlitz is my real env file: https://stackblitz.com/edit/angular-7gabaq?file=sites/site-restaurant-detail/site-restaurant-detail.component.ts

now the whole world have access to my FireBase Project. That have nothing to do with Making Money and dont want to share some of this money to the StackBlitz Developers. Such small things simply make Stackblitz extremely unattractive. Yeah OFC StackBlitz is ultra Awesome! Its the best Online Editor i ever saw. Its close to a real full IDE. but not really useable for me. I cant demonstrate my problem without outputting Data. So i need a option to make some files "invisible/private" ore make the whole project private (only accessable with direkt URL wich is hidden everywhere else)

I think when stuff like that costs money, they loose alot costumers, costumers where are ready to pay for other extras.

But remember. What i write is only what i personaly think. Maybe i am wrong. But that is how i select wich product i use and wich one not. I don want to start a discussion about that. I accept it totaly when people think different.

**Comment by Misiu** [comment]
@BamiGorengo I misunderstood Your previous comment.
By private projects I understood project that can't be accessible by anyone without owner permission (they must have account or password).
I agree that there should be an option to disable editing/viewing config files (like in Your case) for anyone than owner (maybe folking such project should be disabled). This way it would be easier to create demos for StackOverflow.

So 👍 on Your feature request.

**Comment by BamiGorengo** [comment]
Yeah, its not so easy to understand my bad english :)

**Comment by brijmcq** [comment]
@EricSimons Here are my use cases for private projects.
 - An app w/ firebase configurations/credentials that I need to show to my team/clients. This is something that should not be public, though the temporary solution for now is to create a dummy account and its credentials.
 - I use gist for my code snippets, but then it is a lot better to use stackblitz to store your code snippets because you can edit and see the results right away.
I don't mind paying 1-2 dollars for this, if more, I would have to think twice and see if I can live without the private feature. Anyways, it is still an awesome site and continue using it!

**Comment by fabiobiondi** [comment]
@EricSimons : sorry for delay. 
Of course with "snippet" I meant "project. Sorry for the misunderstanding.
Why I need it? Because I'm already use this amazing tool for my React and Angular training course (creating project and exercise for students) and if you check my account you'll already see about an hundred of Angular, React, Typescript, Redux, Mobx, .. projects.

So, since this activity required a lot of works I would like to share a private (or an unlisted) collection just with a group of people to avoid that everybody can see everything.

An example of what I mean is the PRO account of CodePen. You can create public and private snippets and add them to custom collections. These collections can be public or private too and both can be shared just sending the collection url (so they are not really private but unlisted and people cannot see them when visit the user profile).

I would pay for this feature! :)

**Comment by kotpal** [comment]
What happened to this feature request? Is there any way to make StackBlitz projects to be private - in that the project can only be viewed and the underlying project structure and config files are not shown.

**Comment by mackelito** [comment]
Bump this up! :)
Having private Blitz would be awesome!

**Comment by daniel-gwilt-software** [comment]
I have no problem paying for a private StackBlitz.  Although, one of the reasons I have yet to get a Pro CodePen account is because it's "Private" pens are just "hidden" instead of actually securely private.  If you implement this feature it should be private, encrypted and have share links that are only usable by people with the correct account and/or be temporary "read-only" access for demo purposes.  That way I can use a private project for any code.  I would know, with confidence, that it's not only hidden but safe and secure as well.

**Comment by esnakker** [comment]
Hi, what a great piece of software! Tried c9 and codeanywhere, but stackblitz if my favorite for learning and testing react. Would absolutely going to pay for some extra features like private projects, that can't be edited by other people.

**Comment by jensschneider** [comment]
I think private projects are very important. In my opinion this is an advanced feature and users should pay for it. I whould...

I would love it if private github and private npm repository could be available.

**Comment by plaetzchen79** [comment]
This would be really great.

**Comment by BamiGorengo** [comment]
Marking some single Files as Private / Invisible = Free
Private Projects = Payed

**Comment by jasonericdavis** [comment]
I would be willing to pay for private files and more for money for private projects.

**Comment by jamlen** [comment]
From reading the suggestions here, I'd like to see something of a hybrid...

Selecting a project/snippet as 
* 'secret' which would be like a secret gist, not index and  - a free feature
* 'private' which is a properly private and secure project which the access can be managed/expired and allow my team to edit etc - a paid for feature

**Comment by ThunderRoid** [comment]
1 Free private project
More than 1 = PAID

**Comment by BamiGorengo** [comment]
@ThunderRoid Thats useless. We need for free the possibility to hide single files. Otherwhise its not possible to use stackblitz with apps they are using any API. It must be possible to hide / private some single config files they contain secret data.

**Comment by zkuzmic** [comment]
Private projects would be great and definitely worth paying for. I work for a company that isn't able to make code publicly available, so the current setup won't work for us unfortunately.

**Comment by Draccoz** [comment]
I am a professional developer, I code for living. Currently i am paying for GitHub and for CodePen monthly subscriptions, though am not fully happy with CodePen (it's really great for single pens, but not for projects). If StackBlitz offered private projects, I would be more than happy to pay for it (that is if the price is similar to GH/CP prices).
Developers worldwide make pretty good money for their skills. If you build something and want to keep it secret, that means its probably worth money and you will most likely get money out of it. That means you should not demand for stuff like that to be free, our profession has damn low costs anyway. Eventually as suggested by @ThunderRoid a 1 free private project (or more than 1) would be a good option.

**Comment by svstartuplab** [comment]
Stackblitz is awesome but I want to code my Angular app when I'm traveling on an iPad Pro.  While I have a Stackblitz available to the public to answer questions on Reddit and SO I want my main projects to be private.  I also want to connect to my AWS stack so I have the database, etc available anywhere with cell or wifi service.

When can we start paying for this?  :-)

Of course when you put a service like this out in the wild then users want more and more and ...

**Comment by kidandcat** [comment]
I would pay for private projects too, also, with an added plus that if Stackblitz reaches the time when I can do my full work flow (work on private repos, others than github + enterprise level security + multiple packagers (Parcel) + builds online). I could work in a Chromebook. I could even work in any computer with a browser.

I would pay a lot for that.

**Comment by jillella** [comment]
Me too I will pay for private projects.

**Comment by ErickXavier** [comment]
So @EricSimons, it's being a while this feature request is open, do you have an update for us?

**Comment by BamiGorengo** [comment]
@jillella Also nice. but also not possible to set env files hidden... :(

**Comment by appeality** [comment]
> @BamiGorengo @fabiobiondi totally agree about private projects — I'm curious to hear your use case for it (work, sideprojects, etc) and also whether it's a feature you'd pay money for?

I would pay for it. One use case is for internal documentation.

**Comment by baryla** [comment]
After Amazon bought Cloud9, we're exploring online IDEs for our client work. StackBlitz looks very promising however it 100% needs to have private repos/workspaces/projects for obvious reasons. It can paid. For those of you who want something like that - there's also [Coder.com](https://www.coder.com) however it is still in Alpha and they have temporarily disabled the collaboration feature because it caused some issues.

**Comment by awtmarriott** [comment]
Hurry up and develop this - your editor is one of the best for rapid prototyping (and deployment to firebase is sweeeet). There's a free revenue stream that's sat untapped for 18 months, don't let it be for much longer

**Comment by beeman** [comment]
Although not publicly announced yet, as of last week we support private projects and an option to sync to GitHub!

![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55027477-5dafb200-4fd3-11e9-8030-07f35c023bbf.gif)

**Comment by Draccoz** [comment]
That is fantastic! Thank you so much!

**Comment by baryla** [comment]
@beeman great news!

**Comment by fabiobiondi** [comment]
ohhh wow!! Awesome thank you so much @beeman !

**Comment by ErickXavier** [comment]
@beeman I love you guys. lol

**Comment by jahnreektor** [comment]
My lucky day -- private projects released within the same day of Googling for it.

**Comment by daniele-pecora** [comment]
Finally

**Comment by tdekoekkoek** [comment]
that's awesome!  Does that also include importing from a private Github repo?

**Comment by greenstevester** [comment]
@beeman - re: private projects, who can I chat to re pricing, setup, etc.

**Comment by ledeniz** [comment]
stackblitz.com/membership mentions "Unlimited Private projects" for paying members. How many private projects are granted for free users?

**Comment by mikegoodstadt** [comment]
Great work with repos :)
@fabiobiondi also mentioned > * Organize snippets in collections (or by using tags)
Any advances on adding project organization? (groups, tags, labels, categories etc)
Thanks!

**Comment by kievsash** [comment]
+1 for Collections for free plan

**Comment by mikegoodstadt** [comment]
The request for Grouping Projects by categories (aka folders, collections, tags, labels...) has been added to the [StackBlitz Discord #feature-voting channel](https://discord.com/channels/364486390102097930/365955135773474816) - please visit and up-vote!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
