### ISSUE TITLE
Web MIDI not allowed

### ISSUE THREAD

**Issue by ondras** [stackblitz/core#1355]
Trying to use Web MIDI (Chrome) results in:

```DOMException: Failed to execute 'requestMIDIAccess' on 'Navigator': Midi has been disabled in this document by Feature Policy.```

**Comment by sulco** [comment]
Hey @ondras! 
That may be the case if you are trying to run this kid of API inside the built-in Preview window.
Because it exists inside and iframe some of browser's apis are not available this way.

It should work if you open the preview in new window (you can either copy the URL or use the `Open in New Window (LIVE)` button.

Hope this helps!

**Comment by ondras** [comment]
> Because it exists inside and iframe some of browser's apis are not available this way.

So it is technically not possible to use this API from within the `<iframe>`? The error message suggests that it is a matter of Feature Policy configuration.
