### ISSUE TITLE
Node Js server

### ISSUE THREAD

**Issue by vinchauhan** [stackblitz/core#136]
It would be nice to allow to add custom scripts to npm to start a node js server ??

I am not sure if this is already implemented in the platform.

**Comment by EricSimons** [comment]
@vinchauhan excellent idea. This isn't something we've implemented yet but we're definitely looking into it. Hard part would be optimizing the cost, as we'd have to run this on a server (whereas stackblitz currently runs entirely within the context of your browser)

**Comment by Toxicable** [comment]
It would be awesome to see this from a SSR point of view.
Right now when people have issues with Angular Universal in they need to make a repository which we can download to investigate locally but it would save a huge amount of time if we could simply do it through StackBlitz

**Comment by EricSimons** [comment]
@Toxicable this is definitely something we'd like to add- I think we've figured out a way to mitigate the cost too :) We're in the R&D stage for this atm, but I think we could realistically have this shipped by Q1. Do you know of any exemplary universal codebases that we could test against?

**Comment by Toxicable** [comment]
@EricSimons That's good to hear, looking forward to it!
We have this repository here: https://github.com/angular/universal-starter specifically the CLI starter there

**Comment by Igmat** [comment]
@EricSimons are there any news on this topic? Don't get me wrong, but this feature is essential for me.

Your project is really great, and I'd like to use it for sharing small demos of my [pet project](https://github.com/Igmat/baset) - it's a testing tool.
I understand that you don't use real CLIs under the hood (https://github.com/stackblitz/core/issues/17#issuecomment-321366392) and working on something totally different, but there are a lot of projects (including mine) that will benefit from possibility to run some custom node scripts, because there are NO solution for this problem at market now (closest one is https://repl.it but seems like they won't build general solution, preferring to create workaround, like they did for `jest`)

Such functionality will also bring ability to use `stackblitz` for testing angular/react/whatever applications, which seems to be impossible now (correct me if I'm wrong).

If you're able to share some details/problems/implementation challenges with community, I, personally, will do my best (issues, bug reports, test cases, PRs) to help you develop this feature.

**Comment by Igmat** [comment]
In order to clarify previous comment, I just want to be able to open this kind of url (https://stackblitz.com/github/Igmat/baset/tree/master/tests/sample-project) and allow user to run `npm test` and `npm run accept` commands there and see console output.
[These samples](https://github.com/Igmat/baset/tree/master/tests) even don't require any dev-servers/hot-reloading/etc.

**Comment by nasiruddin-saiyed** [comment]
@EricSimons  Sir is there any update regarding Angular SSR ?

**Comment by gauravmahto** [comment]
> @Toxicable this is definitely something we'd like to add- I think we've figured out a way to mitigate the cost too :) We're in the R&D stage for this atm, but I think we could realistically have this shipped by Q1. Do you know of any exemplary universal codebases that we could test against?

Hi, any updates on this would be helpful.

**Comment by kc0tlh** [comment]
@vinchauhan, @Toxicable, @Igmat, and @gauravmahto:  This issue has been resolved both with the launch of WebContainers ([blog post here](https://blog.stackblitz.com/posts/introducing-webcontainers/)) and [our new VS Code editor](https://stackblitz.com/codeflow)!
