### ISSUE TITLE
Cannot import repo from github

### ISSUE THREAD

**Issue by charlesr1971** [stackblitz/core#1408]
https://stackblitz.com/github/charlesr1971/rxjs-chat

It is not very big in size and seems to be pretty simple, so I cannot see why it won't import?

```
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.
If you think this is a bug, please file an issue in our repo! 
```

**Comment by SamVerschueren** [comment]
Did you manage to fix this? I noticed you mentioning something like this in the other issue you made?

If so, feel free to let us know how you resolved it.

**Comment by kc0tlh** [comment]
@charlesr1971  this issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!


Simply add pr.new/](https://developer.stackblitz.com/codeflow/using-pr-new) in front of the repo name to import. For example: [https://pr.new/github.com/charlesr1971/rxjs-chat](https://pr.new/github.com/charlesr1971/rxjs-chat)

More info on opening Github repos in StackBlitz can be found [here in our docs](https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide).

Related issue: https://github.com/stackblitz/core/issues/2473
