### ISSUE TITLE
I get "The repository is missing a package.json file." error when I actually have it.

### ISSUE THREAD

**Issue by ceci96p** [stackblitz/core#1418]
So I am trying to display this project 
https://github.com/ceci96p/Web-Clock

 and  I am trying to have it displayed on 
https://stackblitz.com/github/ceci96p/Web-Clock

I do not know what I am doing wrong to get the " The repository is missing a package.json file." error when I actually have it on the first level of all my directories.

**Comment by kc0tlh** [comment]
@ceci96p This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! 

<img width="722" alt="image" src="https://github.com/stackblitz/core/assets/1532264/6c9cafe1-8175-4bcd-8b86-5e3392599762">

Simply add [pr.new/](https://developer.stackblitz.com/codeflow/using-pr-new) in front of the repo name to import. For example: [https://pr.new/github.com/ceci96p/Web-Clock](https://pr.new/github.com/ceci96p/Web-Clock)

More info on opening Github repos in StackBlitz can be found [here in our docs](https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide).

Related issue: https://github.com/stackblitz/core/issues/2473
