### ISSUE TITLE
[Enhancement] Remove/Garbage collect old DOM content (previous versions of your app)

### ISSUE THREAD

**Issue by mattblackdev** [stackblitz/core#146]
Using the react-dnd and react-dnd-html5-backend packages, I get this error after editing:

```Error: Cannot have two HTML5 backends at the same time.```

In general, it would be nice if stackblitz could garbage collect the old versions of the app in the browser during it's syncing process. However, in my case, it would be ideal, because as it is now the app throws an error and doesn't render until I do a hard refresh after every change.

**Comment by EricSimons** [comment]
@mattblackdev definitely, this is something we actually had enabled in the beginning but had to disable due to perf problems. We're still trying to figure out the right strategy here for auto-unmounting/cleanup for all frameworks but I'm hoping to get something in by next week.

In the meantime, StackBlitz projects can make use of the official System HMR API's to achieve fine grained control over this. In particular, you can write any cleanup code required for HMR's in an exported `__unload` function in any file. For example, here's the unmounting function for the default react project that you can see in action [here](https://stackblitz.com/edit/unmount-react): 

```
// System cleanup method for HMR's
export const __unload = () => {
  ReactDOM.unmountComponentAtNode(document.getElementById('root'))
}
```

**Comment by mattblackdev** [comment]
Hey @EricSimons. How are things going?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
