### ISSUE TITLE
cant clone

### ISSUE THREAD

**Issue by cieldon32** [stackblitz/core#1491]
https://stackblitz.com/github/cieldon32/huameow-react

**Comment by purplem1lk** [comment]
Hey @cieldon32! Are you able to access this locally? I tried these steps:

- Opened a JavaScript blank project
- Clicked on 'Connect Repository' on the top left
- Clicked on 'import from existing repository' and pasted https://github.com/cieldon32/huameow-react
- The screenshot outlines the import error I received

![Screen Shot 2021-07-29 at 10 22 44 AM](https://user-images.githubusercontent.com/49956513/127509106-16e3b77b-1ff1-4d38-92ce-245c9312cf72.png)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

Check it out for yourself here: https://pr.new/github.com/cieldon32/huameow-react

<img width="999" alt="image" src="https://github.com/stackblitz/core/assets/1532264/9db30a32-1766-4297-9cc1-2d35dce37b95">
