### ISSUE TITLE
Importing existing project

### ISSUE THREAD

**Issue by cskiwi** [stackblitz/core#1541]
### **Description of Bug**
When importing an existing project it automatically tries to import the `master` branch. But creating new projects, the default branch is now called `main`.

### **Steps to Reproduce**

1. Go to 'stackblitz.com'
2. Click on create new project > 'Node.js'
3. Click on 'Connect repository'
4. Click on 'import an existing repository'
5. Paste url of your GH repo (e.g. https://github.com/cskiwi/stackblitz-import-main)
6. See error:
![image](https://user-images.githubusercontent.com/847540/125584540-ee0ddd55-4987-4b63-9de2-d781256385fc.png)

### **Additional info**
This is also in the recommended new steps:
![image](https://user-images.githubusercontent.com/847540/125584070-50634e75-3086-4d70-938c-82c66e121d49.png)

**Comment by mrambow** [comment]
Same issue here..
wanted to add that it's not possible to switch branches, like switching to "main" because github doesn't use "master" anymore.

And method described in docs: https://developer.stackblitz.com/docs/platform/importing-projects/
`/github/{GH_USERNAME}/{REPO_NAME}/tree/{TAG|BRANCH|COMMIT}`
also not working, error is plain "not found"

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
