### ISSUE TITLE
my React github is not working in stackblitz - https://github.com/KartikSagar007/ReactMaterialUI

### ISSUE THREAD

**Issue by KartikSagar007** [stackblitz/core#1557]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Steps to Reproduce**
https://github.com/KartikSagar007/ReactMaterialUI
but when hit ulr on browser: https://stackblitz.com/@KartikSagar007/ReactMaterialUI
NOT WORKING

1. Go to 'https://stackblitz.com/@KartikSagar007/ReactMaterialUI'
4. See error as below:
Yikes! The page you requested couldn't be found.

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by purplem1lk** [comment]
Hey @KartikSagar007 - Thanks for your patience. You'll have to take out the '@' in the URL, but after I went to https://stackblitz.com/github/KartikSagar007/ReactMaterialUI and downloaded all the dependencies, I get the errors in the screenshot below.

Does this repo run locally for you?

![Screen Shot 2021-08-01 at 7 46 22 PM](https://user-images.githubusercontent.com/49956513/127788871-8bea641a-5438-4344-b513-df0194363c43.png)

**Comment by KartikSagar007** [comment]
Hi,

Thanks for your email.

No, I am not able to run it locally too. :(



Thanks and Regards,
*Sagar Bagga*
Direct Call: +65-91429131 (Singapore)
Direct / WhatsApp Call: +91-9818909125 (India)
https://www.linkedin.com/in/sagarbagga/




"save Water + save Paper(avoid unnecessary Printouts) = go Green  :) "

**Comment by purplem1lk** [comment]
@KartikSagar007 Since this project isn't running locally for you, I recommend working through the suggestions in the console to get the project up and running. If the project isn't running locally, unfortunately, it won't run in StackBlitz but you can certainly use StackBlitz to debug through the errors you're seeing.

This issue will be closed since this isn't a StackBlitz-related bug - For additional help, I recommend reaching out to the [React community](https://reactjs.org/community/support.html). We also have a [Discord community](https://discord.gg/8SAhUvkC) where you can ask questions. Thank you! :)
