### ISSUE TITLE
Something went wrong with this repository.

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/core#1562]
I am trying to import my repo -> https://github.com/deadcoder0904/mdx-bundler-images-error but this repo (only this one) keeps on throwing error.

![stackblitz-error](https://user-images.githubusercontent.com/16436270/126953739-3390e604-b1f4-4ffe-a5d2-1d57fbd06160.png)

Last time I tried it, it was reloading again & again so I hard-refreshed it but then it kept giving me the same error.

It works for other repos.

**Comment by satanTime** [comment]
Looks like you are facing the same issue as I do: https://github.com/stackblitz/core/issues/1561

Might you check if the repo has some fresh packages updates in its `package.json` and what happens if you roll back to a branch with has last updates 1-2 weeks ago?

**Comment by deadcoder0904** [comment]
> Might you check if the repo has some fresh packages updates in its `package.json` and what happens if you roll back to a branch with has last updates 1-2 weeks ago?

I don't have any branch. You can check the repo yourself as I don't understand what you are saying with fresh package updates. Just need to put in https://githubblitz.com/deadcoder0904/mdx-bundler-images-error in the URL

I have not updated deps at all I think :)

**Comment by patilshrikant77** [comment]
I did the same and getting same error

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

You can check it out for yourself here: https://pr.new/github.com/deadcoder0904/mdx-bundler-images-error

<img width="723" alt="image" src="https://github.com/stackblitz/core/assets/1532264/9d312166-7e7a-488d-8009-d529be729371">
