### ISSUE TITLE
Prettier formatting doesn't work on .vue files

### ISSUE THREAD

**Issue by ffxsam** [stackblitz/core#1570]
### **Description of Bug**
"Format Document" doesn't work in .vue files

### **Steps to Reproduce**

1. Create Vue project
2. Edit a .vue file (make it a little messy)
3. Click "Format Document"

### **Expected Behavior**
I would expect it to format at least the `<script>` block.

### **Screenshots/Screencast**

https://user-images.githubusercontent.com/12532733/127785411-6d2bcbaf-f123-4bfb-93a5-e3f738ce2a06.mp4

**Comment by maiertech** [comment]
Also does not work in `.svelte` files.

**Comment by fvsch** [comment]
Hi @ffxsam. Sorry for replying late. We've shipped Prettier support for `.vue` files last year (Sept 16 2021), so this should be fixed.

We haven’t fixed support for `.svelte` because the Prettier project does not provide built-in support for `.svelte` projects, and the Prettier plugins for Svelte require Node.js and don't run in a browser — last we checked.
