### ISSUE TITLE
Unable to clone my github public repo

### ISSUE THREAD

**Issue by npenin** [stackblitz/core#1593]
Hi team,

I am not able to clone my monorepo https://github.com/npenin/akala. I am just getting an error message, but I do not have detail about the actual error.

**Comment by geromegrignon** [comment]
Hey @npenin,

Can you add the steps to reproduce your issue and the error message?
It'll help maintainers.

**Comment by npenin** [comment]
Just opening this link https://stackblitz.com/github/npenin/akala is not working
![image](https://user-images.githubusercontent.com/1405160/133599662-49a9b93a-1af8-4f67-8dfd-d1e3ff2f95c8.png)

**Comment by geromegrignon** [comment]
Hey @npenin, I would suspect the architecture of your project to explain such an error: Stackblitz can't run the project as there is no dedicated script in the package.json file at the root level.

**Comment by npenin** [comment]
Why would I need one ? what are the requirements to clone a github project on stackblitz then ?

**Comment by geromegrignon** [comment]
I don't know if it's up to date but here are the related docs: https://developer.stackblitz.com/docs/platform/importing-projects#supported-project-types

**Comment by kc0tlh** [comment]
@npenin more updated docs on importing from Github [can be found here](https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide). 

These worked for me to get your repo imported, although I was not able to get it to run due to old dependency versions I believe.

_Related issue: #2473 _
