### ISSUE TITLE
Version mismatch for package in peers

### ISSUE THREAD

**Issue by ssuperczynski** [stackblitz/core#161]
Error:

```
Error in main.ts:
Unexpected value 'TableModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
Evaluating main.ts
Loading app (8:25)
```

See https://stackblitz.com/edit/angular-5gsg43?file=app%2Fapp.module.ts

1. I've added to dependencies `ngx-easy-table` 1.0.11
2. then add `import {TableModule} from 'ngx-easy-table';` to `app.module.ts`.

External module has angular `^4.0.0` so it should work with Stackblitz 4.3.6.
I've checked by including it to anther project and works fine.

This might be a known error https://github.com/angular/angular/issues/15763#issuecomment-291577486

Could you point me out if I've added it to Stackblitz correctly?

**Comment by EricSimons** [comment]
@ssuperczynski you're absolutely correct, there's a version mismatch issue 😓  We actually fixed this bug a while back but apparently there's an edge case in there somewhere! @apai4 is coming back on Monday and can put a fix in then, but until then if you bump all of your angular deps to latest (4.4.4) that fixes it. I forked your template and bumped the deps and it worked- here's the link! https://stackblitz.com/edit/angular-3zsuyt?file=main.ts

**Comment by ssuperczynski** [comment]
Thanks for quick answer. Works <3

**Comment by EricSimons** [comment]
@ssuperczynski wow, I actually just figured out the bug with this one: it's the package itself! Specifically, [the package.json](https://unpkg.com/ngx-easy-table@1.0.12/package.json) is listing @angular/core and other deps as _dependencies_ when instead they should be listing them as _peerDependencies_ to ensure they share the same version of Angular with the user's application. This bug is probably affecting some people developing locally on their machines as well 😮

That said, I think this can be mostly resolved by ensuring the dep resolver is incredibly aggressive at trying to find a common satisfying version for all deps. 👍

**Comment by ssuperczynski** [comment]
Just moved all the dependencies to devDependencies. Thank you for your help. This error occurred for some time and I didn't know what could be the reason for it. Now I can officially add demo to Stackblitz to my Readme ☀️ 🌴 🚀 

I guess we can close this issue.
