### ISSUE TITLE
Allow package.json inside subfolder

### ISSUE THREAD

**Issue by jwanner83** [stackblitz/core#1618]
I wanted to check out this random repository inside of stackblitz https://github.com/coder1389/Portfolio but after opening this url, the following message appears: 

The repository is missing a `package.json` file.

This is not true because there is actually a `package.json` file, but inside a subfolder and not in the root. I think it would be cool to allow opening projects which contain the code in subfolders.

**Comment by fvsch** [comment]
Hi @jwanner83. It's actually possible to import a subfolder of a repository — but only this subfolder — using our GitHub importer, with a URL like: https://stackblitz.com/github/coder1389/Portfolio/tree/main/src

In this case it fails to import because of invalid dependencies, probably because one of your dependencies is specified as:

```json
  "m-requester": "file:../../requester/dist",
```

and we don't support `file:` dependencies, plus this path goes into some folder on your computer that doesn't belong to this repository.
