### ISSUE TITLE
The dependencies for this project couldn't be resolved.

### ISSUE THREAD

**Issue by globalverified** [stackblitz/core#1621]
I want to upload my below-mentioned Github project to the Stackblitz platform for editing.

https://github.com/sagar-github-2021/react-testing

using https://stackblitz.com/github/sagar-github-2021/react-testing

Error : The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

How is it possible as I have uploaded this repository from my local MacBook Pro?

Please suggest.

**Comment by geromegrignon** [comment]
Hey @globalverified,

The issue comes from the git branch.
Stackblitz only supports default **master** branch at the moment.

As your default branch is main, it doesn't work (and as your master branch isn't the default one, it doesn't work too).

There might be some additional issues as by moving the default branch to 'master', the error message is still there.

The workaround is to create a node WebContainer and to import your repository (requiring the default branch to be **master**).
Here is a working WebContainer Stackblitz based on your repository: https://stackblitz.com/edit/node-zmwjwq?file=package.json

**Comment by globalverified** [comment]
Thanks. Closing this ticket.

**Comment by globalverified** [comment]
https://stackblitz.com/github/globalverified/react-testing
https://github.com/globalverified/react-testing

I have changed my branch to master as default and with updated code by pull request.

still unable to upload the project in Stackblitz.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!

<img width="721" alt="image" src="https://github.com/stackblitz/core/assets/1532264/70703ffb-f35a-4682-b8b0-8eee92a15cd8">

Simply add _[pr.new/](https://developer.stackblitz.com/codeflow/using-pr-new)_ in front of the repo name to import. For example: [pr.new/github.com/sagar-github-2021/react-testing](https://pr.new/github.com/sagar-github-2021/react-testing)

More info on opening Github repos in StackBlitz can be found [here in our docs](https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide).

_Related issue: #2473_
