### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#1628]

**Comment by geromegrignon** [comment]
Hey @reinkecarlos,

Can you provide further information about your issue? It'll provide insights to help you.

Here is a template you can use :

### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).


### **Steps to Reproduce**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


### **Expected Behavior**
A clear and concise description of what you expected to happen.


### **Screenshots/Screencast**
If applicable, add screenshots to help explain your problem.


**Additional Context/Questions**
Add any other context or questions regarding this bug.
