### ISSUE TITLE
Facing Issue while Importing my GitHub repo into stackblitz.

### ISSUE THREAD

**Issue by atulpatill** [stackblitz/core#1651]
When Importing this repo `https://stackblitz.com/github/atulpatill/SuperChat`, I got following error.

The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

I think this error is from your end so Please tell how to resolve this?

**Comment by pawellenart** [comment]
Same here.

Tried with two repos:
[pawellenart/lenart-in](https://github.com/pawellenart/lenart-in)
[pawellenart/revents](https://github.com/pawellenart/revents)

I'm sure they are OK, because they run fine locally and also deployed to Vercel.

**Comment by XsongyangX** [comment]
Similar problem here. The repo I have runs perfectly locally. But after importing, the repo says there are missing packages.

I tried checking the box for "Enable Ivy" and I get this new error message.
![image](https://user-images.githubusercontent.com/10444460/141723029-4afc2e43-dac8-4393-aa1e-594c956a20ac.png)

**Comment by markwhitfeld** [comment]
@XsongyangX Your issue is related to the Angular 13 issues. We are busy working on this.
See #1657 for updates.

As for the issues @pawellenart and @atulpatill are experiencing, I am not sure.

**Comment by XsongyangX** [comment]
@markwhitfeld thanks for the reply. I have tried using Vue and I suspect the error is that Stackblitz is seeking `master` branches but there is only a `main` branch. I tried to import an existing Vue repo into the project and it displays this error after I click the pull button.
![image](https://user-images.githubusercontent.com/10444460/144672687-717f45ca-460d-45f4-8c86-26e4b4434dda.png)

**Comment by markwhitfeld** [comment]
FYI, StackBlitz now supports Angular 13:
> Great news! Support for Angular 13 has finally rolled out.
...
For the next day or two (until 12 December 2021), there is a possibility of an initial slow down in starting up the dev server or running NGCC (or potentially even timeouts) as the packages repopulate into the cache as they are used, but it should come right after a refresh or two if you do have any issues. Anything else should be reported as a new issue.

Related StackBlitz issue comment: https://github.com/stackblitz/core/issues/1657#issuecomment-989779722

**Comment by markwhitfeld** [comment]
I'll ping the relevant people on the team about looking into this `master` vs `main` issue.

**Comment by ron2015schmitt** [comment]
Neither of my Angular 12 projects work, even though they work locally running `ng serve`

https://github.com/ron2015schmitt/ngx-mat-tui-calendar-quickstart

https://github.com/ron2015schmitt/ngx-mat-tui-calendar-demo

**Comment by markwhitfeld** [comment]
@atulpatill @pawellenart 
Your projects aren't quite in the right format for StackBlitz v1, but StackBlitz v2 will handle anything you throw at it!
Try adding the `?preset=node` query string to your imports. 
I have also added `terminal=start` so that it runs `npm start` too!

https://stackblitz.com/github/atulpatill/SuperChat?preset=node&terminal=start
and
https://stackblitz.com/github/pawellenart/lenart-in?preset=node&terminal=start
https://stackblitz.com/github/pawellenart/revents?preset=node&terminal=start

This should get you sorted out too @XsongyangX (with a slight tweak of the start command to `serve`):
https://stackblitz.com/github/XsongyangX/universalqc-vue?preset=node&terminal=serve

@ron2015schmitt it looks like you repos are importing ok now, but they may have some dependencies issue.

Closing this, because using WebContainer resolves the primary issue.

**Comment by ron2015schmitt** [comment]
Thank you!

**Comment by XsongyangX** [comment]
Wow thanks! You actually went into my profile to find the repo. 🥇

**Comment by nareshsmrk** [comment]
my project is taking long time to import from github to stackblitz i need to know the uploading status please help me
