### ISSUE TITLE
Any Github Support

### ISSUE THREAD

**Issue by michaellee8** [stackblitz/core#167]
If could be wonderful if we can perform github push and pull and even some command lines like we did generally. Currently without github support make this app just a enhanced jsfiddle, but with Github support it is full-fledged

**Comment by SindreSvendby** [comment]
Is there anyway I can help on this? This is the missing feature for us to try to use this in our workflow! 

If i created a POC repo where I connect to github, retrieve the files and put it into the monaco-editor would that help? I'm not sure on architecture you have, so please advice on what kind of module I can create that would help you implement this feature!

**Comment by maks** [comment]
There is a long and illustrious (ignominious?) [history of getting an in-browser git client working](http://maks.github.io/git-browser-melbjs-lightning-talk/) Note that talk was Mar 2014! 
The most promising thing since then that I am aware of is [libgit2 port to JS via emscripten](https://github.com/kripken/emscripten/issues/4902) BUT this can't work as Github for some reason continues to refuse to enable CORS, so you need to have a proxy to get this to work in browser.

**Comment by SindreSvendby** [comment]
@maks now you are talking about a general git solution ?

You can use the github API to do changes to a repo: https://developer.github.com/v3/repos/contents/

**Comment by maks** [comment]
@SindreSvendby yes actual git protocol. 
I do know about the GH API v3 but that is going to generate a *HUGE* amount of network requests for anything beyond a trivially small repo. Still that is about the only thing that will actually *work* atm.
I just don't understand GH's reluctance to enable CORS for git protocol https access.

**Comment by titombo** [comment]
Hi @SindreSvendby  and @maks did it worked for you? I am trying to achieve something similar like in here: https://stackoverflow.com/questions/51389437/send-and-get-data-from-code-editor-like-plunker-embedded

Could be on stackblitz as well instead of another tool, in this case instead of POST to our servers it would POST to github and our servers would download from there.

**Comment by kc0tlh** [comment]
@michaellee8, @SindreSvendby, @maks, and @titombo: this issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue #2473
