### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by kadiri2006** [stackblitz/core#1705]
cant imported from github repo

**Comment by geromegrignon** [comment]
Please provide a link to your GitHub repository

**Comment by kadiri2006** [comment]
https://github.com/kadiri2006/all-hooks

**Comment by KooiInc** [comment]
[See this snip](https://stackblitz.com/edit/js-kymb25?file=index.js)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

Try it out for yourself here: https://pr.new/github.com/kadiri2006/all-hooks

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/74699873-ccef-4245-bed5-657d46dda4b4">

_Note to our devs: still broken in Classic Editor_
