### ISSUE TITLE
Unable to disable strictTemplates in Angular app

### ISSUE THREAD

**Issue by platon-rov** [stackblitz/core#1710]
### **Description of Bug**

When i create new angular application using cli i can disable `strictTemplates` in `tsconfig` and the next example will work:

```js
/** comp-b */
@Input() prop: boolean;

...

<comp-b prop="false">
```

Unfortunately, i cannot do the same in the StackBlitz. Previously, i could disable Ivy to achieve such behavior but since Angular 13 i cannot do that.

### **Steps to Reproduce**

https://stackblitz.com/edit/angular-ivy-nbbdsj?file=tsconfig.json

### **Expected Behavior**

As `strictTemplates` disabled i should not see any errors.

### **Screenshots/Screencast**

![image](https://user-images.githubusercontent.com/20265336/149335431-e1a38c37-0ff9-4410-8961-ec8bcd95b178.png)

**Additional Context/Questions**

**Comment by markwhitfeld** [comment]
Stackblitz V1 does not support too much customisation of the Typescript Compiler because much of what is does is with its own custom pipeline. It uses reasonable defaults, which `strictTemplates` is definitely a part of.
So unfortunately, I don't think we will support turning this option off.

But, maybe more to the crux of your issue, `strictTemplates` is actually pointing out a valid issue in your Angular code.
Your code: `<comp-b prop="false">`
Should rather be: `<comp-b [prop]="false">`
In this way you will be binding the value of the property to the `false` boolean value.

**Comment by markwhitfeld** [comment]
PS. If you would really like to be able to have full control of this type of thing, then I would suggest using StackBlitz v2, that is, WebContainers ;-)
