### ISSUE TITLE
On mobile Safari, the page continually reloads 

### ISSUE THREAD

**Issue by charlesr1971** [stackblitz/core#1727]
### **Description of Bug**

On mobile Safari, the page continually reloads to try to start up the Dev Server. This makes it impossible to view or edit any code. 

### **Steps to Reproduce**

1. Go to  https://stackblitz.com/edit/github-aercse
2. Observe the Dev Server spinning up continually 
3. This is an Angular project. 
4. Gradually get more and more angry 🤬, as you realise that the software developers at StackBlitz have clearly not tested their updates on mobile Safari, as it is totally unusable. 

### **Expected Behavior**
The page should not continually reload 

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by SamVerschueren** [comment]
Software developer at StackBlitz here 🖐.

Opening it on my phone seems to work perfectly fine.

Do you have more info on your platform? Is it the latest iOS version and Safari version?

![image](https://user-images.githubusercontent.com/1913805/152426135-6b154579-4246-447c-b9db-abeeb28caabe.png)

Might've been a hiccup on our servers which caused this. Does it still happen for you?

**Comment by charlesr1971** [comment]
Hi 

I am using iPhone 8+ iOS 15.0.2

When the page loads, the dev server starts spinning up and then after about 10 seconds, the page reloads. And the cycle starts all over again. 

This has happened every time I have visited the website on my iPhone. So, this is not a one off. 

Thanks 

Charlie 



Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
Please look at it, in the editor and not the preview. 
It happens in the editor mode. 

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
I have just visited the page again and it has happening right now. 

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by EricSimons** [comment]
@charlesr1971 did you delete that project? I can’t seem to access it anymore.

Fwiw, It’s likely your project is large and your iPhone does not have sufficient memory to mount the whole env. If this is indeed a hardware limitation then there isn’t much we can do in this scenario unfortunately.

**Comment by charlesr1971** [comment]
https://stackblitz.com/edit/github-vwxcka

Please stay on the editor page for at least 5 minutes. And scroll to the bottom. You will see the dev server spinning up. 
At some point the page will reload and from that point, it keeps reloading every few minutes or so. 

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
This project is tiny. 

I am pretty sure it has nothing to do with memory. 

Thanks 

Charlie

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
I have an iPhone 8+ and it has plenty of HD space and memory. 

This project only has 2 components and a service. It is technical test that took a few hours to write. 
It is the smallest Angular project possible. 

It has nothing to do with memory issues. 🤷‍♀️

Thanks 

Charlie



Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by SamVerschueren** [comment]
If it was a memory issue, your own code would not be the culprit. All the node_modules are loaded in-memory for intellisense and what not. How big or small your app is, doesn't really matter (probably a bit though, because they add to the memory footprint), it's more the dependencies and everything going on under the hood. And it will also depend what else is running in the background of the phone.

I actually do believe it is a memory management issue. If you [Google](https://www.google.com/search?q=ios+safari+keeps+refreshing) it, everything points to "Safari is running low on RAM". I tried reproducing it on my iPhone, but it's an iPhone 12 so not really comparable. I might have an iPhone 8 lying around somewhere, I'll try to see if I can get it to boot and try to reproduce it.

Also tried an iPhone 8 Simulator through XCode and it works there as well. Fair enough, it's just a simulator and probably isn't too restricted in memory. And even if it was, it's not running anything in the background either.

I'm also not saying it might not be something else, just keeping open every possibility.

**Comment by charlesr1971** [comment]
The dependency footprint is tiny. 

See for yourself:

https://stackblitz.com/edit/github-vwxcka

This is a tiny app!

I did not install any third party modules, only the standard Angular framework.  

Thanks 

Charlie

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
I am an XCode Dev. 
The Simulator will not give you a fair representation. 

Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by charlesr1971** [comment]
I have tried testing a React app:

https://stackblitz.com/edit/use-memo-benchmark-class

And this problem does NOT occur. 

I mean I agree it is difficult to accommodate every type of browser & device, but mobile Safari is one of the most popular mobile browsers. And an iPhone 8, is not exactly prehistoric. I would have thought this combination would have been on your testing schedule?

Thanks 



Charles Robertson

Establish Mindfulness, Technical Director

E: ***@***.***
U: app.establishmindfulness.com
B: www.establishmindfulness.com
T: ***@***.***

**Comment by EricSimons** [comment]
We do indeed test our software on iPhones. Projects with large node_modules folders, like some Angular envs, can cause older mobile/RAM limited devices to run out of memory. In these cases there’s also no way for us to catch this crash before it happens because Safari does no expose any APIs to gather device info on memory available/used, etc unlike chrome and Firefox.

If you need to run angular toolchains on an iPhone 8 and are unable to access an iPad/chrome book/any other device with >2gb of ram, I’d recommend looking into cloud VM hosted IDEs like GitHub codespaces that allow you to pay for additional CPU/RAM/disk as needed.
