### ISSUE TITLE
Cannot find file: +stringify(n)+

### ISSUE THREAD

**Issue by jfsiii** [stackblitz/core#173]
The preview for both https://stackblitz.com/edit/react-cozcfx and https://stackblitz.com/edit/react-lpzpki/ is displaying `Cannot find file: +stringify(n)+`

I'm not sure where the issue lies. Let me know if I can help debug or if you see a change I should make.

**Comment by EricSimons** [comment]
@jfsiii woah, that's a weird error - never seen that before 😮 I'm gonna pull your project locally and see if I can repro; will report back within an hr or so with my results 👍

**Comment by jfsiii** [comment]
@EricSimons Thanks. I meant to mention that it works as expected when I download, unzip, and `yarn && yarn start` locally

**Comment by EricSimons** [comment]
Well, I found the issue — apparently `mapbox-gl` has require statements that are dynamically generated, which appears to be throwing off our tracing mechanism for deps :/ If you ctrl+f for `stringify(n)` you can see the offending line here: https://unpkg.com/mapbox-gl@0.38.0/dist/mapbox-gl.js

This is one of those problems that would be super easy to solve if we were doing this server side, but since dep installation is all being done on the client it's actually really hard 😅. I'm going to dig into this but it will likely take a few weeks; until then I'd recommend using glitch.com as they use an actual node server for running your application.

I'm so sorry about the inconvenience — I'll get this solved ASAP!

**Comment by jfsiii** [comment]
@EricSimons No worries. Thanks for stackblitz (it's terrific), looking into this, and offering an alternative. FWIW, things do work on glitch. See https://tall-border.glitch.me/

**Comment by Wykks** [comment]
Any update on this ? It's so sad to not being able to run mapbox-gl under the awesome stackblitz :cry:

**Comment by EricSimons** [comment]
We got this one fixed! There's some other work we'll need to around mapbox-gl though (allowing peer packages to access it's deps, which apparently many do) but that's more of a DX enhancement 👍 

Thanks for reporting this & lmk if you run into any other troubles

**Comment by Wykks** [comment]
This is amazing!!!!!
Thank you!!

https://stackblitz.com/edit/ngx-mapbox-gl
