### ISSUE TITLE
Cannot run public repo specifying a branch

### ISSUE THREAD

**Issue by Rolanddoda** [stackblitz/core#1745]
### **Description of Bug**
I have [this repo](https://github.com/Rolanddoda/svg-icons-interactive-playground/tree/lesson-3) and I am trying to open it on Stackblitz via: https://stackblitz.com/github/Rolanddoda/unified-way-of-using-svg-icons/tree/lesson-3 but it doesn't seem to work

### **Steps to Reproduce**

1. Just visit the link

### **Expected Behavior**
I read [here](https://developer.stackblitz.com/docs/platform/importing-projects/) that you can run any public repo and optionally specify a branch, tag, or commit. But it seems that this doesn't work.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/18482346/153876439-ac46f968-e087-4542-ad30-7bc7024c418e.png)

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

Try it out for yourself here: https://pr.new/github.com/Rolanddoda/svg-icons-interactive-playground/tree/lesson-3 

<img width="723" alt="image" src="https://github.com/stackblitz/core/assets/1532264/85547b47-a4c8-4a33-b198-ea98e5efeba2">

_Note to our dev team: still broken in the Classic Editor_
