### ISSUE TITLE
Cannot login after changing GitHub username

### ISSUE THREAD

**Issue by saksham-malhotra** [stackblitz/core#1755]
### **Description of Bug**
I am not able to login to my account after changing my user id on GitHub.

### **Steps to Reproduce**

1. Go to 'StackBlitz website'
2. Click on 'Login on top right of the page'
3. Authenticate via GitHub
    
![image](https://user-images.githubusercontent.com/62333433/155524363-6b19c8ef-7ec4-4538-9c20-cadb2ab87b40.png)

### **Expected Behavior**
Able to login.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/62333433/155524363-6b19c8ef-7ec4-4538-9c20-cadb2ab87b40.png)

**Comment by kc0tlh** [comment]
The issue here is that StackBlitz is seeing you attempt to login with the same email address, but a new username. This is causing a collision on our end. We will be revamping this flow in the future (@apai4 / @HeyGarrison tagging you both for awareness), but currently the workaround below should resolve your issue:

To resolve this you could add a +github added to the end of your email address in github, so it is unique in our database. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.

This issue was discussed last year in issue #1402 for additional context.

Hopefully this resolves the issue for you. If not, don't hesitate to reply and we'll have a closer look.
