### ISSUE TITLE
Local Project editing regression

### ISSUE THREAD

**Issue by rayfoss** [stackblitz/core#1761]
### **Description of Bug**
Local project editing seems to have been broken in the latest update.

By that I mean the feature that allowed you to open local folder and run it in web containers without putting it on the internet.
https://twitter.com/stackblitz/status/1395409496621584389

### **Screenshots/Screencast**
https://user-images.githubusercontent.com/876076/155830766-5cc54a97-b8bb-4a0c-9833-5fb8cc544d18.mp4

**Additional Context/Questions**
I switch between non-windows computers often and VSCode and the many different node configurations are too much to deal with. I also have sensitive secrets to smtp and databases in my local code that I can't risk uploading.

**Comment by fvsch** [comment]
Hi @rayfoss. Thanks for the issue!

Local project editing is an alpha feature that you should still be able to use from https://stackblitz.com/local

Last week we removed the "Local Projects (Alpha)" link from our dashboard menu because right now we don't have official plans to improve this alpha feature, and we didn't want to onboard new users to that feature. But we've heard from yourself and others that you're actively using it, so for now we've restored the menu link and will consider this in our future plans.

Hope this solves your problem.

**Comment by erguotou520** [comment]
Any progress on this issue?
The syncing between StackBlitz and local code is still broken now.
