### ISSUE TITLE
I can't log in to my account!

### ISSUE THREAD

**Issue by Yusipower** [stackblitz/core#1763]
I was injured logged in with another github account that I deleted and I don't have access to it

**Comment by terencecusi** [comment]
Same here, I used to have an old GitHub account which was deleted already. I created a new one with the same email address but StackBlitz keeps telling me to login to my already deleted account.

**Comment by kc0tlh** [comment]
This error will occur if you don't have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page:​ https://github.com/settings/emails

If the issue persists, it is likely you have **two GitHub accounts with the same email address and/or username**. If this is the case, simply change the email address and/or username on the new Github account that you would like to log into StackBlitz with.

Tip: **If you don't want to change your Github email address** you can instead update it to have a +github added to the end, so it is unique. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.

This issue was discussed last year in issue #1402 for additional context.

Hopefully this resolves the issue for you. If not, don't hesitate to reply and we'll have a closer look.
