### ISSUE TITLE
Error importing mui/material-ui/tree/master/examples/create-react-app

### ISSUE THREAD

**Issue by mherman22** [stackblitz/core#1767]
trying to access --> `muimaterial-uitreemasterexamplescreate-react-app` i get the error below
 ```
 The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

If you think this is a bug, please file an issue in our repo!
```

**Comment by geromegrignon** [comment]
Hi, please share a direct link to the Stackblitz project

**Comment by mherman22** [comment]
https://stackblitz.com/github/mui/material-ui/tree/master/examples/create-react-app

**Comment by fvsch** [comment]
It looks like this example folder was renamed. I’m finding this one that may be a match:
https://github.com/mui/material-ui/tree/master/examples/material-cra

In my tests it seems to import correctly in StackBlitz:
https://stackblitz.com/github/mui/material-ui/tree/master/examples/material-cra

So I’ll close this issue since things seem to work.
Feel free to open a new issue if something is still wrong.
