### ISSUE TITLE
[ENHANCMENT] SSH access to the workspace

### ISSUE THREAD

**Issue by DillonB07** [stackblitz/core#1770]
I love the idea behind StackBlitz. It's really useful for when I'm away from my computer and want to work on one of my GitHub projects. However, when I'm on my computer, I prefer my normal developer environment as it's customised in a way that suits me best. 

Would it be possible to add SSH access to the workspace so that it's possible to connect in VSC, Terminal, or an editor of the user's choice?

This would be really useful and increase my productivity by ten-fold. Currently, I won't be able to use StackBlitz as a proper part of my workflow until this is implemented.

**Comment by fvsch** [comment]
Hi @DillonB07. I’m tentatively marking this request as “rejected” because of the way that StackBlitz works: we are not running projects on servers, but directly in the browser:

- We run a custom OS layer in JavaScript and WebAssembly;
- We run Node APIs and scripts with the browser’s JavaScript runtime.

So there is no server to SSH into.

If you’re looking for a provider which provisions VMs or containers that you can SSH into, I think the fine folks at GitPod have that feature and a compute model that looks closer to what you’re looking for.

**Comment by ryuheechul** [comment]
I absolutely second this idea. Although there are currently "no servers", but since running NodeJS via WebContainers already broke the limit of what capabilities is possible compare to the past, could it be possible to still expose SSH (or something that allows to mount filesystem to localhost)?

**Comment by fvsch** [comment]
@ryuheechul We have a very alpha experiment for working with local files at https://stackblitz.com/local, but it's not a current focus.
