### ISSUE TITLE
URLs - namespace and retain canonical

### ISSUE THREAD

**Issue by drKnoxy** [stackblitz/core#178]
## URL name collisions
it is weird to have collisions with other users on urls when renaming, maybe the urls should be namespaced either with a prefix `https://githubusername-prettyurl.stackblitz.com` or an additional subdomain `https://githubusername.prettyurl.stackblitz.com`

## Canonical urls
I'll share the generated url `abc.stackblitz.com`, and the update the pretty url `cool-thing.stackblitz.com` and the generated url is lost, creating dead links.
It'd be nice if the generated one was canonical and always resolved.

**Comment by EricSimons** [comment]
I'm in favor of this 👍  We're actually thinking of switching over to a title based system which should make this easier as well (as your project title and URL can be updated independently of each other) - would love to hear your thoughts on that!

**Comment by anddam** [comment]
Is there any update on this?

I'd be in favor of URLs with a speaking path, e.g. `/<username>/<project-name>`.

&nbsp;

If the app URLs have to be retained I'd prefer the latter syntax with the user name as third level domain as it provides a more readable RDNN with user and project names, in that order.

&nbsp;

In order to not break current shared URLs you could match URLs that have only three components to project names alone, and let new URLs only be created with user name.

&nbsp;

#155 is related but the description is less verbose so I'm replying here.

**Comment by anddam** [comment]
Another, simpler, approach is to provide a setting option for prefixing `username` by default to to each new project. 

&nbsp;

If the option is checked then each new project will start with `<username>-<usual project default name>`.

If it is left unchecked the user experience is not altered at all.

&nbsp;

This has the advantage of being very straightforward to implement since it does not change the  current project naming and URLs.

**Comment by flcl42** [comment]
@anddam it may break on names with "-". "/" looks a bit better

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being added to our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
