### ISSUE TITLE
Option to turn off compiler.

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#187]
We'd like to create samples that use native ES6 modules, and require ES6 classes, but there doesn't seem to be a way to turn off the compiler.

**Comment by justinfagnani** [comment]
Any news here? We still have to load unnecessary polyfills in Chrome, Safari and now Firefox, because classes are always compiled out.

**Comment by EricSimons** [comment]
@justinfagnani yes! We're finally rolling out StackBlitz v2 next week which is going to allow us to do this, so turning off compilation in the current JS preset is something we can provide for y'all on day one. We'll also have our static assets dev server fully online by end of Sept as well which will allow for loading in your stackblitz JS files via regular script tags/etc (instead of index.js as exclusive entrypoint).

Would love to hear your thoughts on the above! I also can shoot you a link to our beta builds of the new v2 editor if you wanna try it out :)

**Comment by justinfagnani** [comment]
I would love to check it out!

**Comment by e-cloud** [comment]
@EricSimons could you point out where is that option to disable the compiler?

**Comment by EricSimons** [comment]
@e-cloud you can just this preset for no compiler: https://stackblitz.com/fork/web-platform

**Comment by lsrugo770** [comment]
> @e-cloud you can just this preset for no compiler: https://stackblitz.com/fork/web-platform

@EricSimons Is there a way to turn the compiler off for an existing project? I want to do navigation with links between multiple html files and it doesn't work in a compiled project. (If I try to delete the index.js file it throws an error)
