### ISSUE TITLE
Embedded stackblitz projects work only if they are open in another tab or window.

### ISSUE THREAD

**Issue by praveencodeeasy** [stackblitz/core#1885]
### **Description of Bug**
When I embed a stackblitz project(for example a static HTML/JS/CSS project), the preview pane works only if I keep the stackblitz project open in another tab or window. Otherwise, I get an error in the embedded project as "Error occurred: Error: ENOENT: No such file or directory., '/~'".

### **Steps to Reproduce**

1. Create a static HTML/JS/CSS project in stackblitz.com
2. Copy the embed url from the Embed tab.
3. Use the embed url in a iframe. For example, <iframe src="https://stackblitz.com/edit/angular?embed=1"></iframe>.
4. Run the HTML file containing the iframe in a browser.

### **Expected Behavior**
If the stackblitz project is already open in another tab or window, the loaded iframe looks like this:
![stackblitz error](https://user-images.githubusercontent.com/84696770/171001079-f88e11bb-611a-42ad-8740-a9776a2ec58a.JPG)

### **Screenshots/Screencast**
But if the project is not open in any tab or window, the iframe loads like this:
![stackblitzerror](https://user-images.githubusercontent.com/84696770/171001303-1cd452a9-613e-4591-a9fa-3328148bf6f6.JPG)

**Comment by praveencodeeasy** [comment]
By the way, I am embedding the stackblitz projects in my Angular project. So, if there is any additional configuration for Angular, please let me know.

**Comment by fvsch** [comment]
Hi @praveencodeeasy, thanks for the report. This should be fixed now.

I think this only affected projects using the “Static (HTML/JS/CSS)” starter template. Because of limitations with how this template is implemented, we had disabled running it in iframes, but that wasn't handled correctly and would result in errors like above in the preview.

We now allow running those projects in iframes. One limitation is that if you have multiple instances of the project running in different iframes on the same page, and/or on multiple tabs in the same browser, one instance can end up showing results from a different instance. This is because there is only one service worker per project (unless you fork the project of course), and the service worker returns the last known version of the file it has seen.

**Comment by praveencodeeasy** [comment]
@fvsch  Thank you very much. Anyways, I am not having multiple instances of the same project running in different iframes on the same page. So, everything will work fine.
