### ISSUE TITLE
Support for More File Extensions

### ISSUE THREAD

**Issue by boghyon** [stackblitz/core#195]
I was happy about the [VanillaJS support](https://github.com/stackblitz/core/issues/179#issuecomment-340114416). So I was about to play around with stackblitz but then I realized only a certain set of file extensions is supported. E.g. I can't create XML files which are typically used by [OpenUI5](https://github.com/SAP/openui5) application developers to define UI declaratively. Or is it possible to create a "freestyle" project where I can start fresh and use any file extension I want?

**Comment by fvsch** [comment]
Closing this issue because we have a couple options that should answer this need:

1. Create a project using the “Static HTML/CSS/JS” starter project. This serves project files directly using a Service Worker.
2. Create a project using our WebContainers runtime to run Node.js-based tools. For instance, using the Vite development server and bundler.
