### ISSUE TITLE
Fails importing an 'alfresco-js-api' library

### ISSUE THREAD

**Issue by DenisVuyka** [stackblitz/core#196]
We are experiencing an issue importing `alfresco-js-api` library into the project. It works with Angular CLI projects locally, but fails as soon as used with "stackblitz":

<img width="488" alt="screenshot 2017-12-06 18 19 18" src="https://user-images.githubusercontent.com/503991/33678049-98bbcbe6-dab2-11e7-861d-69645dab95b3.png">

Steps to reproduce:

- Create a new Angular 5 project with stackblitz
- In the `dependencies` input type `alfresco-js-api` and press Enter

**Comment by EricSimons** [comment]
@DenisVuyka I think this is due to an issue with the package's main/browser fields- will investigate further once I'm back in front of my comp next week!

**Comment by DenisVuyka** [comment]
@EricSimons I have deployed a new version that has different "main" value, but having the same result. You can try with `alfresco-js-api@2.2.0-37ae1528b50160408e0ec1e3f16c9f938a8e97c6`. And the [package.json](https://unpkg.com/alfresco-js-api@2.2.0-37ae1528b50160408e0ec1e3f16c9f938a8e97c6/package.json).

As I've mentioned, we have both versions working absolutely fine locally with Angular CLI, but not on the stackblitz.

**Comment by EricSimons** [comment]
@DenisVuyka hey! I just looked into this, and the problem is with your [dist build](https://unpkg.com/alfresco-js-api@2.1.0/dist/alfresco-js-api.js). Specifically, it includes require statements to file paths that don't exist within the dist/ folder.

If you were to remove the `browser` field from the package.json and not point at the dist build, I think it would actually work perfectly fine. If you want to create a UMD bundle however, perhaps looking into Rollup might be a good option? As Rollup strips out invalid require statements like the ones present in this webpack build

**Comment by DenisVuyka** [comment]
@EricSimons That makes a lot of sense, thanks for taking a look.

**Comment by DenisVuyka** [comment]
@EricSimons Just FYI, removing `browser` field helped, thanks again.
