### ISSUE TITLE
Push declined due to email privacy restrictions

### ISSUE THREAD

**Issue by FrederikWolter** [stackblitz/core#1963]
### **Description of Bug**
Trying to create/connect a new GitHub repository from a forked project in stackblitz creates `Push declined due to email privacy restrictions` error.

### **Steps to Reproduce**

Beeing locked in with an GitHub Account having `Block command line pushes that expose my email` and a freshly forked project open 

1. Click on 'Connect Repository'
2. Fill out repo name
3. Click 'create repo & push'

### **Expected Behavior**
New repo is created and contents of the projects are pushed.
If the `Block command line pushes that expose my email` is enabled in the connected GitHub account, the push should be done by the **@users.noreply.github.com** email address.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/35914049/183595652-c56e41a5-92b5-4304-a09b-a71c6b0cc3e4.png)

**Comment by tachibana-shin** [comment]
I met the same error.

This is a silly mistake but i don't understand why it hasn't been fixed

**Comment by robhowell** [comment]
I hit this issue too. It completely breaks the GitHub integration for me, which makes StackBlitz far less useful than it would be otherwise. Although I considered it, I'm not willing to lower my GitHub security settings just to allow use of this tool.

If it isn't straightforward to detect the setting when it is enabled on a GitHub account, another simple approach would be to just allow the user to manually specify/override the email address used for Git commits in a Settings panel.

**Comment by mjulstein** [comment]
Not sure of there being a reason not to use the @users.noreply.github.com email by default?
I don't understand what e-mail will be used instead?

**Comment by fvsch** [comment]
Hi @FrederikWolter and others.

Thanks for the bug report and many confirmations :)

We're shipping a fix for this issue today.

> Not sure of there being a reason not to use the @users.noreply.github.com email by default?

We try to match what people are doing locally, and when contributing to open-source. It's common to just use your public email address for your commits, rather than an anonymized one.

**Comment by fenarinarsa** [comment]
I just hit the same bug. I used Stackblitz as a naive new user to contribute to a project, it asked me to fork it, then to create a branch, then to commit my changes, and when I do a push I get this error message:

```
> git push origin fenarinarsa/patch-47199-french-fixes:fenarinarsa/patch-47199-french-fixes
To https://github.com/fenarinarsa/elk
 ! [remote rejected] fenarinarsa/patch-47199-french-fixes -> fenarinarsa/patch-47199-french-fixes (push declined due to email privacy restrictions)
error: failed to push some refs to 'https://github.com/fenarinarsa/elk'
```

**Comment by FireMasterK** [comment]
> We're shipping a fix for this issue today.

Hi, I'm facing this issue still, have there been any updates since then that break this?

**Comment by T3sT3ro** [comment]
If `git config user.email` worked at least it could be acceptable, but it essentially makes this tool lose all it's benefits over using for example vscode.dev...

Was issue closed due to... WAI?

**Comment by samdenty** [comment]
> git config user.email

I’ll add support for this, and ping the team to try to fix the underlying issue

**Comment by dfernandez79** [comment]
@fvsch This issue should be re-opened. You mention, "It's common to just use your public email address for your commits, rather than an anonymized one." 
However, without stats, it is impossible to tell what is common. Even if that's true, GitHub encourages you to use an anonymized email. 
I've had a GitHub account for a long time, and one of the security recommendations that the platform shows occasionally encouraged me to set the option "Keep my email address private."

As @T3sT3ro  mentions, using `git config user.email` in a terminal works (btw kudos for that, it's amazing how SB reproduces a full env in the browser!). But that setting isn't used from the IDE. My workaround was to do the commit operation from the terminal (it doesn't change my workflow, as that is what I do when working locally). However, it may be a low-hanging fruit that improves the StackBlitz user experience.
