### ISSUE TITLE
IDE cannot install any other extensions

### ISSUE THREAD

**Issue by ZionCm** [stackblitz/core#1984]
The ide that stackblitz provided has a really bad experience when using vue RFC because there is no volar to install and there are no code hints.
I really hate this so that I have to stop using stackblitz and start to use Gitpod even though I really love the new technology that stackblitz is performing.
And why doesn't Stackblitz provide a vue with typescript?

**Comment by ZionCm** [comment]
Actually I really love stackblitz but I am just unable to work in the ide of stackblitz.

**Comment by fvsch** [comment]
Hi @ZionCm,

> when using vue RFC

Did you mean Vue SFCs (single file components), not Vue RFC (request for comment), maybe?

> And why doesn't Stackblitz provide a vue with typescript?

Time and priorities :)

I can't comment on our roadmap right now, but this (and in general support for VS Code extensions, see #3) is definitely something that we are interested in supporting.

For now I’ll close this issue as a duplicate since it's a similar feature request as #3.
