### ISSUE TITLE
Cant find package.json 

### ISSUE THREAD

**Issue by yusupaara** [stackblitz/core#2088]
package.json exist inside folder, do I need to move it into outside?

**Comment by fvsch** [comment]
Hi @yusupaara.

Is this when [importing a project from GitHub](https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github)?

We need a `package.json` at the root of the project. If your `package.json` file is in a subfolder in your repository, depending on how your repository is structured, you might be able to move it to the root. Or alternatively, you could import that specific subfolder only, instead of the whole repository.

To import a subfolder, you can use this syntax:

```
https://stackblitz.com/fork/github/{user}/{repo}/tree/{branch}/{subfolder}
```

For instance, to import a specific example folder (for example: `packages/create-vite/template-react`) from the Vite project, we use:


```
https://stackblitz.com/fork/github/vitejs/vite/tree/main/packages/create-vite/template-react
```

**Comment by yusupaara** [comment]
Thanks alot, its work well.
