### ISSUE TITLE
Add forceEmbedLayout option in the document

### ISSUE THREAD

**Issue by segamiken** [stackblitz/core#2137]
### **Is your feature request related to a problem? Please describe.**
The `forceEmbedLayout` option is a bit confusing because the [SDK Options Reference](https://developer.stackblitz.com/platform/api/javascript-sdk-options) does not explain the `forceEmbedLayout` option which is defined [here](https://github.com/stackblitz/core/blob/d3581865d638611946d590a0c58f0c6e6b2e3e61/sdk/src/interfaces.ts#L122).

### **Describe the solution you'd like**
I know that `forceEmbedLayout` option is listed as `@deprecated May be removed in a future release.` in JSDoc, but it still does exist as a function, so I think it would be better to give an explanation about `forceEmbedLayout` option  in the document.

~### **Describe alternatives you've considered**~

~### **Additional context**~
Add any context or screenshots about the feature request here.

**Comment by fvsch** [comment]
Thanks for the report @segamiken.

@sylwiavargas Do you think it would make sense to document this option?

We have two deprecated properties in our SDK, the `project.tags` property and the `options.forceEmbedLayout` property. Both were kept in our TypeScript interfaces because removing them would break the code of users who use TypeScript (when they upgrade the SDK), and we changed how we handle those properties in semver-minor releases.

That being said, `project.tags` is now fully ignored (and wasn't actually useful before) so I’m okay with not documenting it, but `options.forceEmbedLayout` is still applied if provided by users. So documenting `options.forceEmbedLayout` might make sense.

**Comment by fvsch** [comment]
Made a PR for the docs in case we want to go ahead with it.

**Comment by segamiken** [comment]
Thank you!!
