### ISSUE TITLE
Stackblitz is not running

### ISSUE THREAD

**Issue by JohannCox** [stackblitz/core#2184]
https://github.com/IdanCo/angular-print-service

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

Try it out for yourself here: https://pr.new/github.com/IdanCo/angular-print-service

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/915b0b72-910b-4195-a1d7-3926535da41b">

**Comment by kc0tlh** [comment]
Also working in the Classic Editor here: https://stackblitz.com/github/IdanCo/angular-print-service?file=README.md
