### ISSUE TITLE
My website won't load.

### ISSUE THREAD

**Issue by ChickenG1ttr** [stackblitz/core#2218]
My website [cgw.stackblitz.io] will not work and says {"syscall":"","errno":2,"code":"ENOENT","path":"/var"} unless I open it directly from the editor.

**Comment by apai4** [comment]
Thanks for reporting this @ChickenG1ttr. It looks like this is because the project you have is based off of our Static HTML/JS/CSS starter project which doesn't support viewing the site standalone without the editor. We will work on improving the error message here. As a workaround, if you base your project off of the [Vanilla JS](https://stackblitz.com/edit/js) starter project instead, the website will work without an editor: https://stackblitz.com/edit/cgw-js https://cgw-js.stackblitz.io

**Comment by kc0tlh** [comment]
Closing this as a duplicate of #1427
