### ISSUE TITLE
Respect File Permissions when connecting to GitHub Repo

### ISSUE THREAD

**Issue by leoj3n** [stackblitz/core#2226]
### **Description of Bug**

Even though the `packages/start/bin.cjs` in [this repo](https://github.com/solidjs/solid-start) has executable permissions, those permissions for whatever reason do not translate to Stackblitz when "connecting" to the GitHub repo...

Please see a full bug report here: https://github.com/solidjs/solid-start/issues/550

### **Steps to Reproduce**

1. Create new Node.js project
2. Connect https://github.com/solidjs/solid-start
3. Refresh browser
4. Let `pnpm install` complete
5. Run `pnpm run docs:dev`
6. See error.

### **Expected Behavior**

File permissions on Stackblitz to match the executable bit committed to the GitHub repo.

**Additional Context/Questions**

Does Stackblitz not currently respect committed executable file permission for a reason?

Can the Stackblitz repo clone functionality be implemented in such a way as to respect executable file permissions?

**Comment by fvsch** [comment]
Hi,

I think we can simplify the steps to reproduce by using our main GitHub importer:

1. Go to https://stackblitz.com/github/solidjs/solid-start
2. Let `pnpm install` complete
3. Run `pnpm run docs:dev`

Beyond that:

It's currently a limitation of the classic StackBlitz editor that project files (including all files from an imported repository) always have `644` permissions, and cannot be executable.

The WebContainers runtime itself does support executable Node scripts, but when the project files get imported into the WebContainers filesystem they will have `644` permissions and won’t be executable, regardless of file permissions in Git (unless you run a Node script to alter permissions).

I’m also not sure we’re going to fix this issue, because it would require significant architectural changes. Depends on how many projects are affected, but so far it looks like it’s been an uncommon issue. We would definitely like to hear more from other projects and use cases that might be affected, to help us prioritize.

The good news is that we recently launched the beta of [StackBlitz Codeflow](https://stackblitz.com/codeflow), which pairs WebContainers with a new and more faithful Git implementation (and a full VS Code IDE). And Codeflow doesn't have this issue.

In my tests, this kinda worked in Chrome (though it was fairly slow, possibly because of this V8-on-Apple-Silicon bug):

1. Go to https://stackblitz.com/~/github.com/solidjs/solid-start
2. Let `pnpm install` complete
3. Run `pnpm run docs:dev`
4. When shown a prompt to open the local server, choose to open in a new tab rather than in the Simple Browser preview (which seems broken for this specific project)
5. Wait up to a minute (only if on Chrome + Apple Silicon?)

**Comment by leoj3n** [comment]
@fvsch It can take quite a while for the docs to begin getting served; something I've noticed locally as well, so you may have to let it sit for a while after running pnpm run docs:dev. Not sure if it has to do with macOS necessarily although that is what I am using on an older 2013 machine.

Using `pnpm`, I can verify the `postinstall` script consistently runs when added to `package.json`.

The file that needs to be modified exists prior to `pnpm install` but post StackBlitz clone...

So, I'm wondering if the StackBlitz [project configuration](https://developer.stackblitz.com/platform/webcontainers/project-config) would be sufficient to run a `chmod` only for StackBlitz, something like:

```json
{
  "name": "lib-example",
  "version": "1.0.0",
  "license": "MIT",
  /// ...
  "stackblitz": {
    "startCommand": "chmod +x ./packages/start/bin.cjs && pnpm run docs:dev"
  }
}
```

Won't have a chance to try this until later.
