### ISSUE TITLE
import a vuejs project from github repo

### ISSUE THREAD

**Issue by scenaristeur** [stackblitz/core#2232]
Hi, i'm not able to import one of my vuejs project  https://github.com/scenaristeur/browser-vue.git

- stackblitz want to import @components 
- i think it is a confusion with 'import UploadFiles from "@/components/UploadFiles.vue";' like in https://github.com/scenaristeur/browser-vue/blob/master/src/views/FileBrowser.vue, . the '@' is an alias for 'src' like mentionned here https://stackoverflow.com/questions/55309945/vue-cli-3-project-alias-src-to-or-not-working
![Screenshot 2022-12-27 at 10-52-17 browser-vue - StackBlitz](https://user-images.githubusercontent.com/4020744/209648958-70b57400-06a8-4fb7-b188-cf21dc484a09.png)

next stackblitz can not find a good node-fetch version 

![Screenshot 2022-12-27 at 10-52-28 browser-vue - StackBlitz](https://user-images.githubusercontent.com/4020744/209649030-74c895bb-bae2-4f82-98d9-781931a68e54.png)

should i modify my project to be compatible with stackblitz ? 

project is working on gh-pages https://scenaristeur.github.io/browser-vue/

**Comment by kc0tlh** [comment]
This issue is resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!

Simply put pr.new/ in front of the github repo URL to import into the new StackBlitz editor, then run your start command. For example: [pr.new/github.com/scenaristeur/browser-vue](pr.new/github.com/scenaristeur/browser-vue). More info [in our docs here](https://developer.stackblitz.com/codeflow/using-pr-new). 

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/7e90f2bb-4f77-40e9-bd30-446985f79827">
