### ISSUE TITLE
Preview panel blank...

### ISSUE THREAD

**Issue by pawanvora2017** [stackblitz/core#2238]
I am just trying out a a static project (using Chrome), but my Preview pane is blank! I see "X" icon, but not a reload icon... so I guess it's not able to load... but no idea what's going on.

**Comment by fvsch** [comment]
Hi @pawanvora2017 and thanks for the report.

Do you have a link to a specific StackBlitz project which shows this issue?

And do you have specific browser settings that could be blocking [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)? In particular, the “Block Third Party Cookies” feature of Chrome will also prevent StackBlitz from using Service Workers to power preview windows, which can result in what you're seeing.

One possible workaround is to add exceptions for StackBlitz domains, as described here:
https://developer.stackblitz.com/platform/webcontainers/browser-config#allowing-all-stackblitz-projects

**Comment by CoderLittleChen** [comment]
Hi @fvsch ,I got same problem. I just created react and angular app,Both of their preview panel is blank.
Project Url:https://stackblitz.com/edit/react-ts-eapz6t?file=App.tsx
Platform:Win 11
Brower:Edge

**Comment by pawanvora2017** [comment]
This is what I see… using Chrome on Mac.


￼

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information at this time:

- @pawanvora2017 did not share a URL to a project we could test, and I think an attempt to share a screenshot by email failed?
- The project shared by @CoderLittleChen doesn't exist anymore.

If you are still running into this issue, feel free to create a new issue with detailed information such as:

1. URL of a project showing the issue;
2. Screenshot(s), if relevant;
3. The steps you followed to create the project or run into the issue, if relevant.
