### ISSUE TITLE
There are always warning messages in the console

### ISSUE THREAD

**Issue by BonjourYY** [stackblitz/core#2252]
### **Description of Bug**
When I open the preview window, wait for a while, an error message appears in the console. 
The content is "The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."

### **Steps to Reproduce**

1. Go to "https://stackblitz.com/edit/js-sj491z?file=index.js"
2. Click on 'Open in New Tab'
3. Open 'Console'

### **Expected Behavior**
I don't want it to appear as it will interfere with my debugging the code.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/42639257/211699921-2c85f0b1-20d1-4738-b159-310ad911c02f.png)

**Comment by KooiInc** [comment]
If you click' open in new tab' and in the developer console settings check 'Selected context only' the warnings are gone afaik (well, at least in chrome)

**Comment by BonjourYY** [comment]
Ok, Thank you！

**Comment by fvsch** [comment]
Hi @BonjourYY and @KooiInc.

Sadly we can't do much about those warnings from Chrome. In our tests, preloading important scripts is a performance win for most users, but in some cases the code from preloaded scripts actually runs a bit late (because there's so much work to do before that to mount a fully working editor), so Chrome sees is as a possibly failed optimization.

Ideally we'd love if Chrome logged these warnings in the Issues panel and not in the Console, because these warnings are disruptive for StackBlitz users and often for StackBlitz developers as well, and there's no way to tell Chrome "yeah I know, thanks for the tip, now don't show it again please" :P

We have similar issues with other warnings logged by Chrome / Chrome DevTools, see for instance:
https://github.com/MicrosoftEdge/DevTools/issues/78

IMHO browser interventionism in our consoles has gone too far :shakes-fist-at-sky:, and all those warnings should be in a different panel (like the Issues panel), or if they stay in the Console they should be a new category of content that can be filtered out.
