### ISSUE TITLE
Compiling application and starting dev server taking so much time 

### ISSUE THREAD

**Issue by sridhark158** [stackblitz/core#2268]
initially i created project with 13.2.0 it suggested to upgrade so i updated all packages to update after updating 
Compiling application and starting server taking so much time 

link : https://stackblitz.com/edit/epicor-table-task?file=src%2Fapp%2Fapp.component.ts

**Comment by markwhitfeld** [comment]
The issue that was blocking you is most likely described in issue #2253
The fix was released on Monday and there has been no recurrence.

The other errors that you receive after the upgrade is actual project code that needs to be updated for the new versions of the libraries. This will require your efforts to resolve, just like any other upgrade.
The issue that was preventing you from debugging your project should be resolved now. Therefore I am closing this issue.
