### ISSUE TITLE
Google chrome kept trying to print the page

### ISSUE THREAD

**Issue by arealuser** [stackblitz/core#2346]
Tried stackblitz for the first time.
Whenever I type something into the python terminal, I get a print popup like this:
![image](https://user-images.githubusercontent.com/34215440/219879662-a9540b01-2e00-45f4-b5b7-6d61f159b77d.png)
Doesn't matter what I type, and neither CTRL nor P are pressed.

Bug occurred on: Windows 10, Google Chrome version 109.0.5414.122

**Comment by fvsch** [comment]
Hi @arealuser,

At this time, StackBlitz only runs JavaScript and WASM-based projects, and cannot run Python (unless the project includes a WASM interpreter for Python).

It looks like this “python” project you're trying to fork and work with was created by one of our users, who changed the project’s URL to say `python`, but it’s still not a Python project. It’s a TypeScript project containing the following code: `print()`.

This code will be transpiled to JavaScript (without a change in this case, because TypeScript is a superset of JavaScript and this file doesn't use TypeScript features). Then this gets executed on page load in the context of the preview iframe at the right side of the editor.

In JavaScript, calling `print()` will look for a `print` variable in the current lexical scope, then looking up in parent and ancestor lexical scopes, all the way to the global scope. So here, it will end up calling `window.print()`, which is a native function in web browsers and triggers showing the browser's Print dialog:

https://developer.mozilla.org/en-US/docs/Web/API/Window/print

To avoid this problem, you can fork this project, and in your fork you can edit the `index.ts` file to remove or comment out the `print()` line.

Note that this will just give you a simple TypeScript project with no content. If that's what you're looking for, I recommend starting from our official TypeScript starter project listed on https://stackblitz.com instead.

If you’re trying to run Python code on StackBlitz, that's not currently possible. I don’t think there's a good way to run Python in the browser without talking to a remote server virtual machine currently. The Pyodide  project needs a 300MB folder of JavaScript and WASM, which cannot be added to a StackBlitz project at this time (we have a 10MB size limit for project sources).

If you're learning Python, I would recommend finding a sandbox editor or REPL that runs Python code in a virtual machine on a remote server.
