### ISSUE TITLE
WebContainers should run in Safari 16.4 Beta

### ISSUE THREAD

**Issue by nickmccurdy** [stackblitz/core#2347]
### **Description of Bug**

Attempting to run a WebContainer in Safari 16.4 Beta fails with an error, even though [StackBlitz depends on  `RegExp` lookbehind assertions and `Array.fromAsync`](https://developer.stackblitz.com/platform/webcontainers/browser-support) which are [already supported](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes).

### **Steps to Reproduce**

1. Install Safari 16.4 Beta. If you're on iOS, backup your device and [enroll in the beta program](https://beta.apple.com/sp/betaprogram/).
2. [Use the Node.js template.](https://stackblitz.com/fork/node)
3. Run the file (`node .` in the Terminal panel on desktop or open Preview panel on mobile).
4. Note the error:
> Incompatible Web Browser

### **Expected Behavior**

> Hello Node.js v16.14.2!

(same output as Chromium)

### **Screenshots/Screencast**

![Screenshot](https://user-images.githubusercontent.com/927220/219955539-e87c6d18-4567-4cc0-b4d5-874caf8404a7.png)

(taken on iOS 16.4 (20E5212f)

**Additional Context/Questions**

CodeSandbox containers already supports Safari, so this would make StackBlitz more competitive.

**Comment by fvsch** [comment]
Hi @nickmccurdy.

Our team hasn't had time to fully test Safari 16.4 beta yet, but WebContainers are known to run in Safari Technology Preview 163 indeed.

Currently, because of limitations in how feature detection works in web browsers (i.e. it doesn't actually work for a number of advanced features, you have to try to run your code and pray ^^), we have to do some UA sniffing to show a meaningful warning to Safari users. We're going to revisit that soon!

You can bypass this UA detection by running this code in your console on stackblitz.com:

```js
localStorage.webcontainer_any_ua = "1"
```

Then reload the page. Here’s a basic Node.js project running the `serve` package on Safari TP 163:

![Screenshot 2023-02-19 at 16 19 09](https://user-images.githubusercontent.com/243601/219957573-c72a764b-1493-493a-9389-bcd78e4c365a.png)

**Comment by nickmccurdy** [comment]
Thanks for the info! This is working on my Mac, but I can't figure out how to open the console on my iPhone.

**Comment by fvsch** [comment]
Hi @nickmccurdy,

We announced official (beta) support for Safari 16.4 on macOS and iOS this week:
https://blog.stackblitz.com/posts/webcontainers-are-now-supported-on-safari/

We've made a number of changes since February, so please test again and create new issues if you're having specific troubles.
