### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by marques-kevin** [stackblitz/core#236]
Hi ! 

I lost my connection twice and I did have to rewrite all my code. I think, it would be great to have an auto save option to fix this problem :-)

PS: Your platform is awesome, GG !

**Comment by darrenmothersele** [comment]
+1 

This is an awesome project with huge potential. 

But it does need an auto-save feature (or some way to recover your work). 

I just accidentally create an infinite loop in my code while editing. This crashed the tab. The tab because unresponsive and I had to kill it. When I came back I'd lost the last 30+ mins work.

In case you're wondering how I did that. I was creating an ngrx Effects class. I added an empty effect. I was in the process of adding a map() call, but the code refreshed before I had chance. I hadn't marked the Effect as non-dispatching, I ended up with an effect that dispatched the same action repeatedly.

**Comment by darrenmothersele** [comment]
Just realised that if I should have been running the app in a separate tab/window. Then crashing the tab with the app running in it wouldn't have caused me to lose work.

**Comment by Stephenp1394** [comment]
Was autosave ever implemented? I just signed up for this platform and it looks like it still does not have autosave?

**Comment by manoharreddyporeddy** [comment]
From here https://code.visualstudio.com/docs/getstarted/settings

Tried below 3 options under `Settings > User settings`, but din't work:

	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 1000,

	"files.autoSave": "onFocusChange",

	"files.autoSave": "onWindowChange",

If `afterDelay` with 1000 is too heavy because deployment happens while typing
then either of `onWindowChange/onFocusChange` can be implemented, also technically feasible as `onfocusout` can be implemented
https://www.w3schools.com/jsref/event_onfocusout.asp.

If data loss then try alternatives - https://www.slant.co/options/22488/alternatives/~stackblitz-alternatives

**Comment by Stephenp1394** [comment]
@manoharreddyporeddy thank you

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by Akash187** [comment]
Hello, @purplem1lk I could not find the autosave feature. Can you let me know where to look?

**Comment by shakib04** [comment]
@purplem1lk how to enable auto save

**Comment by bsridatta** [comment]
@purplem1lk Please point to where we can find more info, thanks!

**Comment by perrin73** [comment]
Autosave please

**Comment by euhansarkar** [comment]
please  add  autosave function on stackBlitz

**Comment by RockYou-cmd** [comment]
@purplem1lk 
Reminder : there is still no autosave in the platform !

**Comment by hungchip** [comment]
So we still don't have autosave in this platform ???

**Comment by denivladislav** [comment]
Still no autosave
