### ISSUE TITLE
missing way to generate component and I couldn't type in the name e.g. for class

### ISSUE THREAD

**Issue by willi84** [stackblitz/core#2441]
![image](https://user-images.githubusercontent.com/6207308/227559591-9198ac20-584b-42d2-a8ea-d33636c5a15a.png)

when not found component, I used class, but then the overlay don't let me type in name

![image](https://user-images.githubusercontent.com/6207308/227560009-9388d4ca-d337-4966-bf69-c5e9a973fde0.png)

windows 10, chrome ersion 111.0.5563.110

**Comment by fvsch** [comment]
For the first screenshot: it looks like StackBlitz is too zoomed in for there to be enough space to show the full menu with the "Component" option (it's just above "Service"). Zooming out a bit might help.

For the second issue: definitely a bug we should fix. Workaround for now: because this bug only happens when using the mobile layout, with the sidebar in sliding drawer, zooming out to use the desktop layout should work.

**Comment by willi84** [comment]
yes i noticed now it was just out of the screen. but anyway: maybe you can adapt the flyout to the screen as an idea?
