### ISSUE TITLE
Webcontainer: ENOENT: No such file or directory., '/~/src/main.ts'

### ISSUE THREAD

**Issue by john-fenton** [stackblitz/core#2455]
### **Description of Bug**
In an Angular project, renaming the root folder from `src` results in the webcontainer not being able to locate `main.ts`.

    Cannot read file '/~/src/main.ts': Error: ENOENT: No such file or directory., '/~/src/main.ts'. The file is in the program because: Root file specified for compilation

### **Steps to Reproduce**

1. Go to this new Angular project: https://stackblitz.com/edit/angular-hjukhx
2. Compilation will start.
4. See error in dev tools.

### **Expected Behavior**
Renaming the `src` folder and fixing reference paths in `angular.json` should be accounted.

**Comment by markwhitfeld** [comment]
This project is not a WebContainer project, but rather an Engineblock project (before webcontainer).
I requires a very specific file structure and relies heavily on conventions.
The issue you are experiencing is because your change is breaking the convention for this type of project.

This will work in WebContainers, all you have to do is:
- Go to https://node.new to create a new node project
- Copy over your files from this project
- run npm install
- run your project as you would normally

Closing because the wrong project type was used here.

**Comment by john-fenton** [comment]
@markwhitfeld Thanks for investigating this. 
For completeness, the reason I suspected that it is a webcontainer issue is because it references webcontianer in the error stack:

```
webcontainer.f22f4c1a278d3f5126ea19984c93f163f1bff5da.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at s (webcontainer.f22f4c1a278d3f5126ea19984c93f163f1bff5da.js:8:66054)
    at webcontainer.f22f4c1a278d3f5126ea19984c93f163f1bff5da.js:8:223896
    at Array.map (<anonymous>)
    at jt.collectErrors (webcontainer.f22f4c1a278d3f5126ea19984c93f163f1bff5da.js:8:223878)
    at webcontainer.f22f4c1a278d3f5126ea19984c93f163f1bff5da.js:8:182630
```
