### ISSUE TITLE
Stackblitz cannot be refreshed

### ISSUE THREAD

**Issue by FirstVertex** [stackblitz/core#2483]
1. Visit a Stackblitz
2. Push refresh of web browser
3. Notice you're taken to the Stackblitz homepage

Observed: refresh button takes you to the Stackblitz homepage

Expected: refresh button should remain on the same page

Can be reproduced using any of the Stackblitz links on ng-bootstrap, for example press any Stackblitz button on this page:
https://ng-bootstrap.github.io/#/components/offcanvas/examples

**Comment by fvsch** [comment]
Hi @FirstVertex, thanks for the report!

This is a known limitation currently with projects created using our POST API or the `StackBlitzSDK.openProject()` method. Sites that use this method are creating a project that is not persisted in our database or on GitHub, and the project information only lives in your browser's memory. If you refresh the page, it’s gone.

Workarounds include:

1. When first loading the project, you can click the “Fork” button to make a more persistent fork. This works best if you are logged in to StackBlitz, so that we can associate this fork with your account. Otherwise we’ll keep a copy of it but it won’t be associated with your account unless you log in not too long after.

2. If you make changes to the original project and save with Ctrl+S (or Command+S on macOS), we will also fork the project for you.
