### ISSUE TITLE
Incorrect red squiglish lines

### ISSUE THREAD

**Issue by HarelM** [stackblitz/core#249]
project is here:
https://stackblitz.com/edit/angular-ngx-store-issue7

screen shot:
![image](https://user-images.githubusercontent.com/3269297/35225429-facf95f8-ff90-11e7-8abd-af0fca3d300d.png)

`WebStorageModule` is well defined in `ngx-store` as far as I know

**Comment by EricSimons** [comment]
@HarelM you are totally correct- we just spent the past 3 hours debugging & fixing this 😓 

Turns out the main field is pointing at ESM modules instead of of CJS modules + our typescript definition tracer had an edge case in it. Everything should be working now though! Can you test out and lmk if it's now working on your end?

**Comment by HarelM** [comment]
This seems to work now.
Thanks for the quick response and fix!
