### ISSUE TITLE
don't trigger a hot reload on every keystroke, by default

### ISSUE THREAD

**Issue by ginobean** [stackblitz/core#2493]
It seems wasteful and, useless, to trigger a hot reload on every keystroke.

Better strategy would be simply to wait for the user to stop typing/interacting for at least 5-15 seconds (maybe make this user configurable) and/or wait for a window focus change ..

**Comment by fvsch** [comment]
Hi @ginobean,

In StackBlitz projects you can go to the project settings in the sidebar to chose how the project should react to changes in the editor.

By default, changes in the editor are reflected in the virtual filesystem after a short delay (a bit less than one second), rather than after every keystroke. So if you're typing reasonably fast, it should only refresh once you've stopped typing, or a few times if you make a few pauses.

You can also set it to reflect changes only when you explicitly save the project, if you don’t want any auto-refresh going on.

What happens once projects are reflected in the virtual filesystem depends on the project type and the project configuration:

- For most projects that use the EngineBlock environment, we compile the project code and inject updates in the preview window. You can configure the project to reload the page instead, if that works better.
- For projects that use WebContainers, those projects usually run their own Node.js-based development server process, and it's up to that tool to manage page refreshing or partial updates (also called “hot module reloading” in some tools).

Changing our default behavior to wait for a long time like 15 seconds wouldn't work well. For most users it would just look like nothing is happening (15 seconds is a very long time!) and they need to automatically refresh the preview page, which is not the kind of experience we want by default.
