### ISSUE TITLE
Missing dependencies error on initial load

### ISSUE THREAD

**Issue by gyoshev** [stackblitz/core#250]
I have an [Angular application example](https://stackblitz.com/edit/angular-kkvuzc) running in StackBlitz. Upon first load, it shows a 'missing dependencies' error, even though the packages are listed as dependencies:

![image](https://user-images.githubusercontent.com/90405/35230365-7e7a86b2-ff9e-11e7-9b18-b3b043b96f1b.png)

After touching any of the application files (e.g. inserting a whitespace in the Angular templates), the application is recompiled and runs just fine.

Any ideas how I can resolve this? Should the problem be fixed by changing the packages, or is it a problem in the StackBlitz Angular compilation process?

**Comment by EricSimons** [comment]
Wow, this is _super_ bizarre. It looks like some of the kendo libs have jszip/pako listed as dependencies, which is triggering these errors- any chance you know where they're being imported & invoked? I'm super slammed today otherwise I'd dig in but I can deep dive tmrw morn

**Comment by EricSimons** [comment]
@gyoshev dug into this a little more - I think it would be best if we could suck in your UMD builds instead of the node main entrypoint (for ex: https://unpkg.com/@progress/kendo-angular-popup@1.3.3/dist/cdn/js/kendo-angular-popup.js instead of https://unpkg.com/@progress/kendo-angular-popup@1.3.3/dist/npm/main.js). This would speed up installation, improve perf speed in stackblitz + solve the problems above. Any chance you could list the UMD build in the package.json under the `unpkg` and/or `jsdelivr` field(s)?

**Comment by gyoshev** [comment]
Thanks for the fast response and the info!

To answer your question about the dependencies: `jszip` is a dependency of `kendo-ooxml`, which is loaded by `kendo-excel-export`. `pako` is a dependency of `kendo-drawing`.

We'd be happy to add a field in package.json to make speed up the runner :) From what I read in the [first StackBlitz announcement](https://medium.com/@ericsimons/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4), and [looking at the code](https://c.staticblitz.com/assets/engineblock-ec86cefaa481d8265fb1da9b6f043a759ed6787a5b288444038001a8beb30807.js), you are using SystemJS to load the dependencies. Do you think that adding support for [System bundles](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md) that directly use the `SystemJs.register` format would be beneficial to StackBlitz? That's inspired by the [`rxjs-system-bundle` package](https://github.com/OasisDigital/rxjs-system-bundle#see-it-in-action), and we've used it successfully in Plunker so far. Adding a `system` field in `package.json` feels better than mentioning a CDN service :) What do you think?

**Comment by EricSimons** [comment]
Totally agree about it sucking to include include the CDN-specific names, but unf there isn't consensus around the proposed `cdn` field yet :/ This thread on the d3 repo covers the current situation well: https://github.com/d3/d3/issues/3138 . A lot of widely used packages are using those fields now (d3, vue, etc), but totally understand why it's kinda weird to add them.

Another way around this is having the main field point at the UMD bundle, as node would be able to consume that as well as browsers. This is the way all @angular namespace packages are setup (might also be considered "best practice" IIRC).

Regarding the system bundles- we could add support for that, but our system setup is pretty funky since we're running webpack loaders & other custom stuff on top of it 😅  Our vendor stuff relies on CJS for the most part, so it might be a little tricky to enable the system register format (esp because the interop has known issues in systemjs land).

Do either of the first two solutions work for y'all?

**Comment by gyoshev** [comment]
We tried out adding the `unpkg` and `jsdelivr` fields to a sample package and pointing them to the CDN bundle ([package.json](https://unpkg.com/@progress/sb-092f14f@0.4.0/package.json)). This resolves the package on unpkg.com (https://unpkg.com/@progress/sb-092f14f@0.4.0), but didn't work in StackBlitz ([example](https://stackblitz.com/edit/angular-tmdjxz?file=app/app.component.ts)). Any ideas?

We're a bit reserved about modifying the `main` field, as it may affect customers who depend on it, without a workaround.

**Comment by EricSimons** [comment]
@gyoshev oo I need to enable unpkg field as override for all packages (right now we've been doing a whitelist for it).

HOWEVER, I just realized there might be a third option: setting the `browser` field to point at the UMD (i.e. `browser: './bundles/umd.js'`. Not sure if this would affect your tooling stuff at all, but figured I'd throw it out there :)

Preparing the update to support unpkg field globally now- will report back when it's live 👍

**Comment by EricSimons** [comment]
@gyoshev I found the root of the _actual_ problem causing the import errors -- in pako, the dist/pako_deflate.js file creates multiple modules in a single file and SystemJS is bugging out because of it. I'm going to investigate a fix and/or ping guy bedford about it!

I'd still rec using the unpkg field (or the browser field) just for the perf benefits tho 👍 

Will report back once @apai4 and I have a fix in!

**Comment by apai4** [comment]
@gyoshev we just pushed a hotfix for this; you can boot your project without issues now! Let us know if you run into any more problems, we're working on a full solution for this and PR'ing it upstream with SystemJS

**Comment by gyoshev** [comment]
Great news! Thank you for the effort. The sample is now working great. We'll be gradually adding the `unpkg` field to the packages to speed it up.
