### ISSUE TITLE
Can not import a project from Github

### ISSUE THREAD

**Issue by e-oz** [stackblitz/core#2654]
Please let me know why it doesn't run:
https://stackblitz.com/edit/github-ti6a8g?file=angular.json

Source: https://github.com/e-oz/state-mgmt-signals-example

**Comment by kc0tlh** [comment]
@e-oz the project is importing for me in our [new VS Code based editor](https://stackblitz.com/codeflow):

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/ccfd4ef2-a5b9-450a-98c3-fb19a540d469">

Simply add _pr.new/_ in front of a Github repo URL to import it: https://pr.new/github.com/e-oz/state-mgmt-signals-example

**Comment by e-oz** [comment]
You can see "Cannot GET /" on your own screenshot.

If it's an acceptable level of "how it should work", then I have no more questions.

**Comment by kc0tlh** [comment]
@e-oz apologies for any confusion I was just confirming that the project code can be imported into StackBlitz.

I am getting the same result from this repository when running in my local dev environment so I assumed that the Cannot GET / error was due to issues in the code rather than a StackBlitz IDE issue. 

Are you able to successfully run this code in a different dev environment?

**Comment by e-oz** [comment]
@kc0tlh the same code runs fine on GitHub pages: https://e-oz.github.io/state-mgmt-signals-example/
