### ISSUE TITLE
bug....bug

### ISSUE THREAD

**Issue by its-rio** [stackblitz/core#2727]
Yesterday i create a account on stackblitz, and i create a simple html, css and js   files but the output is not visible to me.

**Comment by fvsch** [comment]
Hi @its-rio.

We'll need more information to look into your issue.
Can you share a link to your project?

**Comment by its-rio** [comment]
https://dom-project-chaiaurcode-vff7k7.stackblitz.io
But after some searches  I read one answer and tried  to change  the
browser and it worked on chrome but not working on brave browser will you
please tell me in reply what I should do to run that on the brave browser?

**Comment by fvsch** [comment]
I suspect that the issue in Brave is this one:
https://developer.stackblitz.com/platform/webcontainers/browser-config#brave-service-workers

Since this is not something that we can fix in our app, but is more likely to be a browser configuration issue, I’ll close this issue for now. Feel free to reopen if you think there is a specific issue separate from the Brave configuration one.
