### ISSUE TITLE
Angular CLI project not working

### ISSUE THREAD

**Issue by nicky-lenaers** [stackblitz/core#274]
Hi,

First of all, this feature of running Angular CLI projects directly on Stackblitz is really amazing 🥇 ! So I have a public repo based on an Angular CLI project called [ngx-scroll-to](https://github.com/nicky-lenaers/ngx-scroll-to). So I tried changing the URL to [https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to](https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to), but it gives me the error message:

```sh
Something went wrong with this repository.
```

I'm not sure if the repo might not be suitable, but I hope you guys might clarify this.

Thanks

**Comment by apai4** [comment]
Thanks for reporting this @nicky-lenaers! I just pushed a fix so your repo can now be imported.

Note that we're prompting to install dependencies when the repo is imported, this is because we don't install `devDependencies` by default. We'll be adding support for this in the future. Having dependencies listed under `dependencies` in package.json will remove the prompt, but since your repo is meant to be a library, you could also have a separate folder and package.json for the example project (which we'll also be able to run).

Let us know if you run into any more issues!

**Comment by nicky-lenaers** [comment]
@apai4 Wow you're faster than lightning! Thanks for the quick fix, it is all working now. Indeed, the repo is a library, so for now I'm sticking with the structure of using `devDependencies`. I'll take your alternative with a seperate `package.json` into consideration for further development, so thanks for the heads up!

Great work on Stackblitz, loving it ❤️

**Comment by nicky-lenaers** [comment]
@apai4 Wow you're faster than lightning! Thanks for the quick fix, it is all working now. Indeed, the repo is a library, so for now I'm sticking with the structure of using `devDependencies`. I'll take your alternative with a seperate `package.json` into consideration for further development, so thanks for the heads up!

Great work on Stackblitz, loving it ❤️
