### ISSUE TITLE
Empty space at the bottom 

### ISSUE THREAD

**Issue by Kalyankal14** [stackblitz/core#2755]
After opening stackblitz, there is a empty space at the bottom. Unable to close or maximize my editing space.
![Capture](https://github.com/stackblitz/core/assets/134216294/bc502f04-66b9-4a8e-a7c4-0cf9242d09e4)

**Comment by fvsch** [comment]
Hi @Kalyankal14,

Could you provide more information on what browser and OS you are using?

Based on the screenshot this looks like Chrome on Windows, but I’m wondering:

- What version of Chrome?
- Is this on a Windows tablet or a laptop with a touchscreen maybe?

**Comment by Kalyankal14** [comment]
Version 97.0.4692.71 (Official Build) (64-bit)
laptop(not a touch screen)

**Comment by fvsch** [comment]
Thanks for the info.

I think the issue is that we are using the CSS `dvh` unit, which is supported in Chrome 108 and later. So here the fix is to update to a current release of Chrome.

- Current stable version: Chrome 117
- Chrome 108 release date: November 2022
- Chrome 97 release date: January 2022

We don't plan to maintain backwards compatibility with older versions of Chrome, and typically try to support the last few releases only (no fixed number, but 4 or 6 last versions is reasonable).

So here the fix would be to update your Chrome version to a recent stable release. That’s probably better from a security standpoint too: by running Chrome 97, you’re running software with known security vulnerabilities.

I’m going to close this issue, since supporting Chrome <108 is not planned.
