### ISSUE TITLE
Node Projects Not Found

### ISSUE THREAD

**Issue by maksym-tkach** [stackblitz/core#2839]
Every Node Project appears to throw a 404 Error, including ones I was able to open less than 24 hours ago. I created a new Node project as a test. i was able to work on it, but when I tried to access it from the Dashboard or Projects, it failed.

**Comment by alkarimlalani** [comment]
I am experiencing the same thing for all projects (React/Vite/Next/Node). This is a screenshot in case helpful:
<img width="957" alt="image" src="https://github.com/stackblitz/core/assets/3395494/80f833dc-323e-4133-874a-cc762c7af964">

**Comment by fvsch** [comment]
Thanks for the reports folks!

Indeed we're getting 404 pages for some existing Node projects for logged in users. The projects are still there, it seems to be faulty code (in specific conditions) when rendering the editor. We are rolling out a fix ASAP!

**Comment by fvsch** [comment]
This issue should be fixed now.

If you visit https://stackblitz.com/, the links to your projects should work correctly.

If you have an open tab for a Node project that shows a 404, you can fix it by:

1. Going back to the dashboard and finding the project again in the project list.
2. Or modify the URL: if it looks like `https://stackblitz.com/~/edit/my-project`, remove `~/  so that it looks like `https://stackblitz.com/edit/my-project`
