### ISSUE TITLE
Forked Projects missing Deps That Are There

### ISSUE THREAD

**Issue by crutchcorn** [stackblitz/core#2845]
I've started pulling some of my older Blitz to use GitHub sub-dir forking instead, and noticed a weird behavior:

https://stackblitz.com/github/unicorn-utterances/unicorn-utterances/tree/local-code-angular-start-to-source/content/blog/angular-templates-start-to-source/start-to-source-3-context?embed=1&file=src/app/app.component.ts

Despite this template having tslib right here:

https://github.com/unicorn-utterances/unicorn-utterances/blob/local-code-angular-start-to-source/content/blog/angular-templates-start-to-source/start-to-source-3-context/package.json#L44

I still get errors from StackBlitz that TSLib is missing and it doesn't show in the devDeps of the forked package.json

Am I doing something wrong here?

**Comment by fvsch** [comment]
Hi @crutchcorn,

It looks like your repository's subfolder is importing as an Angular project using the [EngineBlock environment](https://developer.stackblitz.com/guides/user-guide/available-environments). EngineBlock uses its own package manager and code compiler, and does download `devDependencies`.

If you’re using some package on the frontend (rather than strictly as part of a build tool), that package should be listed in `dependencies` and not `devDependencies`.

In particular, [tslib](https://www.npmjs.com/package/tslib) should be moved to `dependencies`. It's code that is used at runtime, rather than as compile time.

If that change is not enough to run this particular project with EngineBlock, you might want to try using the WebContainers environment instead. You can force importing your repository as a WebContainers-based project using `?template=node` in the URL:

```
https://stackblitz.com/github/unicorn-utterances/unicorn-utterances/tree/local-code-angular-start-to-source/content/blog/angular-templates-start-to-source/start-to-source-3-context?template=node
```

Though it looks like `npm install` fails because you have some Angular 8 packages in `dependencies` and some Angular 7 packages in `devDependencies`, so you might want to fix that too.
