### ISSUE TITLE
error could not find main when creating a github repository from a project

### ISSUE THREAD

**Issue by yehudamakarov** [stackblitz/core#2853]
error could not find main when creating a github repository from a project

**Comment by mauro-gobbi** [comment]
> error could not find main when creating a github repository from a project

@yehudamakarov not sure if this helps, but I had the same issue yesterday, and the root cause was that the default name for the default branch of my new repos in Github was set to "master" instead of "main".
Therefore every time I tried to create a new repo from StackBlitz I got the "main not found" error.

**🟢 Solution: simply set the default name of your repositories to "main" from here https://github.com/settings/repositories et voila!**

@HeyGarrison perhaps you guys could consider to improve the error message, to something more clear, instead of 
`"main not found" `
maybe something better like:
`"the branch <main> was not found, make sure your default repository branch name is <main> from the GitHub Settings"`

It would save a lot of time and make user happier.

Thanks!

**Comment by niblettr** [comment]
didn't work for me... however this did >>

![Image](https://github.com/user-attachments/assets/1bab6cd4-9109-4c8d-a294-b5ad9e9ec603)

then chose a name for said blank file. I think this then forces the creation of the "master" branch...
I suspect selecting "uploading an existing file" would work too...
