### ISSUE TITLE
Compiler get stuck in a JavaScript project because of comments

### ISSUE THREAD

**Issue by hymced** [stackblitz/core#2932]
### **Description of Bug**
Compiler get stuck in a JavaScript project because of comments
("Compiling changes..." appears indefinitely at the bottom of the IDE, and no further changes are reflected in the console or the document

### **Steps to Reproduce**

1. Open a new JavaScript project
2. Go to index.js
3. Replace or add the following code:

```js
// <script>

// var globalVar = "abc";
// var globalVar = "abc";
// var globalVar = "abc";
// var globalVar = "abc";
// var globalVar = "abc";
// var globalVar = "abc";
// var globalVar = "abc";
// var globalVa1 = "abc";
```

### **Expected Behavior**
it should not get StackBlitz to freeze

**Additional Context/Questions**
The above code in the comments above makes no sense, I had more text in my comments, by I narrowed it down to this MVE.
If one adds the closing </script> tag before pasting the comments with the dummy js code, it won't get stuck.
Also, it does not get stuck with a smaller piece of comments with dummy js code...

**Comment by HeyGarrison** [comment]
👋 Hey there!

I couldn't recreate this issue on my side. That being said it does make me wonder a few things…

1. Could you include a reproduction link?
2. What browser are you using and on what OS?

Additionally, I think you'd have a better development experience if you used Vite instead of our generic Javascript template. You can check that out here: https://vite.new/vanilla

Vite uses Webcontainer and because of this is way more powerful and reliable than our generic Javascript template.

**Comment by hymced** [comment]
Hi
I am using an up to date version of Chrome
Version 120.0.6099.224 (Official Build) (64-bit) on Win 10 Pro
Here is the repro, please fork it and notify me so I can delete it from my
account: https://stackblitz.com/edit/js-fjh2vj?file=index.js

**Comment by hymced** [comment]
Also when I open the project it is stuck on "Compiling application & starting dev server…" and changes won't reflect on the page or console

**Comment by hymced** [comment]
"Got it" as you found where lies the issue or you could reproduce the bug or just you got my message?
Also, no issue with the Vite starter.

**Comment by HeyGarrison** [comment]
Sorry for the confusion. I was expressing my understanding of the problem.

Yeah I think as a workaround I would recommend using the Vite starter, etc. The reason why it works is because it's using WebContainers as the underlying technology. You can see the differences here: [https://developer.stackblitz.com/guides/user-guide/available-environments](https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title)

We're currently in the process of releasing our next gen editor and so a lot of these sorts of edge cases will get better as we flip more and more of our starters over to it.

Hope that helps!
