### ISSUE TITLE
Static html from github not working

### ISSUE THREAD

**Issue by birkskyum** [stackblitz/core#2952]
I have a folder with static html here:
https://github.com/maplibre/maplibre-gl-js/tree/main/test/examples/

They are currently hosted here, but in order to edit, you'll have to clone locally etc.
https://maplibre.org/maplibre-gl-js/docs/examples/

I'd like to be able to preview each of these html files in stackblitz like this:
https://stackblitz.com/github/maplibre/maplibre-gl-js/tree/main/test/examples/

Alternatively, just one file:
https://stackblitz.com/github/maplibre/maplibre-gl-js/tree/main/test/examples/3d-terrain.html

**Comment by birkskyum** [comment]
Can i somehow specify that it's static mode?

**Comment by HeyGarrison** [comment]
👋 hey there!

I'd recommend opening the repo with pr.new. You can do that like this: pr.new/https://github.com/maplibre/maplibre-gl-js/tree/main/test/examples/

In order to preview these in StackBlitz you'll likely need a dev server like [Vitejs.dev](https://vitejs.dev) as well. So I'd probably recommend adding that in.

Hope that helps and happy to chat more if I'm not quite answering the question.

Thanks,
Garrison

**Comment by birkskyum** [comment]
@HeyGarrison , thanks!

When folIowing your link (https://pr.new/https://github.com/maplibre/maplibre-gl-js/tree/main/test/examples/) I get in the pr.new this error:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: glob@11.0.0
npm ERR! notsup Not compatible with your version of node/npm: glob@11.0.0
npm ERR! notsup Required: {"node":"20 || >=22"}
npm ERR! notsup Actual:   {"npm":"10.2.3","node":"v18.20.3"}
```

How can i tell pr.new to use something newer than node 18?
