### ISSUE TITLE
create repository assumes default branch is main

### ISSUE THREAD

**Issue by airtonix** [stackblitz/core#2986]
my default branch in github is not `main`.

so I can never create a stackblitz project stored in github.

**Comment by fvsch** [comment]
Hi @airtonix.

Do you mean the default branch setting in https://github.com/settings/repositories?

A possible workaround is to create your repository on github.com directly (on https://github.com/new) and select at least one of the three options that will trigger creating this repository with a first commit and your configured default branch (instead of creating an empty repository):

- “Add a README file”
- “Add .gitignore”
- “Choose a license”

Then you can work on that new repository on StackBlitz by opening it at:

```
https://stackblitz.com/~/github.com/{your_username}/{repository_name}
```

And StackBlitz will pull the repository’s default branch.

**Comment by KwintenP** [comment]
Could you provide some info on what url you specifically opened? If its a public repo and you are able to share, perfect. If not, that's also fine.

I tried to repro this but it seems to work on my end. 
See: https://stackblitz.com/github/kwintenp/non-main
