### ISSUE TITLE
MSW doesn't work in WebContainers

### ISSUE THREAD

**Issue by crutchcorn** [stackblitz/core#3003]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

When using MSW (2.2.3) in a WebContainers project, the `worker.start` doesn't ever resolve the `await` and makes the screen stuck

### **Steps to Reproduce**

1. Go to https://stackblitz.com/~/github.com/crutchcorn/tanstack-image-upload-eager-ui-demo
2. Page won't load

### **Expected Behavior**

`worker.start` should resolve, even with an error

**Additional Context/Questions**
Add any other context or questions regarding this bug.

This codebase works offline off of StackBlitz

**Comment by Nemikolh** [comment]
Hey @crutchcorn! :wave: 

This is a current limitation of our previews, they don't support service workers. It's definitely something we want to support, but in the meantime we could definitely throw an error. I'll add an internal ticket for this.

_I'm going to close this issue because supporting msw (and service workers) has already been reported in https://github.com/stackblitz/webcontainer-core/issues/846_
