### ISSUE TITLE
Packages are not installed immediately from package.json and then they are installed with incorrect versions

### ISSUE THREAD

**Issue by andrewtelnov** [stackblitz/core#3020]
### **Description of Bug**
Do not install packages on starting and then install packages with incorrect versions.
It works correctly in CodeSandbox

### **Steps to Reproduce**
Please go to the [test project](https://stackblitz.com/edit/react-kfwtbt?file=package.json).
It shows "Can't find packages: survey-coresurvey-react-ui" in preview. 
Click "Install missing packages" button.
It will install survey-core: 1.9.137 and survey-react-ui: 1.9.21. 

### **Expected Behavior**
It should install packages survey-core and survey-react-ui  with the latest 1.9.137 version on starting the project.
It works in CodeSandbox in this way.

**Additional Context/Questions**
We use several code sandboxes to allow edit our examples. Please go to [this page](https://surveyjs.io/form-library/examples/text-entry-question/reactjs), for example. You will see CodePen, Plunker and CodeSandbox buttons on the right top corner. You can select a needed framework and edit the example in the selected code sandbox.
We want to replace CodeSandbox with Stackblitz. The [test project](https://stackblitz.com/edit/react-kfwtbt) has been created from our app using your API. Unfortunately, we can't use it since the project doesn't show the preview immediately and it installs incorrect packages.

Thank you,
Andrew Telnov
SurveyJS Team

**Comment by fvsch** [comment]
Hi @andrewtelnov,

If you look in the sidebar of your project, the list of dependencies only include `react` and `react-dom`, and the `survey-core` and `survey-react-ui` packages are missing. Unless there is a specific bug on our side, this is likely because you used the StackBlitz SDK without providing a [`project.dependencies` object](https://developer.stackblitz.com/platform/api/javascript-sdk-options#projectdependencies).

Note that the SDK expects different information for projects that use the [EngineBlock environment](https://developer.stackblitz.com/guides/user-guide/available-environments#engineblock) and for those that use [WebContainers](https://developer.stackblitz.com/guides/user-guide/available-environments#webcontainers).

You'll find more information on how to manage dependencies using the SDK here:
https://developer.stackblitz.com/platform/api/javascript-sdk-dependencies

**Comment by andrewtelnov** [comment]
@fvsch Thank you very much. Adding project.dependencies object allows to solve the issue. I assumed that stackblitz pickup dependencies from "package.json" file. It is not a big deal to copy the dependencies from package.json into your project dependencies.

Thank you,
Andrew
