### ISSUE TITLE
stackblitz adding plugin

### ISSUE THREAD

**Issue by Vinodkumar009** [stackblitz/core#309]
i'm new to ionic & stackblitz,can anyone tell me how to add cordova plugin to the stackblitz project

**Comment by seveves** [comment]
It depends what cordova plugin you want to add. IMHO most of the cordova plugins won't work because they don't have a browser compatible implementation. Another point is that cordova does not fire it's platform ready event in the browser as far as I know.

If you really need support for a native feature (f.e. like camera or push notification) then I would write an angular provider/service that has implementations for the modern web and cordova. 

```typescript
interface PushNotificationService {
   subscribe(options?: Options);
}

class WebPushNotificationService implements PushNotificationService {
  subscribe(options?: Options) {
    // use Push API https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe
  }
}

class CordovaPushNotificationService implements PushNotificationService {
  subscribe(options?: Options) {
   // use some Cordova Plugin / Ionic Native etc.
  }
}

// in the providers array in your app.module
...
providers: [
  { provide: PushNotificationService, useClass: WebPushNotificationService } // later the cordova impl.
]
...

// and in some component:
class SomeComp implements Component {
  constructor(pushService: PushNotificationService) { }
...
```
