### ISSUE TITLE
I can,t run the program

### ISSUE THREAD

**Issue by As-m2023** [stackblitz/core#3106]
![لقطة شاشة_9-9-2024_84924_stackblitz com](https://github.com/user-attachments/assets/91144554-0161-406e-9caf-064914db79ce)

**Comment by SamVerschueren** [comment]
Hey @As-m2023 

The problem here is that your code contains syntax errors (as indicated on the right side). On line 6 (and line 8) you have 3 opening parenthesis `(` but only one closing one `)`. So as the error indicates, you are missing 2 closing parenthesis.

Closing this as it's not an issue on our side.
