### ISSUE TITLE
Scoped packages are not recognized as dependencies

### ISSUE THREAD

**Issue by lagatchell** [stackblitz/core#311]
When opening a project using the JavaScript SDK, scoped packages are not recognized as dependencies.

For example, I would like to be able to add Angular Material to my project automatically when opening the project. Currently this does not work.

```
sdk.openProject({
     files: {
          'main.ts': '',
          'index.html': ''
     },
     title: 'My Project',
     description: 'My Project Description',
     template: 'angular-cli',
     dependencies: {
          '@angular/material': '*'
     }
});
```

**Comment by vthinkxie** [comment]
Same problem, it seems there is a bug in dependencies.

**Comment by apai4** [comment]
Thanks for the info @lagatchell and @vthinkxie! The issue was caused by missing peer dependencies, if some were missing the project's dependencies were coming back as empty. I just made a fix so now if any peer dependencies are missing they will be prompted for when used at runtime instead. Lmk if it's working for you!

**Comment by vthinkxie** [comment]
@apai4 
It works now, thanks!

**Comment by janstadt** [comment]
Im still experiencing this issue with stackblitz enterprise. I have tried having my json obj specify all just specific angular deps, all deps, no deps (which seems to load the angular app fine but since i am missing specific deps it still asks me to install them), and finally i tried posting my own package.json file with ALL deps/devdeps. The last option i tried, stackblitz seems to completely ignore the package.json file and asks for a bunch of installations of missing deps. 

Another thing i noticed was that for the example angular cli example: https://stackblitz.com/edit/sdk-angular-data?file=basedata.ts, where basedata.ts has ALL the package.json files inline, that the actual stackblitz deps list does not match what is in the package.json file.

![image](https://user-images.githubusercontent.com/1872087/151849461-aea125aa-5b73-46af-936d-ba48d2c5199b.png)

I've paid for the enterprise on prem edition expecting these things to be taken care of but here we are, 4 years later with the same or similar issue. I am growing tired of waiting for responses from my support rep as well.
