### ISSUE TITLE
Importing lodash in a Typescript project rises an editor error

### ISSUE THREAD

**Issue by michaeljota** [stackblitz/core#319]
I'm trying to use lodash inside a Typescript, but so far I have been unable to do so. The main issue seems to be related to Typescript typing system. 

dependencies:
`lodash@4.17.5`
`@types/lodash@4.14.104`

Error: `Property '`any lodash property`' does not exist on type 'LoDashStatic'.`

- I try to uninstall lodash, and install typing module first, but I did not solve the issue. 
- I try `import * as _ from 'lodash'` and `import _ from 'lodash'`. Neither solves the error.
- Using `import * as _ from 'lodash'` does not even run the code.
- Using `import _ from 'lodash'` does run the code, but the error still in the editor.

I also notice that there is no errors in the console when running the application. I don't know if that's by design, but it should say something.

**Comment by EricSimons** [comment]
@michaeljota can you link the project here?

**Comment by seckardt** [comment]
@michaeljota You need to be specific regarding the `lodash` feature you want to import. Something like `import { get } from 'lodash';` should work. Besides that using `lodash-es` should be preferred over `lodash` in order to get tree-shakable results.

**Comment by michaeljota** [comment]
@EricSimons Sorry for the delay

https://stackblitz.com/edit/lodash-error

**Comment by michaeljota** [comment]
@seckardt Destructive import also rise the error.

**Comment by michaeljota** [comment]
@kylecordes Maybe I should change the title, but as I said, I can run the project. However, there is errors rising in the editor. In the code you share, it's not the same error, but it does rise an error.

**Comment by kylecordes** [comment]
@michaeljota Yes now I see.  The editor shows a red mark because it does not recognize the lodash import for TypeScript. Adding the types does not work; it just shifts the error to the left portion of the import. To get good results, with the style of importing individual operators, I had to:

* Switch to using `lodash-es` (add the NPM dependency, and change the import)
*  also import `@types/lodash-es`

you can see it in use here:

https://stackblitz.com/edit/github-av3nlg?file=src/app/reddit-search/reddit-image-search.service.ts

While unfortunate, I don't know of a way to avoid it for this. I think there is a chasm in thinking between two different groups of NPM package creators

* One group is accustomed to newer packages, like the way Angular is packaged. With this style of packaging, the goal is to have just a single package which provides whatever common bundle and language level variance are needed. Angular calls this the Angular Package Format, but prior to Angular some other package creators have had similar goals.
* Another group sees NPM as primarily, by default, about CommonJS/ES5 code; and treats anything other than that is a special case, requiring a special, different package name. In this case, `lodash-es` instead of `lodash`.

I hope the newer style gains popularity.

**Comment by seveves** [comment]
Please see my comment in #338 ... you can use `lodash-es` instead.
