### ISSUE TITLE
Code indent customization

### ISSUE THREAD

**Issue by roarwell** [stackblitz/core#323]
Would request you to consider providing a way to customize the indenting in the editor. The indenting space in use today is much less than the indenting length on the desktop VS code. I am sure the default provided are reasonable for some. Still pretty certain that it might be too little for many others.

Love the IDE btw!!

**Comment by patoezequiel** [comment]
Bump! I agree, having a way to set the indentation would be great.

Excellent IDE btw. Definitely going to spread the word 😁👍

**Comment by alexanderzeillinger** [comment]
Yes, please! 👍

**Comment by jarecsni** [comment]
I thought "editor.tabSize": 4 will do it, but apparently it doesn't work, please add support for this.

**Comment by apollolux** [comment]
Hello! I've recently started using StackBlitz for Angular practice and currently find myself looking for this feature as well. Please consider adding it, thanks!

**Comment by MattClendenen** [comment]
👍

**Comment by AlexandreLon** [comment]
Today, is always not implemented, any information ? 
I tested 
```
"editor.tabSize": 4,
```
and 
```
"editor.tabSpaces": 4
```

It doesn't work !

**Comment by matproulx** [comment]
+1 vote for this!

I've tried modifying tsconfig.json file, with no result

**Comment by Kiser360** [comment]
It appears auto-formatting is being handled by [prettier](https://prettier.io). Create a .prettierrc at the root of the project with the following contents
```json
{
    "tabWidth": 4
}
```

See docs for more options:
https://prettier.io/docs/en/configuration.html

**Comment by fvsch** [comment]
Hi everyone.

There are two sides to this coin:

- Which tab type and size the editor uses when you open a file. This controls what happens when you hit the Tab or Shift+Tab shortcut, or when you hit Enter to create a new line inside a code block.
- Which tab type and size the code formatter uses when reformatting files (for instance, when saving a file, because by default we format on save).

We're using two tools here: Monaco for the editor (that's the editor that lives inside VS Code), and Prettier for formatting files.

### Configuring the editor

Monaco will try to detect the indentation type and side by looking at the file when you open it. For instance if it sees code like this:

```js
function coolStuff() {
  console.log('How are you doing?');
}
```

then it’ll decide that the indentation type for this file is `spaces`, and the size is `2`.

You can also configure default values for new files in your User Settings, using the following three properties:

```json
{
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
}
```

- If you want to use tab characters instead of spaces (which can be good for accessibility for blind developers using braille displays), set `"editor.insertSpaces"` to `false`.
- If you'd rather use 4 spaces for indentation, you can change the `"editor.tabSize"` value to `4`. This also controls how wide a tab character looks.

But do read on to the formatting section, because if you make changes to the Monaco config you probably want a matching Prettier config in your project.

### Configuring the formatting style

You can configure Prettier _for a specific project_ in two ways:

1. Adding `"prettier" configuration option in the project's `package.json`, for instance:

```json
{
  "name": "my-project",
  "dependencies": {},
  "prettier": {
    "printWidth": 100,
    "tabWidth": 4,
    "useTabs": false
  }
}
```

2. Or by creating a `.prettierrc` file with Prettier configuration options in the JSON format:

```json
{
  "printWidth": 100,
  "tabWidth": 4,
  "useTabs": true
}
```

We currently don't support a way to set a global Prettier configuration in your account.

### Disabling Prettier

If you don't want to use Prettier at all, we don't have a way to disable it as this time.

But you can disable the “format on save” option in your User Settings, by setting `"editor.formatOnSave": false`. Then Prettier should get out of your way!

**Comment by kc0tlh** [comment]
In addition to @fvsch [guide for our Classic Editor](https://github.com/stackblitz/core/issues/323#issuecomment-1170039811) above, **[our new VS Code editor is now available here](https://stackblitz.com/codeflow)** with all the formatting options you are used to in your local dev environment!
