### ISSUE TITLE
Parse error for Polymer 3.0.0-pre.12

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#363]
See this blitz: https://stackblitz.com/edit/hello-polymer-3?file=example.js

Not sure what the error here is, the module loads in Chrome.

**Comment by EricSimons** [comment]
@justinfagnani this is a problem with our import tracing/compiling; since example.js is being dynamically imported the `@polymer/polymer/polymer-element.js` file isn't transpiled AoT (and thus throws this error).

Besides the upcoming static asset support we've chatted about, this can be solved in 2 ways right now:

1. Use normal ESM imports instead of dynamic imports (enables our tracer to do AoT compilation of all dependencies)
2. Used a normal ESM import to dev the example, then switch it to a dynamic import. When you hit save we actually save a cached version of your current compiled bundle, so the transpiled polymer files will continue to persist.

I know this is not super ideal- our upcoming upgrades to the bundler and dev server should completely eliminate all of these weird quirks though. Thanks for hanging in there :)

**Comment by justinfagnani** [comment]
Shouldn't it be fine if the file isn't transpiled? Seems like some other part of the toolchain doesn't have an up-to-date parser maybe.

In our case we can't use a normal JS import, because we have to wait for the polyfills to load before running app code. I tried using our blocking polyfill loader, but without complete control over index.html, the script tag for index.js is being inserted before the polyfill script tags, making the blocking/document.write behavior not work.

**Comment by EricSimons** [comment]
In order for ESM modules to be added to System's registry it needs to be compiled to either System.register or CJS format. With static asset support you'll be able to leverage module scripts though, which (obv) doesn't require any compilation/etc.

Regarding polyfill loader/scripts in index.html: all scripts listed in index.html _should_ be loaded & executed in order. Are you seeing this behave otherwise?

**Comment by justinfagnani** [comment]
What I was seeing for the blitz above was that the injected script tag for index.js was being run before the script tags I had statically in index.html. I'd rather add my own script tag for index.js and have full control.

**Comment by EricSimons** [comment]
Were you placing the script tag in `head`? If so, it should be guaranteed execute before index.js.

Adding own script tag for index.js will be enabled w/ new dev server static asset support :)

**Comment by justinfagnani** [comment]
I'll try it again and report back.

Awesome news again :)

**Comment by purplem1lk** [comment]
Thank you for your patience - The latest project link is no longer working and we are unable to move forward with this issue and will be closing this accordingly. We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with a working project link and screenshots of the error. Thank you! :)
