### ISSUE TITLE
I signed into my account and all the forks that were created anonymously were attached to my account

### ISSUE THREAD

**Issue by CurtisDS** [stackblitz/core#385]
This shouldnt happen

**Comment by EricSimons** [comment]
Is this not expected functionality? (i.e. why did you create forks anon?)

**Comment by random11x** [comment]
I'm sure it intentional. I just disagree with it. At best I feel that it should only attach the currently edited doc in the tab that you signed into to your account.

I generally use stackblitz anonymously for quickly writing example code to share. But I wanted to save one of the forks I made to my account. And as soon as I logged in all forks I had open in other tabs were added to my account. I had shared the urls thinking they were anonymous and then they switched to not being anonymous. So I had to delete all the forks from my account.

I'm not saying it's a bug. This is just my feedback.

**Comment by purplem1lk** [comment]
Thank you for your patience and the feedback! Since this template is typically for issues/bugs, we will be closing this issue accordingly. We are launching new core technology into beta this month - If you have any additional feedback to share, feel free to tag me or email us at hello@stackblitz.com. Thank you! :)
