### ISSUE TITLE
ngrx/store doesn't work properly

### ISSUE THREAD

**Issue by chris-hq** [stackblitz/core#40]
Moved the code over from a working prototype I was making to StackBlitz. The example is using ngrx/store and effects. After getting all the pieces over I was greeted with the message "Error occurred:
Can't resolve all parameters for _createStoreReducers: ([object Object], ?)."

Works fine in Webstorm.

**Comment by EricSimons** [comment]
Can you link your project here so I can investigate?

**Comment by chris-hq** [comment]
Sure thing. https://stackblitz.com/edit/angular-mzfxnr

**Comment by EricSimons** [comment]
Eek, this is a bug we ID'd yesterday with our dep resolver — nothing on your end :) Just updating all of the core angular packages to latest solves this problem (here's a fork of your code thats running w/ the updated packages: https://stackblitz.com/edit/angular-veytyk?file=main.ts)

**Comment by EricSimons** [comment]
We should have a permanent fix out for this on Monday or Tues, but till then that fix should work!

**Comment by chris-hq** [comment]
Sounds good, want to leave this issue open till the permanent fix is out? Thanks for figuring it out and letting me know. loving StackBlitz so far!

**Comment by EricSimons** [comment]
Yes definitely! I'll close this out once we put in the fix tmrw/Tues. Also, I just noticed that you're doing a http request for a JSON file in your assets folder — this won't work since all files are in memory and aren't actually static assets. We're going to add static asset support in pretty soon here, but till then you might just wanna point at a gist/etc where your JSON file is hosted :)

**Comment by EricSimons** [comment]
And thank you so much for the kind words, we really appreciate it!! ❤️

**Comment by EricSimons** [comment]
This bug is now fixed in prod!
