### ISSUE TITLE
"Can't find package" error when editing in StackBlitz, but when exported works correctly

### ISSUE THREAD

**Issue by tiliev** [stackblitz/core#424]
In this sample https://stackblitz.com/edit/immediate-npm-package-error I am using [js-zip](https://www.npmjs.com/package/jszip) package which depends on [lie](https://www.npmjs.com/package/lie) package which depends on [immediate](https://www.npmjs.com/package/immediate) package. When I run this sample, I am required to install the `immediate` package. However, if I export the sample from StackBlitz, run `npm install` & `npm start` it works. Do I miss something?

**Comment by apai4** [comment]
@tiliev I think i found the cause of this issue:

[`igniteui-angular` is using a dist version of `jszip`](https://github.com/IgniteUI/igniteui-angular/blob/d83bdb613da6ad09109fd260dd3da9e953dfb88c/src/services/excel/excel-exporter.ts#L1) which calls [`require('immediate')`](https://github.com/Stuk/jszip/blob/a4138a23cb9b8eb773c19af7d36d5ce2bcf4bfda/dist/jszip.js#L4565) without declaring it explicitly as a direct dependency.

You can get around this by importing the jszip source directly instead of the compiled dist version.

Here's an isolated repro of the issue:

[`jszip/dist/jszip` prompts for `immediate`](https://stackblitz.com/edit/typescript-phv7ub?file=index.ts&devtoolsheight=20)

[source version works OK](https://stackblitz.com/edit/typescript-ymwylz?file=index.ts&devtoolsheight=20)

**Comment by tiliev** [comment]
@apai4 Thanks a lot!
