### ISSUE TITLE
Unable to use Jquery in Angular Project

### ISSUE THREAD

**Issue by vishalbiradar** [stackblitz/core#438]
I have created a project and tried to use Jquery in it.
But getting the error.

Below is the Url of my project:
https://stackblitz.com/edit/angular-jquery-integration

**Comment by mlc-mlapis** [comment]
@vishalbiradar ... install dependency `@types/jquery` and use `import $ from 'jquery';`.

But because jQuery is the external thing the better way from the Angular point of view is to:

* install dependency `@types/jquery` to get typing
* place `<script src="http://code.jquery.com/jquery-3.3.1.min.js"`></script> directly to index.html
* create a token `export let jQueryToken = new InjectionToken('jQuery');`
* provide `providers:[{provide: jQueryToken, useValue: jQuery}]` in the main app module
* inject that token through `constructor(@Inject(jQueryToken) private $: jQuery) {...}` to any place where you need it

**Comment by vishalbiradar** [comment]
@mlc-mlapis Thanks a lot.
Do I need to create a separate class for `export let jQueryToken = new InjectionToken('jQuery');`
If you don't mind will you please create a sample project with the above-mentioned steps.
In that way, it will be very useful/understanable to me.

**Comment by mlc-mlapis** [comment]
@vishalbiradar ... no, it's not necessary. Just place it in the main app module ...

> Do I need to create a separate class for export let jQueryToken = new InjectionToken('jQuery');
