### ISSUE TITLE
Export JS project is not runnable / has no server

### ISSUE THREAD

**Issue by e111077** [stackblitz/core#444]
When a project is exported, there is no server to run it, and trying to
```
npm install && python SimpleHTTPServer
```
Will not work because scripts in `index.html`'s head will be pointing to `turbo_modules`, so that will require manual edits, and I don't think this is helpful for people that are new learners of web development.

It would be nice to add a simple `npm run serve` that points to a simple server and change the `package.json` to install to `turbo_modules`.

Or, perhaps provide an api for things that show up only on export e.g. a devDependencies config and a hidden server.js / gulpfile / gruntfile.

**Comment by EricSimons** [comment]
Good catch, I'll get a good export format set up that will allow this to run locally. Will circle back here tmrw once it's live 👍

@apai4 I'm thinking we should enable `node_modules` paths so the polymer folks can ditch our `turbo_modules` path, esp since we never meant for it to be used in a user facing way. This will also make it easier for the export scaffolding to work out of the box, per @e111077's comments.

**Comment by kc0tlh** [comment]
This issue is no longer salient in [our new VS Code editor](https://stackblitz.com/codeflow) which follows standard folder and git conventions and utilizes [npm, pnpm, or yarn](https://blog.stackblitz.com/posts/announcing-native-package-manager-support/) allowing local parity by default.
