### ISSUE TITLE
Can't run angular cli project from Github

### ISSUE THREAD

**Issue by jabas06** [stackblitz/core#459]
Hi,

I'm trying to run this angular cli project _https://stackblitz.com/github/coreui/coreui-free-angular-admin-template_, but I'm receiving the message **_"Error in src/app/views/error/404.component.ts (4:15)
',' expected."_**. If I run the project on my local environment, it works well.

**Comment by EricSimons** [comment]
Ah I think I might know what is causing this- will investigate tmrw morn & circle back!

**Comment by kc0tlh** [comment]
This issue is resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

You can check it out for yourself here: https://pr.new/github.com/coreui/coreui-free-angular-admin-template

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/44490b59-550d-4efd-b199-134443573d42">
