### ISSUE TITLE
StackBlitz does not work in IE 11

### ISSUE THREAD

**Issue by tiliev** [stackblitz/core#461]
Stackblitz does not work in IE 11.

**Steps to reproduce**:
1. Open IE 11.
2. Load the following URL - https://stackblitz.com/edit/ie-11-test which is the default Angular template.

**Result**:
Errors in the console and the sample isn't there.

**Expected**:
We should have an editable sample.

**Screenshot**:
![image](https://user-images.githubusercontent.com/6439482/39627811-b673f4fc-4faf-11e8-8f12-6be82577be3a.png)

**Comment by collins1830207** [comment]
Stackblitz does not work in IE 11 now...
Please see https://stackblitz.com/edit/clarity-light-theme-v1-0 and https://stackblitz.com/edit/ie-11-test, no error message in console.

**Comment by HDaghash** [comment]
Hi @apai4 
it seems it's still not working IE 11

**Comment by danail-vasilev** [comment]
Still not working - https://www.screencast.com/t/a3tPw3L1AZ8

**Comment by Orumiya** [comment]
Stackblitz doesn't work in IE11 
opening https://stackblitz.com/ outputs errors in the console:
![image](https://user-images.githubusercontent.com/15063646/79838932-0df91100-83b4-11ea-8850-1a108d8ee4e2.png)

**Comment by EricSimons** [comment]
Hey all- we're going to dig into this. I'm curious why y'all are using ie11? Is this something your employer is making you do or something?

The reason I ask is that we have some new functionality that won't be compatible with ie11, and I'm wondering what reasons/use cases exist that require ie11.

**Comment by papermana** [comment]
I can't talk for others here, but I'm trying to create a minimal reproducible example of a bug that occurs in IE11. Someone on the internet said that StackBlitz would work for that, unlike CodeSandbox, but that doesn't seem to be the case right now. I'm not even trying to edit the code in IE, I just want to see the tiny React app I wrote.

**Comment by Geo-Vann** [comment]
> Hey all- we're going to dig into this. I'm curious why y'all are using ie11? Is this something your employer is making you do or something?
> 
> The reason I ask is that we have some new functionality that won't be compatible with ie11, and I'm wondering what reasons/use cases exist that require ie11.

I dont want to work in ie but working with software that uses ie10 internally and need to be able to open my website in ie 10.  It appears this is not possible, correct?

**Comment by ryanki1** [comment]
Yes in my company material design components need to work in IE11 - company browser.. problem at the moment with datepicker showing.. wanted to view datepicker example through stackblitz (https://stackblitz.com/edit/angular-material2-issue-j3nv8f) and IE 11.. got bug mentioned by @Orumiya..

**Comment by lucaster** [comment]
> Hey all- we're going to dig into this. I'm curious why y'all are using ie11? Is this something your employer is making you do or something?

Many legacy intranet web applications were built against IE10 and older (even IE5 !!). This means that those legacy app rely on quick mode, non-standard javascript functionalities, non-standard css behavior, etc that are specific to IE. As a consequence, newly developed apps must have IE11 support in their SLA, so that users can just use IE11 for everything, and not switch between different browsers depending on which app they want to use.

**Comment by boghyon** [comment]
@lucaster 

> [...] newly developed apps must have IE11 support in their SLA. This way, users can just use IE11 for everything, and not switch between different browsers depending on which app they want to use.

That switching between browsers is no longer required with the new Edge by Microsoft.
Legacy web apps that require IE can be added to the _Enterprise Mode Site List_. The new Edge can then handle those old IE-based apps as well as apps that use modern web APIs **within the same browser**.

There is really no reason for new web apps to support IE11.

**Comment by lucaster** [comment]
Too bad there is no Edge on the old machines used by corporate users

**Comment by boghyon** [comment]
> Many legacy corporate intranet web applications were built against IE10

That actually suggests that the majority of those "old machines" are running with at least Windows 7 (Vista's latest IE version was 9). The new Microsoft Edge is available for Windows 7 as well.

The longer we support outdated browsers (e.g. IE5), the slower we can move forward with using standards on the web. And it's often times because of the innovations and standards we get new contracts by corporate customers who want to reduce development and maintenance costs by leveraging a single web application based on standards, in place of multiple OS-specific native applications.
