### ISSUE TITLE
How to include css from installed npm package

### ISSUE THREAD

**Issue by rashnk** [stackblitz/core#472]
i have installed primeng, and fontawesome
now i want add import css as below

```
"styles": [
  "../node_modules/font-awesome/css/font-awesome.min.css",
  "../node_modules/primeng/resources/themes/omega/theme.css",
  "../node_modules/primeng/resources/primeng.min.css",
  //...
]
```,

how to do this ?

**Comment by daniielvp** [comment]
Link to app?
I suppose you are building an angular app.

If anybody has this kind of problem with React(ES6):
`import 'primereact/resources/primereact.min.css';`

**Comment by jmdmao** [comment]
@daniielvp I have the same problem. my link is https://stackblitz.com/edit/strike

**Comment by daniielvp** [comment]
@jmdmao I've forked your app and this is the working version: 
https://strike-km4jfe.stackblitz.io/candidatos

The problem was in your `styles.scss` and `angular.json`, this is `styles.scss`: 
`@import 'app/_variables';`
`@import '~bootstrap/scss/bootstrap';`
`@import '~font-awesome/scss/font-awesome';`


`@import 'app/_variables';` // Always use relative paths because you never know where your app will be running.
`@import '~font-awesome/scss/font-awesome';` //Using `~` will make sass look into node_module.

For `angular.json` just remove any trace of :
`"node_modules/font-awesome/scss/font-awesome.scss"`

Hope that helps and have fun building your app! 👍

**Comment by jmdmao** [comment]
Okay. But the icons do not load .. :(
![image](https://user-images.githubusercontent.com/29717874/39958763-773a27b2-55d5-11e8-915d-275f5bcbc10d.png)

**Comment by rashnk** [comment]
but i got another stackblitz which is primeng configured

**Comment by daniielvp** [comment]
@jmdmao Add `$fa-font-path: "node_modules/font-awesome/fonts" !default;` to your styles.scss
