### ISSUE TITLE
Install packages from package.json

### ISSUE THREAD

**Issue by dwaq** [stackblitz/core#5]
It would be great if the editor automatically detected the file or at least had a way to manually read a `package.json` file and install the dependencies that way.

**Comment by EricSimons** [comment]
Is this for when you drag + drop a package.json file into the editor?

**Comment by dwaq** [comment]
Yes, that's a good start. But also typing a package into `package.json` should add the package to the dependencies.

**Comment by EricSimons** [comment]
I dig it — will add to the roadmap!

**Comment by albertosantini** [comment]
@EricSimons I was wondering if it is possible to update all the deps clicking on whatever.

At the moment the dep is updated if the dep name is inserted in the input field "enter package name" (as removing it and adding it again).

If there are a few deps that is not a convenient way to make a bulk update.

Do you think this issue is the right one to track this request (because it may be related to package.json) or do you prefer a new one?

**Comment by EricSimons** [comment]
This has been live on prod for a while- closing! 👍
