### ISSUE TITLE
IE11 Promise is undefined (+ request for OTA hot reloading)

### ISSUE THREAD

**Issue by yiochen** [stackblitz/core#51]
I really like the `Open in New Window` feature. I was hoping I could develop in chrome, then test IE (IE 11 to be exact) compatibility inside a virtualbox by copying the app URL over. It's not working currently, IE 11 complains `Promise undefined`. Any plans for adding polyfills for missing features in IE?

**Comment by EricSimons** [comment]
Yikes! We'll def look into the IE11 promise issue you're seeing. Regarding open in new window, the way we're gonna do that is with websockets (since IE/Edge don't support PWA API's yet :)

Should have a fix out for IE11 shortly & OTA hot reloading over websockets should happen within the next month!

**Comment by apai4** [comment]
@yiochen polyfills for IE 11 have been added, lmk if you run into any issues!

**Comment by yiochen** [comment]
Works for me. This is awesome! I will recommend this to my team

**Comment by yogeshgadge** [comment]
Still same issue in IE 11

> `Object doesn't support property or method 'includes'`

**Comment by SargoDarya** [comment]
Having the same issue with IE11 on Win 8.1 trying to run:
https://stackblitz.com/edit/material2-beta12-zskkud

**Comment by yiochen** [comment]
Linked to an open issue that tracks `Object includes` #184
