### ISSUE TITLE
Does stackblitz support proxy.conf.json

### ISSUE THREAD

**Issue by anand-ma** [stackblitz/core#518]
I was trying to reverse proxy my node server local host from stackblitz, it doesn't seem to work. IS there an example where i can post to a local host from stackblitz.

I dont know if this is an issue or a feature request.

**Comment by kc0tlh** [comment]
StackBlitz currently doesn't support direct connections to a local development server due to security constraints and browser limitations, although we may consider this in the future via a VS Code or browser extension.

However, you might be able to work around this limitation by using a service like [ngrok](https://ngrok.com/) or a similar tool to expose your local server to the public internet. Please note that this approach exposes your local server to the internet, and there may be security considerations to take into account.
