### ISSUE TITLE
Color for the keywords is mismatch - Angular project

### ISSUE THREAD

**Issue by vidhya03** [stackblitz/core#521]
The keyword color is mismatched 
![image](https://user-images.githubusercontent.com/534679/40599116-37349ca6-6269-11e8-9e41-fcf252ffe696.png)

https://stackblitz.com/angular/dyoborabjqx?file=src%2Fapp%2Fkeyup.components.ts

**Comment by seveves** [comment]
The problem is caused by line 21 where the `event.target` gets cast into a `HTMLInputElement`.
By the way I would prefer type assertions with "as" instead of the "angle-bracket" (`<TYPE>`) way because "as" is also working in JSX/TSX files.
And the funny thing is that there is no problem when you are writing line 21 like that:
`this.values += (event.target as HTMLInputElement).value + ' | ';`

... but of course the syntax highlighting should work both ways.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
