### ISSUE TITLE
Array construction with spread syntax and map doesn't work

### ISSUE THREAD

**Issue by codeKonami** [stackblitz/core#546]
I use this syntax quite a lot to create my Arrays

```js
const foos =
    [...Array(4)]
        .map(x => 'foo');
// ['foo', 'foo', 'foo', 'foo']
```

But on your platform the array has the good size but of "undefined" element.

See here : https://stackblitz.com/edit/js-mtffex

**Comment by seveves** [comment]
Your pattern should definitely work but how about using `Array.from({ length: 4 }, x => 'foo'));` 😎

**Comment by codeKonami** [comment]
@seveves That's a really nice way to do it too :)
Thanks

**Comment by gdlm91** [comment]
I'm having the same problem while trying to create a range of numbers using this pattern:

- https://stackblitz.com/edit/js-v83uva

```js
const minNumber = 1;
const maxNumber = 10;

const rangeArr = [...Array(maxNumber - minNumber + 1)].map(
  (item, index) => index + minNumber
);

console.log(rangeArr);
```

returns 
```
[undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
```

Instead of
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Tried the same pattern in other platforms and they work correctly:
- https://jsbin.com/sutiqunowa/1/edit?js,console
- https://jsfiddle.net/41xhbr6q/
- https://codepen.io/gdlm91/pen/bGGxaJx?editors=0011

Using @seveves pattern works correctly:

```js
const minNumber = 1;
const maxNumber = 10;

const rangeArr = Array.from(
  { length: maxNumber - minNumber + 1 }, 
  (item, index) => index + minNumber
);

console.log(rangeArr);
```

**Comment by jayphelps** [comment]
A seemingly related issue is how spreading works in general. It seems however Stackblitz is doing compilation, it's in some sort of very loose mode that IMO is way too lose for something like Stackblitz.

e.g. `[...something]` is always compiled to `something.slice()` which is a big no-no because `something` can be anything iterable, including a `Set` which doesn't have slice, concat, etc.

**Comment by sulco** [comment]
Good catch everyone, thanks for reporting this!
Yeah, it was confusing...

Thankfully it should no longer be an issue :)
