### ISSUE TITLE
Angular export is not compatible with cli

### ISSUE THREAD

**Issue by arikanorh** [stackblitz/core#561]
Export angular project isnt compatible with angular cli v6.

First it has src folder inside another src folder and there are some duplicate files like polyfills. The download project angular cli version is 1.x.x.

And as expected, it doesnt compile nor run.

Under those circumtances, it is hard to continue development after prototyping on stackblitz.

**Comment by brunolm** [comment]
Possibly related to import issue #260 
Example: https://stackblitz.com/github/brunolm/angular-how-to

**Comment by tiliev** [comment]
@arikanorh, can you provide a link to the project you try to export? This will help the team to narrow down the issue. Thank you.

**Comment by arikanorh** [comment]
@tiliev This happens on any project. Just create a new angular project on stackblitz. Then export it then you will see the file structure is as decribed.

**Comment by kasparov112000** [comment]
I am having the same issue, here is my app repo https://github.com/kasparov112000/newbio2

**Comment by nishantshreshth** [comment]
This is what I had to do to make an exported project work:

1. Move the main.ts from internal src to outer src: `mv src/src/main.ts src`
2. Move app from internal src to outer src: `mv src/src/app src`
3. Add any project specific resources (css, js) to `.angular-cli.json`

**Comment by adamk33n3r** [comment]
I will add that in StackBlitz I was able to import json files but in the exported project I could not.

**Comment by m67hoff** [comment]
I don't agree with the no 3 from above (add things to .angular-cli.json) and think since this is a new angular-cli version 

It is better:

1. Move all from internal src to outer src:  `mv src/src/* src/`
2. delete .angular-cli.json
3. move src/angular.json out of src `mv src/angular.json .`
4. install / update missing npm packages (since the exported package.json is too old)

```
npm i
npm i @angular/cli@latest
npm i codelyzer@latest
npm i @angular/compiler-cli
npm i @angular-devkit/build-angular
ng update --all
ng s

```

or use the attached updated package.json  (and than `npm i`)

Grüße aus Heidelberg - Michael

[package.json.zip](https://github.com/stackblitz/core/files/2375192/package.json.zip)
