### ISSUE TITLE
Stylesheets in HTML are added after application scripts

### ISSUE THREAD

**Issue by gyoshev** [stackblitz/core#584]
I have a React component that requires a stylesheet to be loaded on the page, in order to function correctly. In certain cases, likely related to cache, the component scripts get executed before the stylesheet is loaded. Here is [an example](https://stackblitz.com/edit/react-lr8h2d?file=app/main.js) that sometimes shows the issue, although I have not found a very reliable way to reproduce it.

The problem looks like this:

![image](https://user-images.githubusercontent.com/90405/42274086-186d0626-7f94-11e8-93ad-da62fd2d9249.png)

Triggering a hot reload on the JavaScript code (by typing a space) fixes the issue, because the stylesheet is present:

![image](https://user-images.githubusercontent.com/90405/42274146-49977704-7f94-11e8-8625-0855b2f064d1.png)

From what I gather, the issue is caused by the late async add of the stylesheet in the generated page.

![image](https://user-images.githubusercontent.com/90405/42274314-dc284ef4-7f94-11e8-895e-25e8446a27d4.png)

**Workaround**: The problem does not appear if the stylesheet is declared as an external resource. Unfortunately, the POST API does not support this at this time. Would it be possible to allow linking to external resources in the POST API?

![image](https://user-images.githubusercontent.com/90405/42274537-b8e9d2cc-7f95-11e8-9e26-102885af18dd.png)

**Comment by gyoshev** [comment]
@EricSimons any chance for allowing external resources to be added through the POST API? This issue is currently blocking us from deploying StackBlitz integration, as it breaks the scripts that depend on global styles.

**Comment by EricSimons** [comment]
@gyoshev sorry about the delay here- this is super weird, any stylesheets defined in your head tag should have load priority before execution of your JS files. Will investigate and circle back by EOD! 👍

**Comment by EricSimons** [comment]
@gyoshev I was able to reproduce the error- it looks like it may have been caused by the unpkg link to the css file. Could you try changing it to a different cdn (jsdelivr/etc) and see if that fixes it?

**Comment by gyoshev** [comment]
@EricSimons Thanks for the quick responses! Indeed, changing the CDN seems to do the trick 🥇 Thank you for the workaround, really appreciate it, and our examples seem very runnable at this point 🎉 We'll give it some more testing, but we're at the final stretch to deploy this.

**Comment by tsvetomir** [comment]
Turns out that loading the css file from jsdelivr only masked the issue, but did not solve it. It appears to be working as jsdelivr allows the response to be cached for 1 week, thereby eliminating the load delay for further requests:

![image](https://user-images.githubusercontent.com/247917/47768607-78f6e980-dce1-11e8-9f27-7612213dd591.png)


With unpkg.com the response is allowed to be cached only for 1 minute. This is expected as the `latest` dist-tag that can change at any moment:

![image](https://user-images.githubusercontent.com/247917/47768796-31bd2880-dce2-11e8-90cc-43c9d5b3666b.png)

Normally, css resources [should block script execution](https://hacks.mozilla.org/2017/09/building-the-dom-faster-speculative-parsing-async-defer-and-preload/). This is why we don't see this problem outside of StackBlitz.
> When the parser gets to a script tag, DOM construction cannot proceed until the JavaScript finishes executing, and the JavaScript cannot be executed until the CSS is downloaded, parsed, and the CSSOM is available.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
