### ISSUE TITLE
Put a compilation delay

### ISSUE THREAD

**Issue by vhb56** [stackblitz/core#59]
Hi,  thank you for an awesome site!

Please, make it possible to put a delay and/or start btn to start a compilation.
I work with Ionic and 'live update' is too heavy for slow machines and often not really necessary until a certain moment.
Like https://jsfiddle.net/ with their RUN button.

And, please, only if it is possible add a possibility to change a keybinding, for example i use IntelliJ IDEA keybindings, because i've switched too often between different environments to start confusing everything. 

Thx!

**Comment by EricSimons** [comment]
Eek! I totally get why this is frustrating — we'll add in an option to turn off the auto-hotreload functionality ASAP. This will likely ship the week after next, simply because my cofounder and I are going to be traveling all of next week.

Until then, **you can get around this by popping the preview into a new window**. This ensures the preview will be using a completely separate process and won't affect the editor's performance.

Question regarding how you'd want to trigger hot reloads: would hitting the "save" button (or it's corresponding cmd+s key) be a reasonable way for that?

**Comment by EricSimons** [comment]
Oh and regarding keybindings, we're def working on that :)

**Comment by vhb56** [comment]
trigger on save is ok :)
but i would prefer auto save(without reload) & RUN btn to reload.
maybe 2 opts: relaod on save / reload on RUN btn

**Comment by simeyla** [comment]
Does this exist now? It's super frustrating the way it works. If I try to tidy up my code formatting while the page is reloading then it refreshes!

**Comment by EricSimons** [comment]
@simeyla I know it's super annoying, so sorry! 😓  @claytonschneider and I are planning on getting this in within the month- will circle back once it's on prod. For the time being, I'd rec opening the preview in a new window so that reloads don't interfere with the editor UX
