### ISSUE TITLE
Some questions about private usage

### ISSUE THREAD

**Issue by Peng-YM** [stackblitz/core#604]
Is it possible to deploy stackblitz in my own server or use it in company? If it is possible, could you provide some extra information about the environment setup? Thanks!

**Comment by durvalrafael** [comment]
I have this same doubt over here

**Comment by samtsai** [comment]
This is a duplicate of #134 There's a little more discussion in there if we wanted to follow that issue instead.

**Comment by beeman** [comment]
Since last week we added the option to sync projects to (private) GitHub repos and making projects private.

![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55047388-9f138200-5012-11e9-92a3-3acffb2683ff.gif)


Closing this issue as self-hosting the server-side of StackBlitz is not something that's on the roadmap for the foreseeable future.

**Comment by JustinBobby007** [comment]
It's useful to support deploying stackblitz in one's own server or use it in company because many projects in corporate are behind in firewalls and have not access to external sites.
