### ISSUE TITLE
Receiving error "style is not a function" when creating a project

### ISSUE THREAD

**Issue by jhenderson2099** [stackblitz/core#625]
Receiving the following when importing a npm package [@blackbaud/skyux](https://www.npmjs.com/package/@blackbaud/skyux)

```
Error in /turbo_modules/@blackbaud/skyux@2.18.0/dist/modules/modal/modal.component.js (157:51)
core_1.style is not a function
Evaluating https://unpkg.com/@blackbaud/skyux@2.18.0/dist/modules/modal/modal.component.js
Evaluating https://unpkg.com/@blackbaud/skyux@2.18.0/dist/modules/modal/index.js
Evaluating https://unpkg.com/@blackbaud/skyux@2.18.0/dist/modules/modal.js
Evaluating https://unpkg.com/@blackbaud/skyux@2.18.0/dist/core.js
Evaluating src/app/app.module.ts
Evaluating src/main.ts
Booting application
```

The problem is that ```style``` is a valid angular function (https://angular.io/api/animations/style).

No further information is supplied.

Using Stackblitz via Chrome 67.0.3396.99

**Comment by apai4** [comment]
@jhenderson2099 it looks like the problem is actually with `@blackbaud/skyux`, they're using the `style` function imported from`@angular/core` (https://v4.angular.io/api/core/style) which was deprecated in Angular 4 and moved to `@angular/animations` (https://angular.io/api/animations/style). You'll either have to wait until they release a new version importing from `@angular/animations`, or you'll have to use an older version of Angular (`style` was deprecated but still existed in Angular 5).

**Comment by jhenderson2099** [comment]
@apai4 Thanks!  That was exactly the problem.  I dropped back and "npm install"ed the Angular 4 libraries and the issue went away.  

I am closing this issue as I believe it is resolved with the above information.
