### ISSUE TITLE
not abe to import project from github

### ISSUE THREAD

**Issue by Thamizhvanan-R** [stackblitz/core#626]
not able to import angular project from this github repository.
github/Thamizhvanan-R/AngularApplication/tree/master/Application

StackBlitz URL - https://stackblitz.com/github/Thamizhvanan-R/AngularApplication/tree/master/Application

**Comment by Rugved** [comment]
I have the same issue

**Comment by linhub15** [comment]
It appears that Stackblitz can't find the package.json file because it's only looking in the repository root.
According to the [docs](https://stackblitz.com/docs#import-from-github) you can optionally specific the branch, tag, or commit but **not a sub directory**. `/tree/Application` is not a branch, tag or commit. It is a sub directory in your repository so it fails.

Maybe specifying a sub directory could be a feature request in the future?

**Work Around**
Move Angular project to root.
e.g. [Tour of Heroes Github](https://github.com/johnpapa/angular-tour-of-heroes) loads into ->[Stackblitz](https://stackblitz.com/github/johnpapa/angular-tour-of-heroes)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
