### ISSUE TITLE
not throwing any issue during re-assign value in const variable

### ISSUE THREAD

**Issue by rjoydip** [stackblitz/core#640]
Please check out my example https://stackblitz.com/edit/js-stackblitz-issue-const. Instead of throwing an error it giving the output.

**Comment by dalbir** [comment]
Hi, I have facing the same issue, it should be corrected. 
My example https://stackblitz.com/edit/react-n5uqvw

**Comment by purplem1lk** [comment]
I see an error in the original project link - Since this is the intended behavior, this issue will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)

<img width="1440" alt="Screen Shot 2021-04-27 at 9 32 48 AM" src="https://user-images.githubusercontent.com/49956513/116250227-89b23a00-a73b-11eb-8820-abcd0c6db3f1.png">
