### ISSUE TITLE
Support images & static assets

### ISSUE THREAD

**Issue by wjhurley** [stackblitz/core#72]
The app assumes that file.png is actually a .js file and tries to import file.png.js, which it cannot find. Create-react-app allows for importing files other than .css and .js, but StackBlitz does not.

**Comment by EricSimons** [comment]
@wjhurley we're working on adding support for static assets 🙌  should ship later this month/early next!

**Comment by DenisVuyka** [comment]
Hello guys, do you have any updates on the static resources and "assets"?

**Comment by Misiu** [comment]
Hi guys, any news?
I'm trying to move entirely to StackBlitz, but I can't because of missing static assets.
I need to create couple of vanilla js files and reference them in index.html, but currently I can't 😢 

Please take a look at:
https://stackblitz.com/edit/microcharts?file=index.js
How can I reference `microchart.js` in `index.html` or `index.js`?

**Comment by EricSimons** [comment]
Hey all- really sorry about our delay on this, we've been completely slammed fixing/upgrading countless things. Static asset support has also proven to be a more difficult challenge than we originally anticipated, particularly because all of this would be happening inside your browser (the stackblitz dev server lives within your browser's service worker) and ensuring reliability/stability+ backwards compatibility for older browsers isn't straightforward.

That said, the good news is that we've been slowly chipping away at this and have finally sorted the large technical challenges. Current ETA is 2-4 weeks, but we're also giving a talk at ng-conf at the end of April that might affect that window by a week or so.

As we make progress on this I'll circle back here and update y'all. Thanks for being so patient & awesome! 🍻

**Comment by urish** [comment]
@EricSimons any updates on this? anything I can do to help?

**Comment by andregomars** [comment]
please give updates

**Comment by jhildenbiddle** [comment]
Adding yet-another-voice to the static asset request. 

I have a demo that I would like to make available on StackBlitz, and it requires one file to request another using XMLHttpRequest. 

Accessing the file via HTTP is related to #133. The fact that the demo is bread-and-butter HTML+CSS+JS means the issue is also related to #179 and #340.

Thanks, and keep up the great work!

**Comment by michahell** [comment]
base64 aaaaaaaal the things! 
`<img src={base64'ed blob} />` works, confirmed
https://www.base64-image.de/

**Comment by DenisVuyka** [comment]
@michahell is that a joke? should we base64 all resources, like translation files, app configuration files, etc?

**Comment by michahell** [comment]
@DenisVuyka no. It's a temporary workaround for if you have a bunch of (small) images you'd like to use, but I should have commented this in the related *images* only issue, I now see this was about assets in general.

**Comment by seveves** [comment]
@DenisVuyka I'm pretty sure that @michahell 's intent was to help you and he wasn't kidding at all. At the moment there is no support for static assets (yet!). So please be patient or find a workaround (uploading static files to github, dropbox or whatever and link them from there). Shouldn't be a big deal for a capable developer.

**Comment by idevthings** [comment]
¿Any ETA? Last one was 12 weeks ago if I am not wrong.

I love stackblitz btw, great tool. Keep up the good work!

**Comment by SuganNaickerf** [comment]
Hi, Love StackBlitz. Any update on the static assets? Thanks.

**Comment by kumaresan-subramani** [comment]
Hi,
i am also facing sample issue. please inform me also when this issue get fixed.
[https://github.com/angular/angular/issues/27531](https://github.com/angular/angular/issues/27531)

**Comment by EmilYoYo** [comment]
Any idea when this feature can be expected?

**Comment by Insira** [comment]
any update on this feature?

**Comment by webpropopuli** [comment]
C'mon guys. Either admit you can't do it, give us a viable workaround or put a HUGE DISCLAIMER on the site saying "don't do this". Please? This is a super-cool tool but...ouch.

As a new React dev, I spent 2 hours thinking this was _my_ issue, diving into webpack and scaring many other rabbits....ugh

**Comment by mfs409** [comment]
If it is any help, I think there are three different use cases here, and while they are interrelated, it may be easier for the StackBlitz maintainers to divide and conquer.

The first case (@wjhurley) is where the programmer has static assets that need to be imported into the app.  If I understand correctly, this is a case where webpack is trying to get an asset at "compile" time, and it is being provided to webpack incorrectly.

The second case (@jhildenbiddle) is where the application dynamically fetches assets at run time.  The app wants the StackBlitz server to provide those assets.  I have this problem too, and can propose an ugly workaround.  Instead of trying to fetch the assets from the local server, I keep them in a GitHub repository, and when fetching, I prefix the asset names with `https://raw.githubusercontent.com/<USER>/<REPO>/master/<PATH>/`.  Right now, this is sloppy, because I have an "assets" folder in my repository, and not in my StackBlitz project, and I can't just drop assets into the StackBlitz project.  But if StackBlitz finishes tightening its integration with GitHub repositories, this solution might be satisfactory.

The third case (@Misiu) is that there are some legacy JavaScript libraries that really want to be included in an app via a script tag in index.html, not via import statements in a JS/TS file.  This is a fundamentally different problem than the above two: StackBlitz does not give the programmer access to the true base HTML file, so script tags don't exactly work.  I have encountered this problem too, and can propose an ugly workaround (again).  I'm using TypeScript, and found that if I put the entire source of the JavaScript library into one of the files that uses it, and I export the main variable of that library, then I can get to it from everywhere I need to, and it works.  It's ugly.  But it works.  Maybe a similar approach will work for @Misiu.  (See /src/jetlag/internal/support/XY.ts in the StackBlitz project I reference below).

If my code is a help to anyone, it's at https://stackblitz.com/edit/jetlag.  For reference, JetLag is an HTML5 framework for making 2-D games with Box2d-style physics and PIXI.js graphics.  I use it for educational outreach activities at schools and libraries, so I really am excited about using StackBlitz... right now, I either have to bring a few dozen chromebooks with me when I do a free event, or else I need to get admin permission on the site's computers so that I can install node.js, vscode, and JetLag.  StackBlitz is really ideal for my use case, and I'd be happy to assist in testing any proposed solutions to this issue.

**Comment by miltonhowe** [comment]
I second @webpropopuli - this issue is now almost 18 months old and remains as far as I can tell completely unaddressed despite many optimistic prognostications unmet as evidenced by the passage time.

Fair enough, it is not my place to criticise the efforts and priorities of those whose work I am grateful for.

I humbly suggest and request that the pain of waiting for this functionality would be greatly eased by the inclusion of the shortcomings (and perhaps links to issues with suggested workarounds) in the project docs and instructions. And that meaningful messaging and error handling be considered for things like binary uploads silently crashing the `save project` function.

**Comment by dirkluijk** [comment]
I have another use case for this. I would like to give a workshop on service workers, and would like to use StackBlitz as IDE. But when I add a `sw.js` script to my StackBlitz workspace, it has incorrect mimeType and is not being served.

**Comment by AhammadAliPK** [comment]
i spent around 2 hours like this was my issue , then i did in googled  **stack blits images angular** , then I took the first result , in that example also , images are not serving . Then I felt , aaaaaaaaaaa

**Comment by oocx** [comment]
With Angular CLI 8, Angular supports .svg files as component templats. I wanted to blog about it and include StackBlitz examples in my blog post. This seems to be impossible right now, I get "import error, can't find file".

**Comment by metacoding** [comment]
come on guys this feature is really needed

**Comment by crhodes2** [comment]
One year, going on two since this issue.
Let's just admit that this feature is never going to happen within the next five.

**Comment by terra819** [comment]
Here's a workaround that may be sufficient for some needs. It takes a couple of extra steps, but it is possible to serve an image from the assets folder on a stackblitz app: https://stackblitz.com/edit/angular-stackblitz-static-image

**Comment by terra819** [comment]
Lets try this again. Posted this before, but found out that if you move your image, the link doesn't update until some time later and then you have a broken link... https://stackblitz.com/edit/angular-stackblitz-static-image

**Comment by joselvelez** [comment]
I really like stackblitz BUT I am really upset about the glaring omission on this from the beginning. I've spent so much time checking my work thinking that it was a mistake only to find out that this is an ongoing problem that has not yet been addressed. Not cool guys.

**Comment by urielblanco** [comment]
> I really like stackblitz BUT I am really upset about the glaring omission on this from the beginning. I've spent so much time checking my work thinking that it was a mistake only to find out that this is an ongoing problem that has not yet been addressed. Not cool guys.

You can bind you project to github, then navigate to your images folder click on one img, copy the url and add "?raw=true" i.e: https://github.com/<user>/<project>/blob/master/<folder of img>/banner01.jpg?raw=true

Finally you get this: 
<img src="https://github.com/xxxxxx/yyyyy/blob/master/zzzzzz/banner01.jpg?raw=true" alt="banner of example">

It works for me, greetings!

**Comment by mfs409** [comment]
> > I really like stackblitz BUT I am really upset about the glaring omission on this from the beginning. I've spent so much time checking my work thinking that it was a mistake only to find out that this is an ongoing problem that has not yet been addressed. Not cool guys.
> 
> You can bind you project to github, then navigate to your images folder click on one img, copy the url and add "?raw=true"
> 
> `i.e: https://github.com/<user>/<project>/blob/master/<folder of img>/banner01.jpg?raw=true`
> 
> Finally you get this:
> `<img src="https://github.com/xxxxxx/yyyyy/blob/master/zzzzzz/banner01.jpg?raw=true" alt="banner of example">`
> 
> It works for me, greetings!

The problem with this approach is that it is tied to github.  For some use cases (such as K-12 outreach), you can't really require students to get a github account.  So while I agree that it resolves the problem for some cases, I would like to encourage keeping this issue open.

**Comment by whitneyland** [comment]
I just paid for a year subscription because it promised file uploads as a feature.  Yeah, I could have read a bunch of docs, but I didn't I'd find, people doing something so cool, would promise important features to people on github and break date estimate promises for 2 years straight and counting.

Is this really still a thing? Should I chargeback my credit card?  

I wouldn't ask for a deadline.  Wouldn't dishonor you like that. As a fellow developer I've done startups I know your hurting.  

But my personal opinion is you at least owe a status update.  For example, the scenario of uploading a .jpg picture of cat and being able to see it, how's that one coming?

(btw I thought I recall it was against github policy to raw link images and use them on web sites).

**Comment by senseijames** [comment]
While this is still clearly an issue (and a fairly glaring omission from such an awesome site, IMHO) I highly recommend just going with @EricSimons' initial suggestion: upload your image to imgur.com and reference it from there.  Bigger fish to fry and all that.

**Comment by gspassky** [comment]
OMG this issue is more than 2 years old!!! Please, make default assets directory in project root for static files. Now any file here is processed as Angular route and of course fail.

For example, I wanted to add favicons to my project. I can't do it! I'll try to upload them to side hosting and make a link, but not sure it's ok for favicons...

**Comment by gspassky** [comment]
Guys, you are doing absolutely foolish features like "Deploy to space", and can't solve real problems!!!

**Comment by gspassky** [comment]
Well, summarizing all gathered info...

The only workaround of this issue now - is to take side hosting for static files, and use (for example) static.yourdomain.com in paths in your app... This also works with favicons.

Of course, in some cases, it's OK to use inline SVG or base64 encoded images...

**Comment by EricSimons** [comment]
Hey all- direct file uploads are WIP. Closing this issue as it's a dupe of https://github.com/stackblitz/core/issues/45, will be circling back there in the next 1-2 months once this is live on prod 🍻

**Comment by gspassky** [comment]
Guys, there is a workaround, if you are making PWA with StackBlitz and Firebase Hosting and were stuck with creating service worker js (now it's impossible to make it with StackBlitz, using standard StackBlitz deploy functionality). Take a look at https://gist.github.com/puf/e00c34dd82b35c56e91adbc3a9b1c412 - it allows you to upload one file to Firebase Hosting without changing all other (which were uploaded by StackBlitz). In comments I've wrote some changes to code to make single-page apps work properly.

**Comment by weilies** [comment]
I have been with Stackblitz for almost a year. Only recent month i found lots of breaks
- ngx-translate, broke when deployed to firebase
- img src can't include image
- my main project started to failed deploy to firebase and i hv no visibility of the log/reason

started to wonder should i move out to MS visual code... i mean aside from the issues i faced above, it's almost PERFECT tool... comparing i should learn the IDE and do all the setup in Visual code from 0 again...

**Comment by EricSimons** [comment]
@weilies this week has been a tough one on our end, I'm really sorry about my delay on responding to your email. I'm going to chunk some time out this weekend to investigate the issues you're running into.

Btw, later this year we're rolling out a huge upgrade to SB that makes it truly a desktop-class IDE, which will solve a lot of the issues described here/bring parity with your local envs. Would love to have you beta test that if interested!

**Comment by urish** [comment]
@EricSimons how do I join the beta?

**Comment by weilies** [comment]
count ME IN!!! @EricSimons LOVE U!

**Comment by skamble89** [comment]
Any update on this??

**Comment by mart2k** [comment]
> @weilies this week has been a tough one on our end, I'm really sorry about my delay on responding to your email. I'm going to chunk some time out this weekend to investigate the issues you're running into.
> 
> Btw, later this year we're rolling out a huge upgrade to SB that makes it truly a desktop-class IDE, which will solve a lot of the issues described here/bring parity with your local envs. Would love to have you beta test that if interested!

"later this year" ... aha ... year is almost over. Any updates on this?

**Comment by weilies** [comment]
i guess we should still treat StackBlitz for hobby project. I have a crucial project so i moved to other platform for serious development. @EricSimons sorry. I still love StackBlitz for the quick adoption. For demo or testing, i still use SB.
But i understand, making it a 100% reliable dev platform it does takes time~

**Comment by carlba** [comment]
Stackblits is perfect except this one problem. It already can host static files but it does not provide the correct mime type for them.

**Comment by haakon-io** [comment]
Sad face :(

**Comment by earshinov** [comment]
I've given up on StackBlitz and migrated to CodeSandbox, which I advise you to do as well.

**Comment by EricSimons** [comment]
Hey everyone- I apologize for the delay on the update here. We actually shipped static asset support in 2020, so you can drag & drop to upload images and other binary files and they should upload 100% correctly. If you're seeing functionality otherwise please lmk.

Additionally, our v2 version is (finally) on production behind a feature flag- this is the thing I mentioned in an earlier post that brings desktop grade editing to StackBlitz. It solves the issues regarding linking to uploaded binary files because it's running the entire Angular CLI/create-react-app/etc CLIs themselves instead of our custom in-browser bundler. If you'd be interested in trying out the alpha please email me at eric@stackblitz.com and I'll get the feature flag added to your account, our team would love to hear your feedback. ETA for general availability of this is late April or May 2021 (i.e. 30-60 days from now).

@earshinov @haakon-io I'd love to understand what exact issues you ran into and if you'd be up for trying out v2 🤗

**Comment by EricSimons** [comment]
And actually, to shed some extra color on what the heck we've actually been up to and why it's taken so long for this to ship- you can take a look at the first public preview of our new v2 product on [the AngularAir podcast](https://youtu.be/5F9qH-ea5Qk?t=621) from a few weeks back.

**Comment by weilies** [comment]
hi Eric let me share bit from my personal exp after many months of using StackBlitz. It's cool, pick and run to test on certain package. But i also noticed one thing, when there are packages required some other depencies, sometime it failed me. It stuck at the 'compiling screen' and sorry i couldn't have a project upgrade. I basically scrap the project and move on to CodeSandBox, which is much more easy to get the installation up and running.

Some packages i experienced the compiling forever issue are like formio, primeNG, some calendar widget. i didn't capture every single failure of StackBlitz.
And in CodeSandbox, it's not perfect as well. Coz i noticed after it run for awhile, those package i mentioned above cause the editor freeze (for no reason)

My best development experience so far is via Google Cloud shell, but again it required you to arrange every folders, installation our own, lots of time we gotto read the compile/build errors. no choice.

My development workflow now, 
Proof of concept - StackBlitz, then CodeSandbox
Production/Development - Google Cloud Shell.

**Comment by EricSimons** [comment]
@weilies thanks so much for posting this detailed writeup- this makes a ton of sense. I think the main reason you've run into issue with both StackBlitz and CodeSandbox is that both options currently 'emulate' the Angular CLI/create-react-app/etc instead of running the CLIs themselves. This leads to divergence in compatibility and unexpected issues (like this github issue, and many others on ours & Codesandbox's issue tracker).

Our v2 product solves this problem by running the CLIs themselves, similar to how Google Cloud shell works- except StackBlitz v2 executes these up to 5x faster (more info [here](https://youtu.be/5F9qH-ea5Qk?t=621)). Would you be interested in trying out the alpha? If so, please shoot me an email and I'll get you hooked up- eric@stackblitz.com ❤️

**Comment by weilies** [comment]
My product is LIVE and the forge is already root in Google. I can't afford to uproot and migrate to StackBliz. At least for coming few years. But i do happy to test for you, as i POC package before bring them into my development workspace. Will email u now

**Comment by haakon-io** [comment]
@EricSimons - I was trying to use some HTML <picture> tags to test some things out, then I discovered that I can't use images in StackBlitz. That is why the sad face.

**Comment by arikanorh** [comment]
Is static js import supposed to work?
`import Twitch from 'src/assets/scripts/twitch.js';`

The script exists there but compiler gives error

`Cannot find module 'src/assets/scripts/twitch.js' or its corresponding type declarations.`

![image](https://user-images.githubusercontent.com/17791032/124882715-57de0f00-dfd9-11eb-8825-028b530e0f56.png)

**Comment by ralflukner** [comment]
It's sad that static images are not supported.

**Comment by timshaw9791** [comment]
I'm a vite+vue3 developer, it looks like only the 3th method is supported until now? do I miss something?
![image](https://user-images.githubusercontent.com/6415962/146674503-ebd9a3e4-fba8-487c-b793-5e88d2fe28d3.png)

**Comment by Slluxx** [comment]
i need exactly this too.
@timshaw9791 's case 1 should definitly work.

sad that this issue is open since 2017.

**Comment by BioPhoton** [comment]
Would be really cool to have this working. Any official plans on that?

**Comment by rba1aji** [comment]
> The app assumes that file.png is actually a .js file and tries to import file.png.js, which it cannot find. Create-react-app allows for importing files other than .css and .js, but StackBlitz does not.

Alternative?

**Comment by rba1aji** [comment]
@EricSimons  thanks for great stackblitz. Still no update on static assets? what is an optimal alternative?

**Comment by pct-cclausen** [comment]
It somewhat surprises me that such a basic thing still does not seem to work?
This is a deal breaker to use stackblitz for anything serious I think.

Sad, stackblitz is a pretty cool idea :(

**Comment by karlji** [comment]
It's still not working. It's pretty sad because it is a deal breaker.

**Comment by frankstepanski** [comment]
So you still cannot reference images uploaded in a Raact app?

**Comment by cgatian** [comment]
No

**Comment by QuangDuke** [comment]
Hey, just wonder how's t going with the feature update? its 2024 now

**Comment by frankstepanski** [comment]
Same

**Comment by Jmadih** [comment]
7 years later... no assets support yet. No big deal, good luck guys!

I think the feature is available only for premium users : https://angular-ivy-phwyr1.stackblitz.io/ 

I've run the same app and i'm getting this url (****)-12d46890.local-credentialless.webcontainer.io/assets/data.json

(0;0) credentialless...
