### ISSUE TITLE
How can I deactivate text wrap in the editor ?

### ISSUE THREAD

**Issue by LucaGabi** [stackblitz/core#727]
Please help.

Thanks.

**Comment by nukadelic** [comment]
Doesn't look like you can do that right now, but if you are worried about long lines of code, I could suggest a simple alternative solution: 
* Make the font smaller by zooming out ( `ctrl` + `-` )
* Close the left panel ( click the current active icon to hide the panel ) 
* Open preview in another window (handy if you have more then 1 monitor, or use the classic `alt`+`tab`)

**Comment by sulco** [comment]
Thanks for submitting the issue! We now support most of the VSCode editor settings, so in order to deactivate text wrap you can set `"editor.wordWrap": "off"` in your workspace or user settings.
![2021-02-09 12 59 35](https://user-images.githubusercontent.com/1511906/107361019-0176ae00-6ad7-11eb-8164-313cf5716040.gif)
