### ISSUE TITLE
Dev sever won't start after adding a dependency in an Angular project

### ISSUE THREAD

**Issue by amellnik** [stackblitz/core#756]
I'm trying to add a dependency (`angular-plotly.js` which has a peer dependency of `plotly.js`) to [this stackblitz](https://stackblitz.com/edit/clarity-light-theme-v013) from the Clarity team.  Adding the dependency appears to succeed, but afterwards the dev server never loads ([example here](https://stackblitz.com/edit/clarity-light-theme-v013-zgbapj)).  No errors are shown anywhere.

**Comment by Markus-Ende** [comment]
I have the same problem. Network tab of Chrome Devtools reveal that it's an issue with the package size: `Package size exceeded the configured limit of 50 MB.`

There is an alternative way to install plotly.js using cdn, but unfortunately I can't install angular-plotly.js without plotly.js because the latter is a peer dependency of angular-plotly.js, so stackblitz refuses to install it.

**Comment by amellnik** [comment]
@Markus-Ende Good catch!
