### ISSUE TITLE
Loading dependency (@Company) incorrectly, minimal setup

### ISSUE THREAD

**Issue by mokimo** [stackblitz/core#772]
**Minimal project setup (2LoC)**
https://stackblitz.com/edit/react-s2j8cb

1) Added "@livingdocs/node-sdk"
2) Used it
3) Prompt to install missing dependencies
4) After installing those missing ones, more issues ("couldn't find .zlib_bindings")

**What is expected to happen?**
import liSDK from '@livingdocs/node-sdk'
-> Being able to correctly use this package (This is possible on a local project set-up, not on Stackblitz though)

**What's the error?**
Following error appears: 
_"Can't find packages:
eventsurlstring_decoderhttphttpszlib"_ 
When the missing packages are installed, another issue arrises ("couldn't find /.zlib_bindings")

I've also tried to track down the issues within the livingdocs-sdk, but we have no dependencies in the tree that use zlib_bindings, from what I've found so far.

Is it possible that it's a general @company_package problem?

**Comment by hdsdev** [comment]
Hi, I have the same problem when I use the "tesseract" library on an angular project.  I get a "couldn't find /.zlib_bindings" error

**Comment by samuraijane** [comment]
I ran into the exact same problem with *@react-pdf/renderer*. The problem is with the **zlib** library itself. This is what I have been able to find out so far:

1. Export your project from StackBlitz
2. In the root of the project on local, run `npm install`
3. Open the project in an editor
4. Navigate to **Node_Modules/zlib/lib** and open **zlib.js**

You'll see something like this which clearly shows what the problem is:

![zlib-missing](https://user-images.githubusercontent.com/8484986/57037871-5dd04c80-6c26-11e9-9f09-ef0bcec67ea2.png)

It appears that **wscript** is supposed to build this file:

```
zlib/wscript (lines 6 – 9)

TARGET = 'zlib_bindings'
TARGET_FILE = '%s.node' % TARGET
built = 'build/default/%s' % TARGET_FILE
dest = 'lib/%s' % TARGET_FILE
```

However, at this point, I do not know how to proceed. Maybe someone else reading this thread can illuminate the rest of us on what is keeping **wscript** from building *.\/zlib_bindings*.

For what it's worth, [zlib](https://github.com/kkaefer/DEPRECATED-node-zlib) has been deprecated for years. The last commit I see in the repo is February 2016.
