### ISSUE TITLE
JSZip is not a constructor

### ISSUE THREAD

**Issue by igandrews** [stackblitz/core#778]
I'm seeing an error in the console ('JSZip is not a constructor') when trying to create an instance of JSZip in stackblitz. You can see a simple example [here](https://stackblitz.com/edit/angular-jszip-test).

It doesn't seem to matter how I import it. We use the following in our code.
`import * as JSZip from 'jszip/dist/jszip';`
But I also tried including the @types/jszip and using the following but the result is the same.
`import * as JSZip from 'jszip';`

If however I change it from **new JSZip()** to **new JSZip.default()** then it works but that wasn't necessary previously and doesn't seem like it should now either since locally the project does work.

**Comment by purplem1lk** [comment]
Thank you for your patience - I don't see the initial error that you mentioned, but it's possible that code changes since the inception of this issue have solved the error you were seeing. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

<img width="1439" alt="Screen Shot 2021-04-30 at 4 55 25 PM" src="https://user-images.githubusercontent.com/49956513/116753295-dfedda00-a9d4-11eb-8d38-c35531191169.png">
