### ISSUE TITLE
[Ionic] Current default project doesn't display icons in tabs

### ISSUE THREAD

**Issue by janpio** [stackblitz/core#82]
Just creating a new Ionic projet gives this error:

![image](https://user-images.githubusercontent.com/183673/29280437-8179e45e-811b-11e7-88f0-d1598d1fc2cf.png)

**Comment by EricSimons** [comment]
This is due to bad code unpkg just pushed: https://github.com/unpkg/unpkg-website/issues/51

I just changed the CSS file to be hosted off jsdelivr, so if you fork the Ionic project on the homepage it should work now :) 

Btw this was the last straw with Unpkg, we've had nothing but problems with their CDN for months now. I'm planning on migrating everything off them and over to jsdelivr when I'm back from vacation.
