### ISSUE TITLE
Can`t import Masonry Module already installed in dependencies  

### ISSUE THREAD

**Issue by Andrey-Nosfer** [stackblitz/core#87]
![image](https://user-images.githubusercontent.com/22439686/29315642-e3311b34-81cc-11e7-85b0-a3950da97074.png)
![image](https://user-images.githubusercontent.com/22439686/29315653-f83aeb0e-81cc-11e7-86a7-fe036ae02481.png)
![image](https://user-images.githubusercontent.com/22439686/29315664-06869262-81cd-11e7-9d6c-733ad9bf2030.png)
What i doing wrong?

**Comment by EricSimons** [comment]
Hmm this is odd — can you link your project here so I can repro & debug?

**Comment by EricSimons** [comment]
Actually there's no need to post your project here, this is a problem with the angular2-masonry package itself — the main field is pointing at a file that doesn't exist (angular2-masonry.js). Did you create this repo? (If so, you should change the main field to 'index.js' which will fix this error for everyone using rollup, browserify, webpack, etc). Otherwise, you can get around this error by just directly importing the index file like so:

```js
import { MasonryModule } from 'angular2-masonry/index'
console.log(MasonryModule)
```
