### ISSUE TITLE
github repo created but not populated with content

### ISSUE THREAD

**Issue by mshgh** [stackblitz/core#911]
I have tried this
- create new empty JS Stackblitz project
- connect it to github

What I can see
- new repo with correct name is created [OK]
- no files created
- in my browser I can see some message: creating repo, committing, updating branches. At the end some progress bar in front of "main" branch is endlessly rotating
- if I change file I can commit the change and provide message, but github repo stays empty all the same

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. Since there have been multiple code changes since the inception of this issue, we recommend attempting this again. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
