### ISSUE TITLE
Save has no effect when working with Github repo.

### ISSUE THREAD

**Issue by JoshuaHD** [stackblitz/core#913]
When i have a project connected to github the save operation has no effect.

I would like to save the project state before commiting it to the repo. 

Unfortunately the editor is pulling on each start data from the repo and overwriting the local save. 

I sometimes end up writing endless loops or other things that hang up my browser and not being able to save means i lose a lot of work if i have to restart the browser.

**Comment by JackSinclairT** [comment]
Same issue here, despite saving multiple times, whenever i reload the page all my changes are lost.

Page before reloading:
![image](https://user-images.githubusercontent.com/9784427/68962187-e8942580-07cb-11ea-9b28-8cc41f9aab5d.png)

Page after reloading (all changes gone):
![image](https://user-images.githubusercontent.com/9784427/68962230-fe094f80-07cb-11ea-9428-ab3915c5397d.png)

Nothing in the console.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by Asheq096** [comment]
This issue still persists May 2023... I see a couple of tickets open with Github integration not allowing a user to save and losing work and a recent ticket where it will even result in severe data loss ON GitHub... Terrible it hasn't been fixed in almost 4 years!

If anyone comes across this thread, here is the workaround that works for me AND will recover work that was saved but is not showing:
1. If your StackBlitz project is already connected to GitHub, you need to disconnect it. You can do this by creating a StackBlitz fork. The new fork will not be connected.
2. You will now have to work on this new fork from now on. Do NOT connect it to GitHub.
3. Changes should save again like normal. Whatever changes you had saved that were not showing up in the original project should show up in this new fork. This is because I believe changes are indeed saving, just that if project is connected, it will pull the files from GitHub instead of from the StackBlitz project.
4. When you want to commit, unfortunately you will have to download the project to your local machine (download button below the Fork StackBlitz button) and commit on your machine.
5. StackBlitz and GitHub are now in sync. Continue working on StackBlitz. Repeat step 4 every time you want to commit.

This urgently has to be fixed by StackBlitz!
