### ISSUE TITLE
Stackblitz embed is not working in mobile

### ISSUE THREAD

**Issue by nguyentk90** [stackblitz/core#92]
Hi,

I've created a stackblitz angular project and tried to embed to a blog post. It's working fine on desktop but it cause reload many times on safari ios and crash web page on chrome ios.

**Comment by EricSimons** [comment]
Eek! Can you link the project that's crashing here? That way I can investigate & debug!

**Comment by nguyentk90** [comment]
Here you are:
https://nguyentr.com/angular-tutorial-01-getting-started/

I test on my iphone, it crashes.

**Comment by EricSimons** [comment]
Okay, so I just did a quick test and I think it's because there are two editors running on the same webpage which uses up too much memory in iOS. Running VS Code/Webpack/etc in browser in hard enough on a mobile browser, and x2 apparently crashes it :)

There isn't much we can do to get around the hard technical limitations of mobile browsers, but perhaps we could track how many editors are embedded on a given page and implement scroll tracking to only start an editor once the user has scrolled to it? Would love to hear your thoughts here.

I'll start working on a fix for this over the weekend but in the meantime, if you remove one of the editors that _should_ solve this (please report back either way though! :)

**Comment by EricSimons** [comment]
PS - I LOVE how you're using stackblitz in this tutorial. Once we get this mobile issue fixed I'm gonna tweet it out for everyone to see! 🍻

**Comment by nguyentk90** [comment]
Yeah, I didn't think about memory on phone's browser. You are right, I have just removed one editor and it's WORKING. Thank you for that!

If you can enhance the embeds by scroll tracking, it would be perfect but I think it's not high priority, because after reviewed the post, one editor may be enough. Also what do you think if we have an option for embed link that it only start when we click on the embed on webpage?

I love Angular and VS Code so I definitely love Stackblitz 👍. Thanks for your great work!
