### ISSUE TITLE
Right click on left panel issue

### ISSUE THREAD

**Issue by imnickvaughn** [stackblitz/core#922]
Recently when I right click on left panel in chrome/windows it will instantly go to another page(not redirect) and that page will be blank.  I will lose all my work since last save.

Before right click
![image](https://user-images.githubusercontent.com/24948723/55696892-08897e00-598d-11e9-8b43-64a2e5ea6546.png)

After right click
![image](https://user-images.githubusercontent.com/24948723/55696853-d11ad180-598c-11e9-9fd0-3d2748dac688.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - I have attached a screenshot of what I see when I right-click on the left panel in an Angular project. It's possible that this issue has been fixed through various code changes since the inception of this issue. This issue looks resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-12 at 7 48 20 PM](https://user-images.githubusercontent.com/49956513/118057954-060f6480-b35b-11eb-9fbb-449683575c13.png)
