### ISSUE TITLE
GitHub Changes Doesn't Reflect on IDE

### ISSUE THREAD

**Issue by vivekpatel19** [stackblitz/core#932]
I have Initialized IONIC project to GitHub Repo after that i made changes to description and project name in Stackblitz IDE but it doesn't reflected to Github. also there is no option to disconnect that particular repo so i can initialize with new name.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. There have been code changes since the inception of this issue so I recommend trying another Ionic project again. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
