### ISSUE TITLE
Unable to import Angular project from Github.

### ISSUE THREAD

**Issue by ThomasBurleson** [stackblitz/core#937]
When I import using [`stackblitz.com/github/ThomasBurleson/ngrx-ticket-management`](https://stackblitz.com/github/ThomasBurleson/contact-manager)

![image](https://user-images.githubusercontent.com/210413/56234684-b3a7d080-603a-11e9-8353-dc4de156b611.png)

The **Starting dev server** never completes due to errors:

> This runs locally very easily. See [Github TIcket-Manager](https://www.github.com/ThomasBurleson/ngrx-ticket-management)

Refs #626, #400

**Comment by lichunbin814** [comment]
I have the same issue, this is my repo link

https://stackblitz.com/github/lichunbin814/angular_bootstarp_dropdown/

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm unsure if there have been code changes since this issue was posted, but the screenshot shows what I see on my end. However, we are launching new core technology into beta this month that should resolve related issues so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-12 at 8 20 15 PM](https://user-images.githubusercontent.com/49956513/118059864-7ae49d80-b35f-11eb-92ed-41e936a1c3cf.png)

**Comment by MarioNeubacher** [comment]
I tried to open a public repo with https://stackblitz.com/github/ + CagriAvsar/portfolio 
![image](https://user-images.githubusercontent.com/90280732/162409818-b022f589-36d4-4277-ba5c-8d6a1c218b0b.png)
