### ISSUE TITLE
Hot reload not working correctly on chrome

### ISSUE THREAD

**Issue by kumari1224** [stackblitz/core#948]
1) Hot reload stops working after one or two edits into the files, and it's not even working after refreshing the preview window.

2) File save is not working properly too, as after saving (CTRL+S) so many times, on reload of the page, it prompts the warning as **Your changes may not be saved**.

**Comment by willi84** [comment]
1. Can you give a sample stackblitz or github repo AND your chrome and OS version?

2. yes, after changing you need to hit the "save" button in the upper left corner

![image](https://user-images.githubusercontent.com/6207308/58877075-298df700-86d0-11e9-82c7-85b49d86d78f.png)

**Comment by purplem1lk** [comment]
Thank you for your patience. I am unable to reproduce this error - It's possible that previous code changes have fixed this since the inception of this issue. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link and a screencast of what you're seeing. Thank you! :)
