### ISSUE TITLE
GitHub Branch Switching

### ISSUE THREAD

**Issue by prateektalesara** [stackblitz/core#951]
The git branch switching is not working and at least there should be a terminal for GIT, so that we can properly work and integrate on GITHUB.

**Comment by willi84** [comment]
@prateektalesara  can u be more specific what you have tried and what do you want to have? and maybe split bug and feature request. I guess this ticket is just a feature request?

Because if I take a random github repo and try to import a branch of it, it is working:

https://stackblitz.com/github/gothinkster/angular-realworld-example-app/tree/m-1

check where is the angular.json or angular-cli.json

**Comment by willi84** [comment]
I can also your one repo from github:

https://stackblitz.com/github/prateektalesara/angular-material-expandable-table-rows-xfwta7/tree/feature/testing_Stackblitz

![image](https://user-images.githubusercontent.com/6207308/58876483-87214400-86ce-11e9-885b-8b3263f27ca0.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
