### ISSUE TITLE
Online editor does not show page

### ISSUE THREAD

**Issue by MarcioPaulo** [stackblitz/core#982]
Online editor does not show page, fails with the following error
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://angular-testebase64.stackblitz.io') does not match the recipient window's origin ('https://stackblitz.com').

**Comment by EricSimons** [comment]
What browser are you using? Do you have 3rd party cookies/storage disabled (or have any adblockers on)?

**Comment by MarcioPaulo** [comment]
> What browser are you using? Do you have 3rd party cookies/storage disabled (or have any adblockers on)?

Google Chrome  74.0.3729.169
3rd party cookies/storage disabled (or have any adblockers on) - No.

It was working this morning. 05-28-2019

**Comment by MarcioPaulo** [comment]
I disabled all extensions, and it worked.
and now I'm activating one at a time to find out what's wrong.
thank you very much.

**Comment by ineam** [comment]
The issue should not be closed, as if you keep blocking 3rd party cookies on your browser, the embedded preview page won't render and still return the same errors as mentioned above.
And Stackblitz should fix this issue, it has not the right to force the user (especially European ones since GDPR law in 2018) to accept the 3rd party cookies so he can use Stackblitz.
