### ISSUE TITLE
Import error, can't find files:

### ISSUE THREAD

**Issue by ofirrifo** [stackblitz/core#992]
I created a GitHub repo using angular CLI.
This repo using a library I wrote.
When I'm running this repo locally it works as expected but when I try it with stackblitz
I get this error: 
```
Import error, can't find files:
../../lib/oop
../../token_iterator
...
```
as you can see from this [URL](https://stackblitz.com/github/ofirrifo/ngx-ace-demo?file=src%2Fapp%2Fapp.module.ts):

**Comment by markwhitfeld** [comment]
@ofirrifo This issue is now resolved!
The way that Ace was intercepting the `resolve` function in its AMD formatted file was confusing the StackBlitz cjs parser.
Also, the Ace package has some webpack loaders specified in some of the require statements, which was also wreaking havoc with the dependency resolution.
